### ISSUE TITLE
The largo_top_term function fails when there are multiple terms with the same term_id

### ISSUE THREAD

**Issue by rnagle** [INN/largo#1008]
Terms from different taxonomies can have the same `term_id` in the `$wpdb->term_taxonomy` table.

See: https://github.com/INN/Largo/blob/master/inc/related-content.php#L321

This doesn't seem to violate any primary key constraints -- the primary key for this table is `term_taxonomy_id`. Will need to find a way to attempt the `taxonomy` lookup without relying solely on the `term_id`.

**Comment by benlk** [comment]
Closing in favor of https://github.com/INN/largo/issues/1474
