### ISSUE TITLE
Term Featured Media: Docs

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1016]
- [x] how to set term featured media
- [x] how to edit
- [x] the places that this appears
- [x] what sort of things you can upload
- [x] what would you use this for
- [x] recommendations for image size and type and proportions and suchlike.

For RNS-60 and #928 and #1010.

**Comment by jackbrighton** [comment]
Can I be of help with this?

**Comment by aschweigert** [comment]
@jackbrighton yeah, probably just get a demo of this and then update the docs to reflect these things (and anything else you think makes sense)

**Comment by jackbrighton** [comment]
Docs updated in PR https://github.com/INN/Largo/pull/1048
