### ISSUE TITLE
largo_load_more_posts_choose_partial doesn't.

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1018]
Beginning with this issue, changes to any of the PHP functions regarding the Load More Posts functionality **[must](https://tools.ietf.org/html/rfc2119) include tests**. This is no longer optional. We've been bitten by it too many times.

From [we-47](http://jira.inn.org/browse/WE-47):

> Load more posts in Search Results yields a number of broken elements when you hit the Load More button several times. E.G.: http://womensenews.largoproject.org/?s=clinton
Same thing happens on author and category pages:
http://womensenews.largoproject.org/author/crystal-lewis/ http://womensenews.largoproject.org/category/media/

> ----

> This is loading the women's enews partials/content-home.php, which is puzzling, because in search and in the author archive it shouldn't be loading content-home at all. It should be loading content-archive for both contexts.

> ... it's loading 'home' because that's the default and what the LMP function is expecting is an array of query_vars, not the entire WP_Query object, and so it fails to trip any of the conditionals. And then if you feed it the array of query vars, because largo_load_more_posts_choose_partial is written using object notation because it's expecting an object for some reason, none of the conditionals trip, and so it returns 'home'. I swear this worked correctly in 0.5.2. Did WordPress change something under us, or has it never worked correctly and I am forsworn?

- [x] fix the bug
- [x] test coverage for `largo_load_more_posts_choose_partial` at bare minimum: https://github.com/INN/Largo/blob/master/tests/inc/test-ajax-functions.php
- [ ] test coverage for all LMP PHP functions if possible.

**Comment by aschweigert** [comment]
let's have a discussion re: tests as that is something that will require additional time (that we don't have at the moment)
