### ISSUE TITLE
add docs for new nav/header options

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#1029]

**Comment by jackbrighton** [comment]
Navigation notes are here: https://docs.google.com/document/d/1WpjfUqJ2kkvsABnP-wfmiyzWHjbD-bws3BhTVzuXehk/edit

**Comment by jackbrighton** [comment]
The new nav/header will first be deployed on http://rns.wpengine.com/. Ryan will indicate when that's available. I'll then need access to the WP dashboard to see how it works to write up the docs.

**Comment by jackbrighton** [comment]
Everything is on http://largoproject.staging.wpengine.com/ now so that's the place to see 0.5.4 in action.

**Comment by jackbrighton** [comment]
Docs have been updated on branch jack-docs-users-themeoptions-update, pull request pending review.
