### ISSUE TITLE
Floating social buttons cover up the left-hand sidebar on single-column posts

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1039]
<img width="999" alt="screen shot 2016-01-04 at 10 59 40 am" src="https://cloud.githubusercontent.com/assets/1754187/12093784/e7ae62f4-b2d2-11e5-8fe6-408993a9235c.png">

This can probably be fixed by adding another check to the FSB's method that determines the top offset.

**Comment by benlk** [comment]
Marked as low priority because we discourage the use of this sidebar, but it's still a bug.

**Comment by aschweigert** [comment]
also, we should probably move that sidebar to the right instead of the left and make it wider (pushing into the content). the current positioning is weird.

**Comment by benlk** [comment]
If we move the sidebar to the right (#1104), then this issue isn't needed, because the sidebar will not be in the same space as the floating social buttons.
