### ISSUE TITLE
Clarify explanation in Appearance -> Theme Options -> Navigation

### ISSUE THREAD

**Issue by jackbrighton** [INN/Largo#1041]
In this description in the Appearance - >Theme Options -> Navigation tab:

"By default, the sticky navigation bar is visible on all pages for mobile screen sizes. The sticky navigation bar will disappear when a user scrolls down and reappear on an up scroll. When the main navigation is visible, the sticky navigation will disappear."

Except: The main navigation is probably generally assigned to the sticky navigation (the location of which is named Main Navigation). Would be more clear if we renamed the menu location to Sticky Navigation. Then users would easily know which menu they are assigning to the Sticky Navigation location.

Meanwhile, can we delete the last sentence that reads "When the main navigation is visible, the sticky navigation will disappear"?  In many cases (perhaps most) it's self-contradictory.

**Comment by jackbrighton** [comment]
Updates to the Largo docs were submitted and merged in https://github.com/INN/Largo/pull/1055

**Comment by dryanmedia** [comment]
@jackbrighton can this ticket be closed?

**Comment by jackbrighton** [comment]
yep, all good. I added a section to the Largo Docs to clarify if anyone needs further clarification.
