### ISSUE TITLE
Sticky Nav in Largo 0.5.4 disappears on scroll to top in Safari/mobile view

### ISSUE THREAD

**Issue by jackbrighton** [INN/Largo#1045]
When viewing a Largo 0.5.4 Staging site in Safari in mobile view, the sticky nav behaves like it should until you scroll down and then all the way to the top where it disappears. You can get it to reappear by scrolling down again, then up, but when you hit the top it's gone. 

This occurs in Safari desktop and iOS 9.2.  

No such problem in Chrome/Mac and Firefox/Mac.

**Comment by dryanmedia** [comment]
This is identical to #1054, should have checked before I made. Going to close this issue out.
