### ISSUE TITLE
Flexbox?

### ISSUE THREAD

**Issue by benlk** [INN/largo#1058]
Microsoft [axed support for IE 7, 8, 9 and 10](https://asna.com/us/articles/newsletter/2015/q4/ms-kills-old-ies) on January 12, which means that [we can finally use flexbox](http://caniuse.com/#search=flexbox).

Do we want to use flexbox when we redo all the layouts?

**Comment by aschweigert** [comment]
http://reflexgrid.com might be worth a look, used it for the mother jones site, it's pretty light and didn't require a tremendous amount of reworking to implement (although there are probably all kinds of gotchas buried in largo that might make it more complex).
