### ISSUE TITLE
Combine more and more dropdown menus

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#1061]
Presently:

- When the main nav is too long it folds into a dropdown menu with a parent/trigger labelled "more" by default (uses a theme option to override)
- Many sites also use "more" as the label for the dropdown when the global nav folds into a dropdown at smaller screen sizes (uses the menu name instead of a theme option)
- This leads to two dropdowns labelled "more" and extra clutter

Instead:

- Let's append the global nav items to the same "more" dropdown menu and just have a single theme option to override the dropdown trigger/label

**Comment by rnagle** [comment]
Fixed in e3a6968675f59e9d5d75807a32efb5acc7462921.
