### ISSUE TITLE
Largo 0.5.4 Instructions for Sticky Header Logo in Theme Option need slight revision

### ISSUE THREAD

**Issue by jackbrighton** [INN/Largo#1065]
In Appearance > Theme Options > Theme Images > Sticky Header Logo, it says "Used in the sticky navigation. This image should be 100px tall and at least 100px wide. This logo will be hidden on mobile sites if the Show Site Name in Sticky Nav option is checked under Basic Settings." There is no such box to check in Basic Settings, so we should say something like "If no logo is provided the site name will be displayed."

**Comment by aschweigert** [comment]
assuming we add a new option to override the site name with a shorter version just for the sticky nav we'll probably also want to explain that here. sigh.
