### ISSUE TITLE
twitter share button always includes via attribute even if no author/site twitter account is provided

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#1088]
this used to be smarter...what happened?

**Comment by aschweigert** [comment]
to be clear, the via attribute here should use the post author twitter account (if provided) and then fall back to the site/publisher twitter account (from the theme options) and finally, if none of those are set, it should be omitted altogether.

**Comment by benlk** [comment]
In the event that there are multiple coauthors with Twitter handles, how should Twitter handle passed as the `via

**Comment by aschweigert** [comment]
in that case probably better to just fall back to the organization account
