### ISSUE TITLE
Issue trying to create uncompressed stylesheet (for documentation)

### ISSUE THREAD

**Issue by 1000camels** [INN/Largo#109]
I'm trying to produce an uncompressed style.css. I am getting an error. Am I using the right command. Any additional instructions on working the styles, especially in a child theme.

Largo darcy$ lessc less/style.less css/style-uncompressed.css 
ParseError: Unrecognised input in /Users/darcy/Web/wordpress/wp-content/themes/Largo/less/mixins.less on line 512, column 7:
511     .spanX (@index) when (@index > 0) {
512       (~".span@{index}") { .span(@index); }
513       .spanX(@index - 1);

**Comment by rnagle** [comment]
You can use grunt to compile the less files for Largo. Once you have grunt installed, try running `grunt less` or `grunt watch` from the root of the repo.

**Comment by rnagle** [comment]
I'll also mention that in the `css` directory, there are both minified and unminified versions of all the css for Largo.

If you still want/need to recompile the css files, you should follow the advice of my previous comment. Grunt has a great guide to help [get you get started](http://gruntjs.com/getting-started).
