### ISSUE TITLE
Support all custom Largo author meta fields in Co-Authors

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1097]
Our Co-Authors settings filter: https://github.com/INN/Largo/blob/master/inc/users.php#L50

Add:

- job title
- hide email
- hide in staff roster (if coauthors get sucked into the staff roster widget, that is?)

This will be a hotfix against Master.

**Comment by aschweigert** [comment]
job title? I think hide email is worth having, hide in staff roster is less important because guest authors don't (presently) appear in the staff roster so there would be more work involved in making it support those (add that role to the list of roles supported by the shortcode, etc.)

**Comment by benlk** [comment]
Job title because of http://jira.inn.org/browse/WE-72, to match its being an option for normal users in Largo: https://github.com/INN/Largo/blob/master/inc/users.php#L260-L266

If the staff roster doesn't include coauthors then there isn't a reason to add the option here and now, so I shan't. Do we want to support that in the future?

**Comment by aschweigert** [comment]
sorry, your original description just said "job" but the field should be called "job title" consistently in both places

**Comment by benlk** [comment]
Oh, sorry the confusion.
