### ISSUE TITLE
CSS for the Analytics Bridge Popular Posts widget is completely heinous

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1120]
Copying from @aschweigert's https://github.com/INN/analytic-bridge/issues/36

> i have no idea what's going on in there but it's not good.

**Comment by rclations** [comment]
Can we move the analytics bridge less file over to that plugin? 
`https://github.com/INN/Largo/blob/develop/less/inc/widgets/analytic-bridge-popular-posts.less`

I'm not sure it should exist in Largo if the plugin isn't itself a part of Largo.

**Comment by benlk** [comment]
If I recall correctly, we put this file in Largo because the styles were to integrate the plugin with Largo's appearance, instead of shipping styles for non-Largo users' sites that weren't going to match their styles.

**Comment by aschweigert** [comment]
Yeah and then I think we decided to remove it (or I did, anyway). Let's remove it and put it in the plugin where it belongs but simplify the styles if we can so they're more general, less fussy and more likely to work with a wider variety of themes.
