### ISSUE TITLE
Series landing page displaying different fonts before "load more posts" 

### ISSUE THREAD

**Issue by rnsbrian** [INN/Largo#1130]
http://religion.news/series/whats-new/

The title alignment with feature images is wonky at the above page. When we hit "load more posts" - the problem is fixed and font size increases for the new posts that load, but the first posts remain wonky.  We want the proper feature image placement and alignment that occurs after hitting "load more posts" to be replicated in the initial posts that load. 
![screen shot 2016-02-10 at 09 46 07](https://cloud.githubusercontent.com/assets/17156554/12941451/29ddce2e-cfdb-11e5-976b-67957aedebe8.png)

**Comment by aschweigert** [comment]
Hi Brian - 

It looks like you're using a slightly older version of Largo. This bug has been fixed in the latest version so you should just need to download and replace your current theme files, run the update script and you should be good to go.
