### ISSUE TITLE
Can't replace video thumbnail when using a Featured Video 

### ISSUE THREAD

**Issue by jackbrighton** [INN/Largo#1155]
When setting a Featured Video, uploading a new Video thumbnail does not replace the default original video thumbnail attached to the video. 

The custom video thumbnail uploads and displays in the Featured Media modal, but doesn't display in the post. The original video thumbnail displays instead. 

Tested with YouTube and Vimeo videos with same result.

**Comment by aschweigert** [comment]
Hm, when you say "displays on the post" do you mean the thumbnail that's displayed, for example, on the homepage? or actually on the individual article page itself?

**Comment by jackbrighton** [comment]
I meant the article page. Didn't notice that it displays on list pages. Maybe that's the way it was intended? It wasn't what I was expecting.

**Comment by aschweigert** [comment]
Hm, that's just strange because it should just be showing the embedded video...do you have a sample URL where this is happening?

**Comment by jackbrighton** [comment]
I suspect I wasn't thinking this through. Just to be clear, is it the case that:

- the custom video thumbnail should only show up on the homepage/section page
- the article page just has the video embed which is going to display the YouTube/etc thumbnail, not the custom thumbnail

That is the intended behavior?

**Comment by aschweigert** [comment]
yeah that seems right (i think)

**Comment by aschweigert** [comment]
so if they wanted the custom thumbnail to display in the actual embed they'd have to change that on youtube (which is possible, if it's their video)

**Comment by jackbrighton** [comment]
This makes sense.
