### ISSUE TITLE
Largo Related Posts widget options for Show Date and Thumbnail Position don't work

### ISSUE THREAD

**Issue by jackbrighton** [INN/largo#1158]
In Largo 0.5.4 the Largo Related Posts widget has two options that don't seem to have any effect on how the widget displays content:
- a checkbox option to "Show date with each post," which by default is not selected. The date displays regardless of the state of this checkbox.
- a Thumbnail position dropdown with values of "After Headline" and "Before Headline". Changing the value has no effect on position of the thumbnail.

**Comment by benlk** [comment]
Adding this to 0.6.4 so that if we pick up https://github.com/INN/largo/issues/1727 in 0.6.4, we remember to check for this bug.

**Comment by joshdarby** [comment]
@benlk I don't see either of those checkboxes in the `Largo Related Posts` widget?

![Screen Shot 2019-06-19 at 12 36 56 PM](https://user-images.githubusercontent.com/18353636/59783805-07c76f00-928f-11e9-86f8-11570257a677.png)

**Comment by joshdarby** [comment]
@MirandaEcho @benlk Looks like the option for the thumbnail placement was removed back in 2016 in commit https://github.com/INN/largo/commit/6f73365, and the option to display the date was replaced with the option to display the byline back also in 2016 in commit https://github.com/INN/largo/commit/c7d3e04.

**Comment by joshdarby** [comment]
And yes, the `Show byline on each post` checkbox option functions as expected.

**Comment by MirandaEcho** [comment]
@benlk looks like we can close this then. Can you confirm?
