### ISSUE TITLE
Largo Series Posts widget thumbnail position dropdown has no effect on thumbnail position

### ISSUE THREAD

**Issue by jackbrighton** [INN/largo#1159]
In the Largo Series Posts widget there's a dropdown menu for the Thumbnail position on the first post. Choices as "Before Headline" and "After Headline," but the thumbnail floats left of the headline regardless of this setting.

**Comment by benlk** [comment]
Adding this to 0.6.4 so that if we pick up https://github.com/INN/largo/issues/1727 in 0.6.4, we're reminded to check this.

**Comment by joshdarby** [comment]
@benlk Shouldn't we close this since we removed those options in #1727?
