### ISSUE TITLE
Improvements to search results page styles and markup

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1162]
For [RNS-198](http://jira.inn.org/browse/RNS-198):

- Clean up search results page
- Make search input box full width
- Use Largo default button styles
- Make font sizes sane in returned results 
- Increase space between the headline and the search results

**Comment by aschweigert** [comment]
@benlk why don't you take the first crack at this and pair with @julia67 as needed to work out the styling issues here.

**Comment by benlk** [comment]
Why do we have a link to an RSS feed of the search results? https://github.com/INN/Largo/blob/master/search.php#L69

Is this something that people use?

**Comment by aschweigert** [comment]
i don't think it hurts anything, probably just leave it for now

**Comment by benlk** [comment]
ok, cool.
