### ISSUE TITLE
Largo 0.5.4 second-level main nav doesn't open via Touch on iOS

### ISSUE THREAD

**Issue by jackbrighton** [INN/Largo#1166]
On Largo 0.5.4 sites with second-level links in the main menu, when viewed on an iOS phone, the second-level menu does not open upon touch. The main menu drops down from the hamburger icon, whereupon those menu links that have submenus display arrows indicating they should open on touch, but the submenus don't open.

On a desktop computer in mobile view, the submenus to open on click. So the issue seems to only occur on a iOS touchscreen in mobile view.

The issue does not occur on Android phones.

Example sites include:

- http://chicagoreporter.com/ (Help Desk ticket is open for this site: http://jira.inn.org/browse/HELPDESK-568)
- http://eyeonohio.org/
- http://gijn.org/
- http://jjie.org/
- http://investigatemidwest.org/
- http://mtcir.org/
- http://necir.org/
- http://indepthnh.org/
- http://oklahomawatch.org/
- http://raleighpublicrecord.org/
- http://voiceofoc.org/
- http://youthtoday.org/
- http://womensenews.org/

**Comment by benlk** [comment]
(Using a mouse on an Android phone is also not affected, fwiw.)

**Comment by aschweigert** [comment]
Let's try to address this in 0.5.5, but our general guidance should be that using second level dropdowns is generally a bad idea because the items therein will be all but invisible to users anyway (it's very rare for people to drill down that deep).

**Comment by jackbrighton** [comment]
This may be the same issue causing the Global Navigation "More" dropdown to not open on touch, as reported by Current.org here: http://jira.inn.org/browse/HELPDESK-641

**Comment by aschweigert** [comment]
it is, still not a high priority, but we'll try to address it in this next release

**Comment by jackbrighton** [comment]
I want to gently suggest that second level dropdowns might not get used a lot, but a significant number of Largo sites have them and they are currently broken on iOS devices. If a menu isn't important to users, and is also broken, it probably shouldn't exist. If it does exist it should work. Would be good to resolve this in Largo 0.5.5.

**Comment by aschweigert** [comment]
Let's do an audit of sites that actually have this issue and then decide. Personally, I'm pro just losing second level dropdowns and explaining to sites why they're going away.

**Comment by rclations** [comment]
I think this actually may be a js issue - looking into it

**Comment by rclations** [comment]
the issue here is that we have 2 sections overwriting each other and both opening/closing the nav.

First there's https://github.com/INN/Largo/blob/master/js/navigation.js#L37-L72, target specifically at mobile devices

Then the more generalized nav section in https://github.com/INN/Largo/blob/master/js/navigation.js#L166-L215

From my testing, I believe we can remove the entire mobile section (L37-72) and just keep the generalized parts (L166-215).

Thoughts on this?
I'm not sure of the background that led to 2 sections of code
