### ISSUE TITLE
largo_trim_sentences() needs support for AP-style month abbreviations and single-letter abbreviations

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1179]
The function: https://github.com/INN/Largo/blob/0db770f238dd3bc094b57ed2aa78e3bad5a283f4/inc/post-tags.php#L520

The following things count as the end of a sentence:

```
Mass. # State abbreviations
Jan. # Months
v. # used in court cases
Hon. # The Honorable, a title for judges
```

**Comment by aschweigert** [comment]
This is a duplicate, i'll try to find the other issue momentarily...

**Comment by aschweigert** [comment]
duplicate of #171
