### ISSUE TITLE
Add action in largo_google_analytics to allow modifying the Google Analytics object

### ISSUE THREAD

**Issue by benlk** [INN/largo#1180]
This is currently a pluggable function, so it's not that big a deal, but it might be nice to be able to do this.

Related: WE-77

**Comment by aschweigert** [comment]
Supporting custom dimensions should probably be the default behavior (sending over category and author information will be useful to a lot of sites). We can do this just in the WE theme at first, but whatever we do there has a very high likelihood of being moved back into Largo in the next release.

**Comment by benlk** [comment]
Custom dimensions are part of the Google Universal Analytics, and Largo still uses the old `ga.js` library.

There's an [upgrade guide and process](https://developers.google.com/analytics/devguides/collection/upgrade/) for moving from ga.js to analytics.js.

WE for now will use custom variables, unless you want to upgrade it and Largo to the new analytics.

**Comment by aschweigert** [comment]
Yes, we should do that.

**Comment by aschweigert** [comment]
see also #199

**Comment by aschweigert** [comment]
obviously that should be part of the next release though, not a hotfix

**Comment by rclations** [comment]
opened companion issue in no-nonsense-google-analytics, where this can continue
