### ISSUE TITLE
Replace all date/time h5 elements with properly-styled time elements.

### ISSUE THREAD

**Issue by benlk** [INN/largo#1182]
Largo has a bunch of these:

``` html
<h5 class="top-date">April 2, 2015</h5>
```

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time

This is more of a semantic wish than anything else.

**Comment by rclations** [comment]
see https://github.com/WordPress/twentyseventeen/blob/a15f8d1ed4003007b8e25330dc787cda7b7a32f7/inc/template-tags.php#L30-L50

**Comment by mikeschinkel** [comment]
@benlk Has this been handled already in the `develop` branch?  I can find no reference to `"top-date"` and `published_date()`, `largo_comment()` and `largo_edited_date()` are using `<time>` markup in the code I just cloned.

**Comment by benlk** [comment]
The only place I'm seeing this any more is in partials/content-search, where we have `<span class="date"><?php largo_time(); ?></span>`. When `largo_time()` outputs a date, it's only outputting the string, not HTML: https://github.com/INN/largo/blob/develop/inc/post-tags.php#L59

**Comment by mikeschinkel** [comment]
@benlk https://github.com/INN/largo/pull/1469

**Comment by benlk** [comment]
Resolved with #1469, but we have more h5 elements to remove. I'll create issues for those separately.
