### ISSUE TITLE
Check for WordPress 4.5 compatibility errors

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1188]
- [x] Add 4.5 to .travis.yml and remove the oldest version of WordPress from that list
- [x] Rerun tests
- [ ] Check for code enqueuing scripts on [load-edit-tags.php and update if necessary](https://make.wordpress.org/core/2016/03/07/changes-to-the-term-edit-page-in-wordpress-4-5/)

**Comment by benlk** [comment]
- [ ] some breaking changes in Backbone and Underscore: https://make.wordpress.org/core/2016/02/17/backbone-and-underscore-updated-to-latest-versions/

**Comment by aschweigert** [comment]
@benlk is this still needed? or are we good with the update to 4.6?

**Comment by benlk** [comment]
There's a persistently-failing test in Wordpress 4.5 and 4.6 that's related to terms, probably because of the new WP_Term object.

I'm not sure if we ever did the stuff for https://make.wordpress.org/core/2016/03/07/changes-to-the-term-edit-page-in-wordpress-4-5/

**Comment by aschweigert** [comment]
fixed, yes?

**Comment by benlk** [comment]
According to https://travis-ci.org/INN/Largo/builds/163140174, yes, it's fixed.
