### ISSUE TITLE
If Largo Related Posts widget is placed, but not saved, it outputs infinite posts.

### ISSUE THREAD

**Issue by benlk** [INN/largo#1195]
By not saving the widget, the `$instance['qty']` is not set, which means that when the widget [calls Largo_Related](https://github.com/INN/Largo/blob/master/inc/widgets/largo-related-posts.php#L30), it does so for `null` posts.

I think this is happening because `empty( null )` is true, and so `Largo_Related::__construct()` [does not set `$this->number`](https://github.com/INN/Largo/blob/a5a0b7fdaedcfe261023be7e6f642956d51e58b4/inc/related-content.php#L419-L421) (I think?).

Anyhow:
- [x] make sure that the widget has a default of `1` related post in the `widget` function
- [ ] make sure that `Largo_Related` has a default of `1` in the constructor

**Comment by rclations** [comment]
@benlk are you able to reproduce this still? I'm not able to so far

**Comment by benlk** [comment]
Now fixed in the widget in Largo branch `0.5-dev`: https://github.com/INN/largo/blob/213fab08974c01e96fdad1f9b006f2185f729980/inc/widgets/largo-related-posts.php#L29-L33

This was harder to reproduce because WordPress started saving the widget when you inserted it in the widget settings. This behavior appears in the Customizer, which doesn't save the widget immediately.

**Comment by benlk** [comment]
Largo_Related has the default 1 already: https://github.com/INN/largo/blob/0a3417f574736ecf1ed4d6a08ed0736dce786a03/inc/related-content.php#L491
