### ISSUE TITLE
Widget title link doesn't work on some widgets

### ISSUE THREAD

**Issue by jackbrighton** [INN/largo#1201]
The Link field in widgets is supposed to make the widget Title a link to whatever url is entered in the Link field. With some but not all widgets, a url entered in the Link field has no effect. 

Known widgets where the Link field doesn't work:
- Largo Image Widget
- Largo Author Bio widget (should probably not even have a Link field)
- Largo Prev/Next Links widget (should not even have a Link field since there is no Title field)
- Events Calendar widget (plugin)
- Largo Series Posts
- Largo Staff Roster
- Saved Links
- Link Roundups

Would need to do an audit of all widgets to complete this list.

In addition, having an option for a link title probably doesn't make sense in some cases:
- Largo Explore Related
- Largo Featured Posts ("In case you missed it")
- Largo Disclaimer (this widget doesn't have a title field)
- Largo Related Posts (defaults to Read Next. Even if used on a Series page, it's confusing to have a title link here)
- Largo Tag List (Title defaults to "Filed Under" while each tag links to the tag archive page. No reason for the Title to have a link)
- Largo Taxonomy List (contains links to taxonomy terms; the Title doesn't need a link)

**Comment by benlk** [comment]
The widget title link functionality described here would be a good candidate for pluginification.

**Comment by benlk** [comment]
Closing this in favor of individual issues, which are created as a review of widgets is completed in #1736.
