### ISSUE TITLE
Clean up styles for heading elements

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1206]
In most cases where we need a specific size for an `h1`, `h2`, `h3`, `h4`, `h5`, `h6`, the styles for that are scoped directly to the situation where we need that heading sized.

But by far and above, the places where we use headings are the `h3.widgettitle` elements in sidebars, a constellation of utility `h5.whatever` elements for tags, bylines and top terms.

The place where our users use header elements the most is in the entry content.

Do we use any bare h1 or h2 elements? Why do they get separate sizes when https://github.com/INN/Largo/blob/master/less/inc/typography.less#L52-L95 makes the bare elements' styles defunct for use inside `.entry-content`?

**Comment by aschweigert** [comment]
Having a baseline is important, even if you tend to override it for more narrowly-scoped styles. I don't see a problem here, but am I missing something?

**Comment by benlk** [comment]
It's not really a problem, just occasionally annoying to have to override the .entry-content heading styles for widgets.

**Comment by aschweigert** [comment]
It's presently fairly unusual to have widgets within the .entry-content div so this is probably more of an exception than a rule
