### ISSUE TITLE
Posts sometimes display twice in the Top Stories box of the "One big story and list of stories from the same series" homepage layout

### ISSUE THREAD

**Issue by jackbrighton** [INN/largo#1212]
When using the homepage layout "One big story and list of stories from the same series," the single story with full-width image is sometimes also displayed as a headline to the right of the big story. 

It seems to be the case that if the most recent post is part of a series, it displays as the featured story and doesn’t repeat in the right-side headlines. You don’t need to assign post prominence of Homepage Featured to it if it’s the newest post.

If you assign Homepage Featured to a series post published earlier than the latest post in that series, it repeats in the right-side headlines.

![iowawatch-top-stories](https://cloud.githubusercontent.com/assets/506788/14969772/c11cfbe0-1089-11e6-96b9-5d395a5eb9b2.png)

Also just noting that Homepage Top Story has no effect when using this layout. The most recent Homepage Featured post is displayed as the Big Story, regardless of whether or not it's part of a Series. If it's not part of a Series, the other Series posts' headlines are not displayed in the Top Stories box. If we're fixing the issue raised above, it might make sense to use a Post Prominence of Homepage Top Story to key the Big Story, rather than Homepage Featured.

**Comment by benlk** [comment]
Needs replication conditions, unfortunately.

**Comment by benlk** [comment]
Closing unless we can reproduce.
