### ISSUE TITLE
Largo Recent Posts widget set to "Avoid Duplicate Posts" won't display posts hidden in Recent Stories list

### ISSUE THREAD

**Issue by jackbrighton** [INN/Largo#1219]
From Help Desk ticket: http://support.largoproject.org/helpdesk/tickets/33

Website: http://iowawatch.org/

This problem applies to the three "big story" homepage layouts that have a "recent stories" link in the featured stories box, which links to the river view of homepage posts.

From the ticket (with editing for clarity): "I am writing about the category heading in the left column (Business & Consumer Affairs). I have posted the stories under the We Recommend widget in the right sidebar because they do not show up elsewhere. I would rather they be under category headings. Blighted Housing: Inspections Fail To Stem Poor Conditions For Migrant Farmworkers, just posted, is marked for business and consumer affairs only and we still are having the problem. I tried with only one heading with the other giving me problems, University of Iowa Fuels Concern Over Women's Coaching Job Losses."

With the Largo Recent Posts widget set to Avoid Duplicate Posts, the most recent post in the category of Business & Consumer Affairs isn't displaying in the widget, nor is it visible on the homepage. It is, however, in the river view of the homepage that's only visible after clicking the "recent stories" link in the upper-right of the features box. It seems the widget won't repeat those stories even though they are hidden in the default view, and don't appear on the page at the same time.

Here are all the posts assigned the category of Business & Consumer Affairs on this site:
http://iowawatch.org/wp-admin/edit.php?category_name=consumer-affairs

It probably doesn’t make sense that those would be added to the list of posts to not duplicate because they don’t ​*really*​ appear on the page at the same time.

**Comment by rclations** [comment]
Can we ask them if there's a current instance of this issue? I'm unable to reproduce at the moment.

On my local vagrant, I set all posts published after the **Blighted Housing** piece to drafts, but the Blighted Housing piece is showing up under the `BUSINESS & CONSUMER AFFAIRS` heading, in the sidebar under `WE RECOMMEND`, and at the top of the `Recent Stories` alternate display.

**Comment by rclations** [comment]
reply from IowaWatch - 

> I did a fix. I created a new category for the top story only. When we do a new top story I will change the category for our most recent one to Government and Politics.
>
>Change the category on the top story to Gov and Politics and see what happens to the category box below. It should go to a July story about Iowa Gov. Terry Branstad and Donald Trump.

additional notes from Jack -

>the Largo Recent Posts widgets in the Home Bottom Left and Center widget areas *should* display the most recent posts in their respective categories (e.g. Government & Politics), unless the most recent posts are already displayed above in the featured posts area
>
>That is, when the Avoid Duplicate Posts option is selected in the widget
>
>But they don’t display the most recent posts in the respective categories
>
>they seem to skip seven posts and display the eighth
>
>at least in the Government & Politics category which I just tested, but I’m assuming the other widgets would behave the same
