### ISSUE TITLE
Button to set Term Featured Media does not open featured-image box

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1224]
This is on the develop branch, with WordPress 4.5.2.

> The button doesn’t work to assign a term banner image. I have tried in chrome and firefox after cleared caches and a restart, Ron has tried in chrome. The button doesn’t seem to want to activate.

This doesn't cause any JavaScript errors.

**Comment by benlk** [comment]
Can't reproduce this in vagrant or in the staging site for the production instance concerned.

Staging and production are using:

- the same versions of Largo
- the same versions of WordPress
- INN/analytic-bridge
- Better WordPress Google XML Sitemaps
- Disqus
- DoubleClick for WordPress
- Easy Digital Downloads - Restrict Content Pro Member Discounts
- Easy Digital Downloads - Stripe Payment Gateway
- Edit Flow
- GP Pay Per Word
- GP Preview Submission
- GP Word Count
- Gravity Forms Coupons Add-on
- Gravity Forms MailChimp Add-On
- Gravity Forms Stripe Add-On
- Gravity Perks
- Link Roundups
- Redirection
- Regenerate Thumbnails
- RNS EDD Customizations
- RNS Transmissions
- Simple History 2.5.5 (outdated, current is 2.6)
- INN/super-cool-ad-inserter-plugin
- Term Debt Consolidator
- User Role Editor

Staging is using:

- Coauthors Plus 3.1.1
- Easy Digital Downloads 2.5.13
- Gravity Forms 2.0-beta-2
- Restrict Content Pro 2.5.2
- **SearchWP**

Production is using:

- Coauthors Plus 3.2.1
- Easy Digital Downloads 2.5.16
- Gravity Forms 2.0-rc-1
- Restrict Content 2.5.4
- **Aksimet**

There is a slight display difference between vagrant/staging and production, which appears to be because vagrant/staging is enqueueing `/wp-content/themes/largo/css/featured-media.css` and production is not?

- [ ] update plugins on staging to match production
- [ ] see if that causes a problem

**Comment by benlk** [comment]
Updating plugins on vagrant to match production did not cause this error until *after* I updated vagrant to WordPress 4.5.2.

Cleared:

- [x] Akismet
- [x] Restrict Content
- [ ] Coauthors Plus
- [ ] Easy Digital Downloads
- [ ] Gravity Forms

**Comment by benlk** [comment]
These aren't enqueued on affected pages:

```html
<link rel="stylesheet" id="largo_featured_media-css" href="http://rns.staging.wpengine.com/wp-content/themes/largo/css/featured-media.min.css?ver=4.4.3" type="text/css" media="all">
<script type="text/javascript" src="http://rns.staging.wpengine.com/wp-content/themes/largo/js/featured-media.min.js?ver=4.4.3"></script>
```

**Comment by benlk** [comment]
This appears to affect all Largo taxonomies in WordPress 4.5.2.

**Comment by benlk** [comment]
All term edit screens now use the admin url `term.php`, which isn't in this array of when to enqueue the relevant scripts and styles: https://github.com/INN/Largo/pull/1010/files#diff-216f6d639b07286f59ca7d39193160f8R342

Since this affects all sites in 0.5.2, I'd like to make the fix in master and then merge master back into develop. @INN/tech-team does course of action make sense?

**Comment by benlk** [comment]
#1125 merged.

**Comment by jackbrighton** [comment]
Was this bug fix deployed? I can set Featured Media for a taxonomy term on Staging, but not Production. 

Mississippi Today just filed a [ticket](http://support.largoproject.org/helpdesk/tickets/51) asking if it's possible to add a banner on Category pages, and this would fulfill what they're asking about.

**Comment by benlk** [comment]
No, this hasn't been deployed to production yet.

**Comment by benlk** [comment]
Production is currently checked out at cdcd8ab843e2b37fda18c037829a668b1c020209, and the only things that have changed between then and now are this PR and a bunch of docs.

**Comment by aschweigert** [comment]
let's go ahead and get it deployed. @jackbrighton the styles for this are pretty rough so they'd need to think through what exactly they want and we'd probably need to add some custom styles to support it.

**Comment by jackbrighton** [comment]
Here's what a 1170px image looks like on a Category page on MSToday/Staging. Not too bad:

http://mstoday-largoproject-wpengine-com.largoproject.staging.wpengine.com/category/education/

**Comment by aschweigert** [comment]
Yeah, the main thing is that many orgs seen to want to use this and put text in the image (or overlay the text on the image) for the category title so it's sort of a case-by-case sort of thing unless we come up with some kind of "standard" approach

**Comment by benlk** [comment]
Deployed.
