### ISSUE TITLE
Make homepage templates pluggable

### ISSUE THREAD

**Issue by benlk** [INN/largo#1229]
The goal here is to make as much of Largo's homepage templates into zone functions, and then to make those zones pluggable functions, so that child themes can redefine one function instead of [duplicating two whole files](https://bitbucket.org/projectlargo/theme-insideenergy/commits/a3adfa6f75fde677330fbb673f537af10fb3deaa) to change a part of the layout.
- [ ] Homepage templates should use [get_template_part](https://developer.wordpress.org/reference/functions/get_template_part/) to [load templates](https://github.com/INN/Largo/blob/master/homepages/layouts/TopStories.php#L9) from the stylesheet dir first, falling back to the template dir. This makes it easier for child themes to override the Largo parts.
- [ ] All functions [in the default Largo zones file](https://github.com/INN/Largo/blob/master/homepages/zones/zones.php) should be [made pluggable](https://codex.wordpress.org/Pluggable_Functions)
- [ ] ???

**Comment by rclations** [comment]
Well be switching the homepage generator by 0.9 so this will hangs anyway
