### ISSUE TITLE
Term Featured Media dialog lost its "remove featured media" option

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1238]
This is currently a problem on the develop branch.

- [ ] Remove featured media option is not displaying
- [ ] featured embed code, featured video, featured gallery options are showing when should not be
- [ ] "override display of featured image for this post" is not working.

**Comment by benlk** [comment]
Of primary import: *why did the remove button disappear?*

**Comment by benlk** [comment]
Confirmed, this is not a child theme issue. This is Largo

**Comment by benlk** [comment]
With largo `develop`, no child theme, and WP 4.5.3, 4.5.2, 4.5.1, 4.4.3. How old is this issue? Is this a plugin problem?

Gonna go try a different install, without plugins.

**Comment by benlk** [comment]
Adam suggested https://github.com/publicmediaplatform/pmp-wordpress/commit/ead1816884ca327dad23e8684806713c93902296 as a possible solution to a possible problem, but Largo's featured media doesn't use Underscore - it uses `wp.media` to handle the templating.

Here's a sample workflow:

0. Open the term's edit page
1. Set a term's featured media, and save it. Close the editing page.
2. View the term's archive: the featured media should display, if it is a thing that does display
3. Open the term's edit page
5. Despite having previously set the term featured media, the button reads "Set Featured Media" instead of "Edit Featured Media"
6. If you set a new featured media again and save the TFM dialog (this closes the dialog), then re-check the term's archive, nothing has changed on the archive: the media is still displayed.
7. If, after setting a new featured media, you re-open the dialog by clicking the "Edit Featured Media button", the "Remove featured media" button now does appear. It doesn't appear if you're coming to this from a fresh page load.
    - Clicking the "Save Term" button is the same as reloading the page. The "Removed featured media" will not appear until you re-set the featured media.
8. Click "Remove featured media", check the term listing page: it's gone

The workaround for affected sites is:

1. Set the term featured media to the thing it was.
2. Edit the term featured media, click "remove featured media"
3. Save the term.

But all this points to a problem when the page is rendered; not a problem in the javascripts.

**Comment by benlk** [comment]
https://github.com/INN/Largo/blob/master/inc/featured-media.php#L351 

This doesn't work for terms!

**Comment by benlk** [comment]
Actually, no, that should be a PR on Master and then merged into dev, because this is affecting sites in prod now

**Comment by benlk** [comment]
#1239 merged into master, so I'm going to merge master into develop and close this ticket.

**Comment by benlk** [comment]
#1239 fixed it in WordPress 4.5.x

But it broke it in 4.4.x

(╯°□°)╯︵ ┻━┻

**Comment by benlk** [comment]
(This is less of a problem, because WPEngine production environments are running 4.5 right now, but some staging sites are running 4.4.x and non-INN-hosted users of these themes may also be using 4.4)

(It breaks Largo compatibility with 4.4 and previous, I believe)

**Comment by aschweigert** [comment]
I'm not that worried about 4.4, let's not spend a bunch of time on that. Given that we're about to rework a lot of things anyway, let's focus on things that are actually broken for the sites that we host/support. If they're using 4.5+ then 4.5+ is our target.

**Comment by benlk** [comment]
OK. I'm going to tag this wontfix.
