### ISSUE TITLE
contributing.md should contain information on choosing develop or master branch

### ISSUE THREAD

**Issue by benlk** [INN/largo#1253]
Proposed guidelines:
- Create a branch from `master` and file your pull request against `master` if:
  - your pull request contains a fix for a bug in production
  - your pull request is needed for a feature in a site on production (rare)
  - your pull request updates documentation for a feature already in `master`
- Create a branch from `develop` and file your pull request against `develop` if:
  - any other reason

A PR fixing this would go in the `master` branch, because that's where Github draws it from.

https://github.com/INN/Largo/blob/master/contributing.md

**Comment by aschweigert** [comment]
sure, that seems fine to me, except I'd probably reverse the order there and say that typically you'll want to create a branch and file a pull request against develop with the following exceptions...

**Comment by benlk** [comment]
`master`, `develop`, and `1.0` are currently working on the full rewrite of Largo, while `0.5` and `0.5-dev` keep track of the present production branch of Largo and its development work, respectively. https://github.com/INN/largo/commit/72cc8433a1be1de4f22789e1ec89496d54a653d9#diff-0730bb7c2e8f9ea2438b52e419dd86c9 in `0.5` closes this issue now that `0.5` is the default branch.
