### ISSUE TITLE
Docs for #1285

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#1309]
The add/edit featured media button is moved back to the right column when creating/editing posts, let's make sure our docs reflect the change.

**Comment by benlk** [comment]
Is this in the Largo user docs?

**Comment by jackbrighton** [comment]
I'll add it for sure.

**Comment by jackbrighton** [comment]
This is updated in the Largo User Guide. All references to the Set Featured Media button, and all related screenshots, now reference the Featured Image panel in 0.5.5.
