### ISSUE TITLE
If a post has no top term and no category, largo_top_term's fallback displays nothing

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1340]
https://github.com/INN/Largo/blob/09367b17e4d49578dbcc22d9c0829d3668a1e3f5/inc/related-content.php#L332-L336

**Comment by aschweigert** [comment]
more specifically, if a post is in the "uncategorized" category we get nothing even if a top term is set (to a tag or something)

**Comment by benlk** [comment]
So this looks like this check https://github.com/INN/Largo/blob/09367b17e4d49578dbcc22d9c0829d3668a1e3f5/inc/related-content.php#L334

Should instead lead to querying for tags associated with the post, and putting one of those up.

**Comment by benlk** [comment]
Fixed with https://github.com/INN/Largo/pull/1094
