### ISSUE TITLE
Desktop sticky nav menu dropdowns don't drop down on larger touchscreens

### ISSUE THREAD

**Issue by benlk** [INN/largo#1368]
This is true from 769px upwards.

<img width="812" alt="screen shot 2016-10-28 at 12 15 23 pm" src="https://cloud.githubusercontent.com/assets/1754187/19813561/438a2502-9d08-11e6-8fc5-4b354470bb97.png">

**Comment by benlk** [comment]
Reopening for the following browsers:

- Mac with latest OS X and Safari
- Windows 10 in any browser, but with touchscreens

**Comment by julia67** [comment]
Here's one option for a fix: https://github.com/INN/umbrella-freshenergy/blob/e4b85bcde4e9d4f077127e6ed8f26ceca422ee89/wp-content/themes/freshenergy/footer.php#L264-L293

**Comment by rclations** [comment]
I'm not sure we should be doing anything here - if touchscreens are changing the default behavior to adapt to their interface, we should let them and stay out of the way. As long as we're using standard css dropdowns, I think we can leave this alone.

**Comment by julia67** [comment]
Problem is Largo's css dropdowns don't work on touchscreen devices at all - including tablets/phablets/ipads/etc. It's a problem we need to address at some point.

**Comment by rclations** [comment]
I can confirm this issue is displaying on ipad (standard size)

**Comment by benlk** [comment]
Here's some sample HTML:

```html
<li class="menu-item menu-item-type-taxonomy menu-item-object-region menu-item-has-children dropdown menu-item-1092724"><a href="https://energynews.us/region/southeast/" class="dropdown-toggle">Southeast <b class="caret"></b></a>
<ul class="dropdown-menu">
	<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1092753"><a href="/?category_name=news&amp;region=southeast">News</a></li>
	<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1092756"><a href="/?category_name=opinion&amp;region=southeast">Opinion</a></li>
</ul>
</li>
```

The hover effects are hooked on `.no-touch` CSS classes set by Modernizr, so we'd need a fallback set of interactions.

https://github.com/INN/largo/blob/72cc8433a1be1de4f22789e1ec89496d54a653d9/less/inc/navbar-common.less#L452-L457

Or we could investigate why the `.open` class isn't being applied by tapping on the dropdown trigger element.

I think it's because of the type of event we're listening for here?

https://github.com/INN/largo/blob/72cc8433a1be1de4f22789e1ec89496d54a653d9/js/navigation.js#L45-L64

But it may also be a symptom of broader `touchstart` vs `click` changes that need to happen in the navigation JS in response to browser API changes.

**Comment by benlk** [comment]
Worth noting that we already have touch/tap/click-agnostic in the nav js here:

https://github.com/INN/largo/blob/72cc8433a1be1de4f22789e1ec89496d54a653d9/js/navigation.js#L180-L185

#1544 co-opts that.
