### ISSUE TITLE
Homepage with series stories template duplicates main post

### ISSUE THREAD

**Issue by benlk** [INN/largo#1384]
<img width="922" alt="screen shot 2016-12-09 at 2 17 34 pm" src="https://cloud.githubusercontent.com/assets/1754187/21061420/49b793fa-be1a-11e6-9b93-d4f93b83083d.png">

http://wisconsinwatch.org/ says that it's happening regularly.

**Comment by aschweigert** [comment]
known issue (there's already an issue in largo somewhere for this). #wontfix unless it's critical for them (and probably unless a client is willing to pay for it) per our policy of critical fixes only to the current codebase

**Comment by benlk** [comment]
There's https://github.com/INN/Largo/issues/1381 which is a different duplication set; not seeing one for this specific issue.

**Comment by rclations** [comment]
the issue is that we're adding the main story to `shown_ids` in https://github.com/INN/Largo/blob/master/homepages/templates/full-width-image.php#L6

but [`$moreStories`](https://github.com/INN/Largo/blob/master/homepages/templates/full-width-image.php#L28) has already been defined before this template has been loaded

I'm not sure how to fix this without refactoring a bunch of the code, so we'll have to leave it out of the current point release.

**Comment by benlk** [comment]
in the template, we use [largo_home_story_top()](https://github.com/INN/Largo/blob/master/homepages/homepage.php#L93) to grab the ID for the top story. That function doesn't check `$shown_ids`, so we can run it wherever $moreStories is defined.

`$moreStories` is defined [through magic](https://github.com/INN/Largo/search?utf8=%E2%9C%93&q=morestories).

There are two concerned functions for generating `$moreStories`.

- `homepage_feature_stories_list()` gets its posts from `largo_home_featured_stories()`, which [already excludes](https://github.com/INN/Largo/blob/56c40405990d7693fadfa082196b5339963d445b/homepages/homepage.php#L153) the top story, so we don't have to worry about that.
- `homepage_series_stories_list()` uses largo_get_the_main_feature() on the post returned by largo_home_single_top() to get a taxonomy term, and then uses largo_get_recent_posts_for_term to get the posts from that term. 

[`largo_get_recent_posts_for_term( $term, $max=5, $min=1 )`](https://github.com/INN/Largo/blob/922ede22117298e118589d01d85d4dfc9f78fb21/inc/related-content.php#L163) doesn't have an `exclude` argument, but we could easily add one. Default to empty array, set to an array of IDs in the homepage.

It wouldn't break the function anywhere else in the theme, I don't think.

**Comment by aschweigert** [comment]
let's not spend any more time on this, per my comment above, this is a wontfix unless we have someone paying for the work because we have much bigger fish to fry at the moment

**Comment by benlk** [comment]
Fixed in #1388.
