### ISSUE TITLE
Make circular avatar images for authors in bylines the default

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1386]
- [ ] copy styles from Rivard
- [ ] make sure that sites currently with square avatars are okay with the transition

For PublicSource

**Comment by rclations** [comment]
We should leave the point release as bug fixes only, but this feature should definitely be considered for the next major release

**Comment by aschweigert** [comment]
this looks pretty rough as-is so i would like this to be moved into master in the next point release (0.5.5.3)
