### ISSUE TITLE
If the options framework hasn't been initialized, you get a "var_log does not exist" error

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1390]
https://github.com/INN/Largo/commit/b0bfc398bd139923d6dc9a8a4071b1999d35ee84 causes a white-page error if the value in the wp_options table for the option_name `optinosframework` is not parseable as something like this:

```
a:2:{s:2:"id";s:11:"child_theme";s:12:"knownoptions";a:1:{i:0;s:5:"largo";}}
```

**Comment by benlk** [comment]
Fix is to remove var_log from those lines and replace them with an appropriate logging function, like the PHP native functions var_log is composed of.

**Comment by aschweigert** [comment]
or just remove it, which is a thing we can do, correct?

**Comment by benlk** [comment]
Fixed in https://github.com/INN/Largo/commit/f8c5e3b093790ec8352fbb40d7517c801620e217
