### ISSUE TITLE
featured media preview not reflected on modal close

### ISSUE THREAD

**Issue by aschweigert** [INN/largo#1409]
On a single post, when new featured image/media is set, saved and the modal closes, the metabox displaying the featured thumbnail changes state and the button reflects edit/set featured media but the thumbnail does not appear to reliably update.

Ideally, the metabox should reflect the current thumbnail immediately after the modal is closed without requiring the post to be saved or the page refreshed.

**Comment by benlk** [comment]
Is the featured media being set using the dedicated "Set Featured Media" button or the "Set as Featured" button in the "Add Media" diaog? https://github.com/INN/Largo/issues/1399

**Comment by aschweigert** [comment]
This is using the dedicated set featured media button in the custom metabox. We may patch this but just fyi for your internal purposes, in user testing literally every user has mentioned this as a thing that trips them up so it's definitely worth fixing (imo)

**Comment by rclations** [comment]
💯  agree that the current UI is not good.

We'll be spinning this out into it's own plugin for Largo 1.0, but the UI here will have to be fixed as a part of that so it mimicks core exactly.

**Comment by rclations** [comment]
moving to https://github.com/INN/featured-media/issues/3
