### ISSUE TITLE
Remove INN Member Badge

### ISSUE THREAD

**Issue by rclations** [INN/largo#1443]

**Comment by benlk** [comment]
As part of this, make sure there's an action in Largo where it can be output, and that the CSS rules in https://github.com/INN/largo/blob/09367b17e4d49578dbcc22d9c0829d3668a1e3f5/less/inc/footer.less#L41-L59 are updated if any changes need to be made.

The INN Member Badge output itself can just cut https://github.com/INN/largo/blob/56c40405990d7693fadfa082196b5339963d445b/inc/header-footer.php#L74-L89 from largo.

**Comment by rclations** [comment]
I think this should just be handled as something super minimal in https://github.com/INN/inn-members/issues/4 - maybe shortcode?

**Comment by benlk** [comment]
And then, for largo, add a do_shortcode call on the appropriate action?

**Comment by rclations** [comment]
that can be done in a child theme or preferably in a widget for the end user
