### ISSUE TITLE
Changing the homepage top story prominence term name from "Top Story" to anything else breaks expected behavior of largo_home_single_top()

### ISSUE THREAD

**Issue by benlk** [INN/largo#1445]
[In largo_home_single_top()](https://github.com/INN/largo/blob/v0.5.5.3/homepages/homepage.php#L98):

```php
$top_story_term = get_term_by( 'name', __('Top Story', 'largo'), 'prominence' );
```

This means that if a site renames their top story prominence term to, say, "Homepage Top Story", the value of `$top_story_term` will be `false`, and so it falls back to `__('Homepage Featured', 'largo')`.

Can we change these `get_term_by()` calls to the largo-created, uneditable slug for these terms, instead of using the assumption that the term name has not been edited from the translated version of the Largo-provided default term name?

See https://secure.helpscout.net/conversation/374740864/932/

**Comment by benlk** [comment]
Check to see if this is still the case.

**Comment by benlk** [comment]
This appears to still be the case.

**Comment by benlk** [comment]
The reason this is problematic is because many of Largo's homepages instead use "Homepage Top Story" as the name for that term: https://github.com/INN/largo/blob/72cc8433a1be1de4f22789e1ec89496d54a653d9/homepages/layouts/LegacyThreeColumn.php#L17-L23

**Comment by joshdarby** [comment]
@benlk This is ready for review in PR #1709
