### ISSUE TITLE
When switching to PHP 7.0, the Largo_Settings class throws a deprecated error

### ISSUE THREAD

**Issue by jonathanstegall** [INN/largo#1452]
I'm using the Homebrew PHP switcher and the 1.0 Largo branch. When I run `sphp 70` and then load a page, it gives this warning:

`PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; Largo_Settings has a deprecated constructor in /path-to-wordpress/wp-content/themes/largo/inc/settings.php on line 9`

Largo_Settings is like this:

```
$settings = new Largo_Settings();

class Largo_Settings {
	function largo_settings() {
		add_filter( 'admin_init' , array( &$this, 'register_fields' ) );
	}
...
}
```

So there's no constructor at all. I think the deprecation is meant to remove things like this:

```
<?php
class Foo
{
    function Foo()
    {
        //some initialization code
    }
}
?>
```

But it apparently also will display when there's no constructor of any kind.

**Comment by rclations** [comment]
is this `1.0` branch?

**Comment by jonathanstegall** [comment]
Yes. I updated the first line to say that.
