### ISSUE TITLE
Fix Various Issues from Theme Check

### ISSUE THREAD

**Issue by rclations** [INN/largo#1460]
>The theme check plugin is an easy way to test your theme and make sure it’s up to spec with the latest theme review standards. With it, you can run all the same automated testing tools on your theme that WordPress.org uses for theme submissions.

## Step 1: Install this plugin and run it on the current version of Largo:
https://wordpress.org/plugins/theme-check/

At first glance, there are a _lot_ of issues listed here.
Feel free to jump in on any of these and work on them, but here are a few of the easier ones to pick out:
- #1458
- #1459

**Comment by benlk** [comment]
Duplicative of https://github.com/INN/largo/issues/844
