### ISSUE TITLE
Notice: Undefined index: largo_featured_widget in /var/www/wp/wp-includes/widgets.php on line 1039 in Customizer

### ISSUE THREAD

**Issue by mikeschinkel** [INN/largo#1467]
This default widget appears to have been removed from the code.  I will provide a pull request with all those defaults commented out and an `@see` to this issue.

**Comment by benlk** [comment]
Which branch is in this in?

**Comment by mikeschinkel** [comment]
@benlk @rclations is working with me on it.

**Comment by benlk** [comment]
PR for this is https://github.com/INN/largo/pull/1469

**Comment by benlk** [comment]
Part of #1492.
