### ISSUE TITLE
Largo declares support for title-tag but doesn't implement it

### ISSUE THREAD

**Issue by benlk** [INN/largo#1470]
https://github.com/INN/largo/blob/v0.5.5.3/functions.php#L424

in the function largo_setup, we declare theme support for `'title-tag'`. `'title-tag'` means that the theme doesn't have any `<title>` tags in it, and the ones that are there are wrapped as backwards-compatibility functions for WordPress versions before 4.1. [See the Codex article](https://codex.wordpress.org/Title_Tag) for what the backwards compatibility function looks like.

The reason this is a problem is because we have both `add_theme_support( 'title-tag' );` and `<title` tags in the `header.php` file. We should have either one or the other.

https://github.com/INN/largo/blob/v0.5.5.3/header.php#L24-L25

The theme-output `title` tag pairs with the WordPress-output `title` tag to result in all Largo sites outputting two different title tags.

Most people notice this when they activate an SEO plugin like Yoast, which, seeing the `title-tag` support, modifies the WordPress-output title tag, but because that comes after the Largo-output title tag, it doesn't affect the actual parsed title rendered by browsers or search engines.

There's two possible fixes:

- remove `add_theme_support( 'title-tag' );`: not recommended; this is _required_ in WordPress since 2015: https://make.wordpress.org/themes/2015/08/25/title-tag-support-now-required/
- remove the title tags from Largo: easy, fast, recommended: https://kb.yoast.com/kb/the-seo-title-output-for-the-plugin-doesnt-work-as-expected/

Until a fix for this ships in Largo, we can patch child themes by copying Largo's header.php and removing the relevant lines.

**Comment by benlk** [comment]
For sites using Largo, the fix for this is copying Largo's `header.php` into your child theme and removing the `<title> ... </title>` section: https://github.com/INN/umbrella-rivard-report/pull/14/files

**Comment by cartonic** [comment]
Thank you for the help. I'll do that for now.

**Comment by benlk** [comment]
This is also part of the "wp_title" thing mentioned in https://github.com/INN/largo/issues/844 and https://github.com/INN/largo/pull/1245

**Comment by benlk** [comment]
- [x] replace the contents of Largo's title tag with a call to wp_title()
- [x] filter wp_title to output the contents of Largo's title tag

**Comment by benlk** [comment]
Whoops, gotta not-enqueue the meta stuff if Yoast is installed and active.
