### ISSUE TITLE
require_once with or without ()?

### ISSUE THREAD

**Issue by benlk** [INN/largo#1494]
https://github.com/INN/largo/blob/0.5-dev/functions.php#L190-L205

We call `require_once $file` and `require_once( $file )` and there doesn't seem to be agreement in our code on which way is proper. https://secure.php.net/manual/en/function.require-once.php uses () parentheses. 

- [x] research what the WordPress Code Standards policy is on this
- [ ] file a pull request to fix that.

**Comment by aschweigert** [comment]
if you want to do this "correctly" wp actually wants you to use validate_file() before you use require_once(). So like:

$includes = array(
	'/inc/some-stuff.php',
	'/inc/some-other-stuff.php',
	'/inc/more-stuff.php',
);
foreach ( $includes as $include ) {
	if ( 0 === validate_file( get_template_directory() . $include ) ) {
		require_once( get_template_directory() . $include );
	}
}

**Comment by benlk** [comment]
That's pretty cool. I'll add a note here that [WordPress' PHPCS rules](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards) at version `0.14.0` give the following response:

> 22 col 9 warning | "require_once" is a statement not a function; no parentheses are required

**Comment by benlk** [comment]
https://github.com/INN/largo/blob/11f4927db49863fc180df3c8109e1601a2c24e5e/functions.php#L189-L204

**Comment by benlk** [comment]
There are a lot of other `require_once`, `include_once`, `include`, and `require` statements in Largo, all of which need review. Starting this https://github.com/INN/largo/pull/1589.
