### ISSUE TITLE
Review all 'http://' strings in the theme and upgrade to `https://` where possible.

### ISSUE THREAD

**Issue by benlk** [INN/largo#1522]

**Comment by fenriz07** [comment]
Hi, I'm interested in helping you. He developed plugins and themes for wordpress

**Comment by benlk** [comment]
Howdy hey!

If you're interested in this issue, what you'll need to do is:

- [ ] check out the theme
- [ ] search the theme for all places where we have `http://`
- [ ] for each `http://`:
    - [ ] check if that URL now redirects to an identical `https://` URL, and if it does, update the URL
    - [ ] if that URL now redirects to a different `https://` URL, update that URL if the page content is probably the same (I.e., a 301 moved `http://example.com/docs.html` to `https://example.com/docs/`)
    - [ ] if that URL now 404s or redirects to a generic page (`http://example.com/docs/example.html` redirects to `http://example.com`), make a note of that here so that we can talk about it
- [ ] commit your changes and make a pull request

**Comment by fenriz07** [comment]
Well thank you, later I send it to you!

**Comment by fenriz07** [comment]
This url: http://largo.readthedocs.io/users/menus.html#available-menu-areas -> 404

**Comment by fenriz07** [comment]
this is url: http://argoproject.org/ does not respond in https 

lib/navis-madia-credit.php

**Comment by fenriz07** [comment]
this is url http://argosit.es dooes not respond in https or http

lib/navis-media-credit/js/media_credit_editor_plugin.js


http://lesscss.org SSL no valid 
lib/less.inc.php

https://www.checkfront.com/extras/wp-clean-contact -> 404
lib/clean_contact/clean_contact.php

 https://tgmpluginactivation.com/ no working 
lib/class-tgm-plugin-activation

https://jeffsebring.com/responsive-wordpress-images/ no work in https
less/inc/wp-responsive-media.less

http://www.yakirs.net/ no exits
js/select2/select_2_locale_he.js

http://webcloud.se no work in ssl
js/largoPlugin.js

http://feeds.feedburner.com/INNMemberInvestigation 404
inc/widget/largo-inn-rss.php

http://inn.us1.list-manage1.com/subscribe?u=81670c9d1b5fbeba1c29f2865&id=913028b23c 404 
inc/dashboard.php

**Comment by benlk** [comment]
Resolved in https://github.com/INN/largo/pull/1555.
