### ISSUE TITLE
Remove Google Plus buttons

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1546]
Google is shutting down Google Plus. 

> To give people a full opportunity to transition, we will implement this wind-down over a 10-month period, slated for completion by the end of next August. Over the coming months, we will provide consumers with additional information, including ways they can download and migrate their data.
> — https://www.blog.google/technology/safety-security/project-strobe/

**Comment by benlk** [comment]
April 2019. https://www.blog.google/technology/safety-security/expediting-changes-google-plus/

**Comment by joshdarby** [comment]
This is in PR #1667.
