### ISSUE TITLE
Use filemtime for all enqueued assets

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1550]
See https://github.com/INN/umbrella-mtfp/commit/263dde3aca98bdcc75617668b4026294a025184f for an example of how it's done.

This way, asset cachebuster strings are updated when the files themselves update.

**Comment by benlk** [comment]
Moving to 0.6.1 because this is annoying, and because it's a relatively fast fix.

**Comment by benlk** [comment]
This comment is invalid; see changelog at https://github.com/INN/largo/pull/1575

-----

## Modified

## Not modified
- [ ] homepages/homepage-class.php:92:					call_user_func_array('wp_enqueue_script', $asset);
- [ ] homepages/homepage-class.php:94:					call_user_func_array('wp_enqueue_style', $asset);

because the version number is for a rarely-updated script
- [ ] functions.php:469:	wp_enqueue_script( 'navis-columns', $columns_src, array( 'jquery' ), '1.0', true );

because it's a core WordPress script registered elsewhere
- [x] header.php:36:			wp_enqueue_script( 'comment-reply' );

- [ ] inc/ajax-functions.php:26:		wp_enqueue_script(
- [ ] inc/avatars/admin.php:4:	wp_enqueue_script('largo_avatar_js', get_template_directory_uri() . '/inc/avatars/js/avatars.js', array('jquery'));
- [ ] inc/custom-less-variables.php:519:		wp_enqueue_script( 'iris' ); // Colorpicker
- [ ] inc/custom-less-variables.php:520:		wp_enqueue_script( 'largo_custom_less_variable', get_template_directory_uri().'/js/custom-less-variables.js', array( 'jquery', 'iris' ), '20130405', true );
- [ ] inc/custom-less-variables.php:521:		wp_enqueue_style( 'largo_custom_less_variable', get_template_directory_uri().'/css/custom-less-variables.css', '20130405' );
- [ ] inc/customizer/customizer.php:342:		wp_enqueue_script( 'largo-customizer', get_template_directory_uri() . '/inc/customizer/js/customizer.js', array( 'jquery' ) );
- [ ] inc/customizer/customizer.php:343:		wp_enqueue_style( 'largo-customizer', get_template_directory_uri() . '/inc/customizer/css/customizer.css' );
- [ ] inc/enqueue.php:18:		wp_enqueue_style(
- [ ] inc/enqueue.php:27:		wp_enqueue_script(
- [ ] inc/enqueue.php:36:		wp_enqueue_script(
- [ ] inc/enqueue.php:63:		wp_enqueue_script(
- [ ] inc/enqueue.php:69:		wp_enqueue_script(
- [ ] inc/enqueue.php:89:		wp_enqueue_style( 'navis-slick', $slick_css, array(), '1.0' );
- [ ] inc/enqueue.php:92:		wp_enqueue_script( 'jquery-slick', $slides_src, array( 'jquery' ), '3.0', true );
- [ ] inc/enqueue.php:95:		wp_enqueue_style( 'navis-slides', $slides_css, array(), '1.0' );
- [ ] inc/enqueue.php:98:		wp_enqueue_script( 'navis-slideshows', $show_src, array( 'jquery-slick' ), '0.11', true );
- [x] inc/enqueue.php:114:			wp_enqueue_style( 'largo-child-styles', get_stylesheet_directory_uri() . '/style.css', array('largo-stylesheet'));
- [ ] inc/enqueue.php:129:	wp_enqueue_style( 'largo-admin-widgets', get_template_directory_uri().'/css/widgets-php' . $suffix . '.css' );
- [ ] inc/enqueue.php:130:	wp_enqueue_script( 'largo-admin-widgets', get_template_directory_uri() . '/js/widgets-php' . $suffix . '.js', array( 'jquery' ), '1.0', true );
- [ ] inc/enqueue.php:273:		wp_enqueue_style(
- [ ] inc/enqueue.php:297:		wp_enqueue_style(
- [ ] inc/featured-media.php:289:	wp_enqueue_media();
- [ ] inc/featured-media.php:292:	wp_enqueue_script(
- [ ] inc/featured-media.php:314:	wp_enqueue_style(
- [ ] inc/post-metaboxes.php:210:		wp_enqueue_script(
- [ ] inc/post-metaboxes.php:323:		wp_enqueue_script( 'top-terms', get_template_directory_uri() . '/js/top-terms' . $suffix . '.js', array( 'jquery' ) );
- [ ] inc/term-icons.php:135:			wp_enqueue_style( 'fontello', $this->_css_file );
- [ ] inc/term-icons.php:141:			wp_enqueue_style( 'select2', $dir.'/js/select2/select2.css' );
- [ ] inc/term-icons.php:142:			wp_enqueue_script( 'select2', $dir.'/js/select2/select2.min.js', array( 'jquery' ) );
- [ ] inc/term-icons.php:145:				wp_enqueue_script( 'select2-locale-'. implode( '-', $locale ), $dir . '/js/select2/select2_locale_' . implode( '-', $locale ) . '.js' );
- [ ] inc/term-icons.php:147:				wp_enqueue_script( 'select2-locale-'. $locale[0], $dir . '/js/select2/select2_locale_' . $locale[0] . '.js' );
- [ ] inc/term-icons.php:151:			wp_enqueue_script( 'custom-term-icons', $dir.'/js/custom-term-icons' . $suffix . '.js' );
- [ ] inc/term-meta.php:95:	wp_enqueue_media();
- [ ] inc/update.php:985:		wp_enqueue_script(
- [ ] inc/widgets/largo-image-widget.php:39:		wp_enqueue_media();
- [ ] inc/widgets/largo-image-widget.php:40:		wp_enqueue_script( 'largo-image-widget', get_template_directory_uri() . '/js/image-widget.js', array( 'jquery', 'media-upload', 'media-views' ), self::VERSION );
- [ ] inc/widgets/largo-twitter.php:63:		wp_enqueue_script(
- [ ] inc/wp-taxonomy-landing/functions/cftl-admin.php:679:		wp_enqueue_script( 'series', $url.'/inc/wp-taxonomy-landing/series.js', array('jquery', 'jquery-ui-sortable'), '0.0.1', true );
- [ ] inc/wp-taxonomy-landing/functions/cftl-admin.php:680:		wp_enqueue_style( 'series', $url.'/inc/wp-taxonomy-landing/series.css' );
- [ ] lib/class-tgm-plugin-activation.php:559:				wp_enqueue_style( 'plugin-install' );
- [ ] lib/options-framework/options-framework.php:175:	wp_enqueue_style('optionsframework', OPTIONS_FRAMEWORK_DIRECTORY . 'css/optionsframework.css');
- [ ] lib/options-framework/options-framework.php:179:	wp_enqueue_style( 'wp-color-picker' );
- [ ] lib/options-framework/options-framework.php:204:	wp_enqueue_script( 'options-custom', OPTIONS_FRAMEWORK_DIRECTORY . 'js/options-custom.js', array( 'jquery','wp-color-picker' ) );
- [ ] lib/options-framework/options-medialibrary-uploader.php:72:	wp_enqueue_script( 'of-medialibrary-uploader' );
- [ ] lib/options-framework/options-medialibrary-uploader.php:73:	wp_enqueue_script( 'media-upload' );

**Comment by MirandaEcho** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Disclaimers](https://trello.com/c/iySk5jUr/2-disclaimers)
