### ISSUE TITLE
Clean up branch names

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1571]
Continuing from https://github.com/INN/largo/issues/1534:

In the Largo 1.0 family of branches, we have:
- 1.0
- master
- develop

In the Largo 0.x family of branches, we have:
- 0.5
- 0.5-dev

The current stable Largo version is 0.6, in the 0.5 and 0.6-dev branches.

How should branches be named, moving forwards?

**Comment by benlk** [comment]
As a replacement for `0.5-dev` I propose `trunk` as described in https://twitter.com/glyph/status/1143621561653456896: 

> git is intuitive. like for example the main branch is called "master", like you know, when you have a tree growing out of the ground, and you have the one big branch in the ground, in the middle of the tree, that the other branches come from? the "master" of the tree? like that

A replacement name for `0.5` would be hard to find in the tree-trunk metaphor except as something like `seed` or `pollen`, so I propose `release` as a branch name to reflect `0.5`'s current role as the branch that's up-to-date with the latest tagged release.

**Comment by joshdarby** [comment]
@benlk I'm all for `release` as a branch name for the current tagged release branch. Also, `trunk` is a good idea. That's how SVN tags master branches too http://svnbook.red-bean.com/en/1.8/svn.tour.importing.html#svn.tour.importing.layout

**Comment by benlk** [comment]
## To do

- [x] rename `0.5` to `release`
- [x] rename `0.5-dev` to `trunk`
- [x] After changing the branch names, change the default branch in https://github.com/INN/largo/settings/branches
- [x] Update branch names in readme.md in the `trunk` branch

**Comment by joshdarby** [comment]
@benlk The `To do` checklist is completed, but I'll let you delete the `0.5` and `0.5-dev` branches after making sure the new setup looks ok.

**Comment by benlk** [comment]
New setup looks okay; I'll change the branch protection settings (which I had forgotten about 'til now) to the new branches.

**Comment by benlk** [comment]
Added branch protection rules:

- `trunk`: prevent deletion, prevent force pushes
- `release`: prevent deletion, prevent force pushes, only org and repo admins can push (which is everyone at INN)
