### ISSUE TITLE
Floating social buttons obscured by body text

### ISSUE THREAD

**Issue by tylermachado** [INN/Largo#1576]
The popover from the floating social buttons is being obscured by the body text. Looks like a z-index bump on the floating social buttons parent element ought to fix it.

![image](https://user-images.githubusercontent.com/3586466/48640552-00608000-e9a5-11e8-95f3-d208c84e0157.png)

**Comment by benlk** [comment]
In 0.6, the floating social buttons were moved down in the z-index stack so that they'd pass behind fullwidth images in Gutenberg. Could this be fixed by increasing the z-index height for the menu?

**Comment by tylermachado** [comment]
Doesn't look like it -- I think that only moves the menu up within its parent element, even if I attach an extra position:absolute on it. So it seems to be reliant on the z-index of the parent.

**Comment by benlk** [comment]
Copying note from Slack:

So the z-indexes of the relevant items need to be:

- Sticky Nav
- `.alignfull`
- FSB/menu
- paragraph/list/etc text at normal Z-index

**Comment by benlk** [comment]
Adding another bug case in current 0.5-dev: In the single-column template, the sticky nav buttons `div#floating-social-buttons` at `z-index: 0` are actually _beneath_ the transparent `div#main` at `z-index: 1`.  Those two divs are sibling children of  `div#page`.
