### ISSUE TITLE
"Featured in category" removes items from the RSS feed for the category

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1598]
Reported by Frank Mina:

- "Featured in category" removes posts from the category RSS
- RSS feed is sorted by updated date, not by published date

This may be because of the featured category query:

https://github.com/INN/largo/blob/d167efce9c2cb3f4a2a15a0d95705a24bca8470b/inc/featured-content.php#L160-L184

- [x] see if this is fixed by not using that function when processing an RSS feed
- [ ] examine https://github.com/INN/largo/blob/0.5-dev/feed-mailchimp.php and any other feeds to see if there's something affecting the sort order
- [ ] add an option to change the sort order: updated or published

**Comment by joshdarby** [comment]
"Featured in category" posts being removed on category RSS feeds is fixed in PR #1668. 

I haven't been able to replicate RSS feeds sorting by updated date, not by published date. I will create a new issue for it.
