### ISSUE TITLE
Test Largo using Google's Lighthouse

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1652]
https://developers.google.com/web/tools/lighthouse/ can be run from Chrome's dev tools

**Comment by joshdarby** [comment]
@benlk Do you think this would best be done through a local environment or our Largo sandbox?

**Comment by benlk** [comment]
Either should be fine for most of the metrics; the local environment will have misleadingly fast connection speeds.

**Comment by joshdarby** [comment]
Tested http://demo.innsandbox.wpengine.com/

Mobile results:
[demo.innsandbox.wpengine.com-20190820T164953.json.zip](https://github.com/INN/largo/files/3522516/demo.innsandbox.wpengine.com-20190820T164953.json.zip)

Desktop results:
[demo.innsandbox.wpengine.com-20190820T164852.json.zip](https://github.com/INN/largo/files/3522515/demo.innsandbox.wpengine.com-20190820T164852.json.zip)

**Comment by benlk** [comment]
What do those results tell us?

**Comment by joshdarby** [comment]
![Screen Shot 2019-08-21 at 12 21 44 PM](https://user-images.githubusercontent.com/18353636/63449523-4fdd4c00-c40e-11e9-83b4-7be4b569cd42.png)

Main takeaways:

Performance:
> **Eliminate render-blocking resources**
> URL | Size | Potential Savings
> -- | -- | --
> …block-library/style.min.css?ver=5.2.2(demo.innsandbox.wpengine.com) | 5 KB | 350 ms
> …css/style.min.css?ver=0.6.4(demo.innsandbox.wpengine.com) | 18 KB | 800 ms
> …slick/slick.css?ver=155…(demo.innsandbox.wpengine.com) | 1 KB | 350 ms
> …css/slides.css?ver=156…(demo.innsandbox.wpengine.com) | 3 KB | 350 ms
> …css/gutenberg.min.css?ver=156…(demo.innsandbox.wpengine.com) | 1 KB | 350 ms
> …css/legacy-three-column.css?ver=5.2.2(demo.innsandbox.wpengine.com) | 1 KB | 350 ms
> …jquery/jquery.js?ver=1.12.4-wp(demo.innsandbox.wpengine.com) | 34 KB | 800 ms
> …jquery/jquery-migrate.min.js?ver=1.4.1(demo.innsandbox.wpengine.com) | 4 KB | 350 ms
> …js/load-more-posts.min.js?ver=155…(demo.innsandbox.wpengine.com) | 1 KB | 200 ms
> …js/modernizr.custom.js?ver=0.6.4(demo.innsandbox.wpengine.com) | 5 KB | 350 ms
> - Consider lazyloading images

Accessibility:
> **Best practices**
> - [id] attributes on the page are not unique 
> - [user-scalable="no"] is used in the <meta name="viewport"> element or the [maximum-scale] attribute is less than 5. 
> - Names and labelsThese are opportunities to improve the semantics of the controls in your application. This may enhance the experience for users of assistive technology, like a screen reader.
> 
>**Names and labels**
> - Form elements do not have associated labels 
> - Links do not have a discernible name 
> 

Best Practices:
> - Does not use passive listeners to improve scrolling performance; Consider marking your touch and wheel event listeners as `passive` to improve your page's scroll performance
>     - jQuery@1.12.4
> - Includes front-end JavaScript libraries with known security vulnerabilities 2 vulnerabilities detected
>     - jQuery@1.12.4

**Comment by benlk** [comment]
- scroll listeners item will be affected by consolidating the navs: https://github.com/INN/largo/issues/1638
- text labels on twitter links: https://github.com/INN/largo/issues/1791
- text labels on social media buttons: https://github.com/INN/largo/issues/1789
- scaling item: https://github.com/INN/largo/issues/1785
- header image link text: https://github.com/INN/largo/issues/1783
- duplicate social media button IDs: https://github.com/INN/largo/issues/1781
- contrast: https://github.com/INN/largo/issues/1780
- set a performance budget: https://github.com/INN/largo/issues/1779
