### ISSUE TITLE
Provide sane defaults for column sizing in Gutenberg

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1658]
- [ ] make sure columns responsive breakpoints work for Largo's breakpoints

This is because the WP Core blocks stylesheet's breakpoints don't work well for Largo. We should override its rules with our own.

And then we should create an issue for dequeueing the Core blocks stylesheet and replacing it with native Largo styles.

**Comment by joshdarby** [comment]
@benlk This is in PR #1679. 

Before image:
![Screen Shot 2019-04-22 at 3 27 38 PM](https://user-images.githubusercontent.com/18353636/56521104-33d6a600-6513-11e9-83e2-995e4976fcd2.png)

After image:
![Screen Shot 2019-04-22 at 3 27 29 PM](https://user-images.githubusercontent.com/18353636/56521142-3b964a80-6513-11e9-9f66-8322ee229b85.png)
