### ISSUE TITLE
apply font-display:block to fontello

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1686]
https://developers.google.com/web/updates/2016/02/font-display

> **block**
>
> block gives the font face a short block period (3s is recommended in most cases) and an infinite swap period. In other words, the browser draws "invisible" text at first if the font is not loaded, but swaps the font face in as soon as it loads. To do this the browser creates an anonymous font face with metrics similar to the selected font but with all glyphs containing no "ink." This value should only be used if rendering text in a particular typeface is required for the page to be useable.

**Comment by benlk** [comment]
This is a temporary fix for https://github.com/INN/largo/issues/1497

**Comment by joshdarby** [comment]
@benlk Does this just involve adding that `font-display` attribute here?

https://github.com/INN/largo/blob/67b4dedb252220515243756e96ed2033dd7f0d38/less/inc/icons.less#L1-L7

**Comment by benlk** [comment]
Yes.
