### ISSUE TITLE
Revisions to `.wp-block-quote` and `.wp-block-pullquote` styles

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1699]
This will require significant duplication of styles, because the markup for a Quote block

```html
<blockquote class="wp-block-quote">
<p>This is a standard WordPress Quote block</p>
<cite>It has a citation.</cite>
</blockquote>
```
Does not match the markup for a Pull Quote block:

```html
<figure class="wp-block-pullquote">
<blockquote>
<p>This is a <a href="https://wordpress.org/support/article/pullquote-block/">Pullquote</a> block, which is different from a Quote block.</p>
<cite>WordPress</cite>
</blockquote>
</figure>
```

Note how `.wp-block-pullquote` is applied, not to the `blockquote` element, but to the containing `figure` element.

**Comment by benlk** [comment]
Alternately:

Apply the `.type-pull-quote` styles to Pull Quote block. Add the `aside` styles from the Module Wrapper as an alternate-style option to the pull quote block.

See generally https://github.com/WordPress/gutenberg/issues/11610

**Comment by benlk** [comment]
[User comment](https://secure.helpscout.net/conversation/802967329/3453/?folderId=2051037):

> Also, I question why you made this change: "[Matches the default styles for Gutenberg's Pull Quote block with Largo's styles for `<blockquote>`.](https://github.com/INN/largo/pull/1687)" Blockquotes and pull quotes are different stylistic elements, and I'm not sure why anyone would want them to look the same. A pull quote is supposed to add visual flair beyond what a blockquote presents. Or maybe I'm at odds with what most other sites do on this.


This would be in favor of the alternate approach described above.

**Comment by benlk** [comment]
- [x] remove pull quote styles from block quote, leaving only block quote styles.
- [x] apply pull quote styles to pull quote block.

**Comment by joshdarby** [comment]
@benlk I went ahead and removed the normal block quote styles from the pull quote and added the `type-pull-quote` styles to it. Anything else we're looking for in this specific issue?

![Screen Shot 2019-07-11 at 3 12 28 PM](https://user-images.githubusercontent.com/18353636/61078336-65faf400-a3ee-11e9-9842-5a3566fe0f93.png)

**Comment by benlk** [comment]
Does it look okay in alignment left/right/center/none conditions?

**Comment by joshdarby** [comment]
@benlk I think so. Here's how it looks.

Left:
![Screen Shot 2019-07-12 at 4 29 23 PM](https://user-images.githubusercontent.com/18353636/61156880-8eecb900-a4c2-11e9-83cd-d3eb54b62c50.png)

Right:
![Screen Shot 2019-07-12 at 4 28 05 PM](https://user-images.githubusercontent.com/18353636/61156881-8eecb900-a4c2-11e9-88df-400d7c11f7ae.png)

Full-width:
![Screen Shot 2019-07-12 at 4 30 32 PM](https://user-images.githubusercontent.com/18353636/61156878-8eecb900-a4c2-11e9-8f76-166fd44f4091.png)

Wide:
![Screen Shot 2019-07-12 at 4 30 08 PM](https://user-images.githubusercontent.com/18353636/61156879-8eecb900-a4c2-11e9-8694-1739863d72af.png)

Normal:
![Screen Shot 2019-07-12 at 4 31 45 PM](https://user-images.githubusercontent.com/18353636/61156877-8eecb900-a4c2-11e9-87c9-72b9e0aa7e6d.png)

**Comment by benlk** [comment]
👍
