### ISSUE TITLE
Add box-sizing: border-box to navis slideshow caption CSS

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1702]
https://github.com/INN/largo/blob/e2ac830239452658c285860b330d521c6a0f300e/lib/navis-slideshows/css/slides.css#L306-L317

Add this:
```css
    box-sizing: border-box;
```

This will change the caption of an image from this first image to the second image:

![Screen Shot 2019-04-29 at 18 13 50 ](https://user-images.githubusercontent.com/1754187/56930438-ab27af00-6aaa-11e9-93bb-d00211940bba.png)

![Screen Shot 2019-04-29 at 18 13 39 ](https://user-images.githubusercontent.com/1754187/56930437-ab27af00-6aaa-11e9-86ce-a12ddf0f5a51.png)

**Comment by joshdarby** [comment]
@benlk Should this also be added to `.wp-block-gallery .blocks-gallery-image figcaption, .wp-block-gallery .blocks-gallery-item figcaption`?

**Comment by benlk** [comment]
Yes. Anywhere there's a `figcaption` or `.wp-caption-text`, basically.

**Comment by joshdarby** [comment]
This is awaiting review in #1711.

**Comment by benlk** [comment]
Let's create an issue for better automated frontend testing in the future, but continue testing this with our existing testing stuff.

**Comment by joshdarby** [comment]
@benlk I created a sample post [here](http://largodev.innsandbox.wpengine.com/2019/07/17/box-sizing-examples/) with a classic block image, classic block gallery, image block, and gallery block.

What else do you think we should test for this?
