### ISSUE TITLE
Move floating social media buttons so they don't overlap align-wide content

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1718]
<img width="1077" alt="Screen Shot 2019-06-07 at 14 32 54 " src="https://user-images.githubusercontent.com/1754187/59125728-352c2880-8931-11e9-868e-81a01d8f310b.png">

In this image, the floating social media buttons are overlapping the align-wide content in the page. The FSB will always conflict with align-full content, but let's keep the FSB from conflicting with align-wide.

This will involve changing the positioning in styles or in JS.

**Comment by benlk** [comment]
This issue's solution may only be a short-term fix; ideally we'd fix the Z-index conflict between the FSB and the page so that the FSB could go underneath content rather than atop it, while remaining clickable. See https://github.com/INN/largo/issues/1576 for more of the history of this issue.

**Comment by MirandaEcho** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Changing post CSS so that we can have the floating social buttons float under wide/full images](https://trello.com/c/4mfVbd6p/6-changing-post-css-so-that-we-can-have-the-floating-social-buttons-float-under-wide-full-images)

**Comment by rlambertsen** [comment]
the new team thinks that when an image is full width the social buttons act normally. Being able to share quickly is the key over small ingress over an image.
