### ISSUE TITLE
Undefined variable: post in homepages/templates/top-stories.php on line 73

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1723]
With the "Top Stories" layout active, `$post` is undefined in several places on the homepage.

![Screen Shot 2019-06-10 at 17 17 51 ](https://user-images.githubusercontent.com/1754187/59227609-bf7bc300-8ba3-11e9-90ef-4c40376baf6b.png)

**Comment by joshdarby** [comment]
@benlk Do you think we should we just change `$post` to `the_ID()` in this context, or actually make a `$post` variable?

`largo_excerpt( $post, 3 );`

**Comment by benlk** [comment]
If possible, we should pass the WP_Post object to largo_excerpt rather than the post ID: 

https://github.com/INN/largo/blob/37e7b9dbf3e40072fb15b9ebf25e81f73d20daef/inc/post-tags.php#L184-L198

**Comment by joshdarby** [comment]
@benlk So couldn't we just pass `the_post` instead of `$post`?

**Comment by joshdarby** [comment]
@benlk So couldn't we just pass `get_post` instead of `$post`?

**Comment by benlk** [comment]
Yeah, that looks like it would work.
