### ISSUE TITLE
Patch Largo to fix Gutenberg stylesheet misaligning paragraphs and left/right images

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1731]
If there isn't a fix for https://github.com/WordPress/gutenberg/issues/16241 in WordPress Core or the Gutenberg plugin by the time that Largo 0.6.4 is ready, take the following actions:

- [ ] copy the changes from https://github.com/woocommerce/storefront/pull/1165 into largo's LESS in a file named `gutenberg-shim-16241.less`
- [ ] create a ticket to remove that shim in the next Largo release if Gutenberg has fixed the bug

This was reported by an INN member in https://secure.helpscout.net/conversation/884401410/3812/

This is Clickup task ID #166f8b

**Comment by joshdarby** [comment]
@benlk After todays discussion about the implementation of this, do we still want to create a new `.less` file and a ticket to remove it later on?

**Comment by benlk** [comment]
Yes.

**Comment by joshdarby** [comment]
@benlk Could you help me reproduce this? I followed your instructions from https://github.com/WordPress/gutenberg/issues/16241 on my local Current.org env

**To reproduce**
Steps to reproduce the behavior:

1. With WordPress 5.2.2.1 and no Gutenberg plugin
2. Add an image block aligned right that is less than the full column width.
3. Following the image block, add a paragraph text block.
4. See error

but I'm not seeing the issue? What am I missing?

![Screen Shot 2019-07-11 at 9 46 12 AM](https://user-images.githubusercontent.com/18353636/61056194-e276de00-a3c0-11e9-9e22-39814f8ac6c4.png)

![Screen Shot 2019-07-11 at 9 45 57 AM](https://user-images.githubusercontent.com/18353636/61056196-e276de00-a3c0-11e9-8ce4-334c78817dbd.png)

![Screen Shot 2019-07-11 at 9 48 38 AM](https://user-images.githubusercontent.com/18353636/61056331-2538b600-a3c1-11e9-93f0-6ba21c0ac8b3.png)

**Comment by benlk** [comment]
I think it's only visible if the image block is the first block in the post. 

With a paragraph block before the image block, in Firefox:

<img width="725" alt="Screen Shot 2019-07-14 at 21 51 42 " src="https://user-images.githubusercontent.com/1754187/61192342-96a68c00-a681-11e9-9e4f-08561a977552.png">

Without a paragraph before the image block, in Firefox

<img width="734" alt="Screen Shot 2019-07-14 at 21 52 16 " src="https://user-images.githubusercontent.com/1754187/61192352-ac1bb600-a681-11e9-9239-636cdd095d8d.png">

With a paragraph block before the image block, in Chrome:

<img width="708" alt="Screen Shot 2019-07-14 at 21 55 14 " src="https://user-images.githubusercontent.com/1754187/61192414-22b8b380-a682-11e9-8f7d-5f1e20aa5a75.png">


Without a paragraph before the image block, in Chrome:

<img width="709" alt="Screen Shot 2019-07-14 at 21 55 23 " src="https://user-images.githubusercontent.com/1754187/61192416-26e4d100-a682-11e9-837f-1d3d95522a55.png">

I don't understand why that would be the case; there doesn't appear to be any difference in styles between the image block first in the post and the image block later in the post.
