### ISSUE TITLE
Largo Facebook Widget lacks a title field, but the form has a "Title URL" field in the settings page.

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1739]
Following up on https://github.com/INN/largo/pull/1736 for https://github.com/INN/largo/issues/1717, the decision was made to check all Largo widgets to see if they output the widget title safely.

No widget title is output in the widget, and the widget has no field to save the widget title.

https://github.com/INN/largo/blob/aa45901f61d1b8840512e603780b29853f3bbf80/inc/widgets/largo-facebook.php#L22-L38

But the widget does display Largo's "Widget Title Link" field:
![Screen Shot 2019-07-09 at 16 38 15 ](https://user-images.githubusercontent.com/1754187/60921214-f8bd5680-a267-11e9-9918-a5a3a718a462.png)

**Comment by benlk** [comment]
Should this widget have a title field? If so, add one.

**Comment by joshdarby** [comment]
@benlk Should we wrap the Twitter widget into this issue also? The same thing is happening with it.

**Comment by benlk** [comment]
I'd create a separate issue for it, but there's no reason they couldn't be addressed in the same PR.
