### ISSUE TITLE
add other input types to metabox API

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#175]
Had to add a function to the WCIJ child theme for checkboxes (http://bit.ly/1h4hnKA), should probably fold this back into the parent theme at some point.

**Comment by willhaynes** [comment]
@aschweigert is this still an issue? Or was this already pulled in?

**Comment by aschweigert** [comment]
I don't believe so. I think I was thinking about re-organizing/improving some other pieces of the metabox API and that's why I hadn't just copied and pasted this over. For now it might be ok to just make a quick pass through that stuff and jus refactor anything that pops out but otherwise just drop this in and leave any further improvement until the next iteration

**Comment by willhaynes** [comment]
I believe this is no longer applicable, as this metabox has been removed & folded into the new featured media framework.

**Comment by aschweigert** [comment]
Eh, I still think it's applicable, just not for this particular application. We can always look at adding it later when we need it.
