### ISSUE TITLE
PHP Warning:  preg_match_all(): Compilation failed: invalid range in character class at offset 44 in wp-content/themes/largo/inc/custom-less-variables.php on line 776

### ISSUE THREAD

**Issue by earthboundkid** [INN/Largo#1774]
https://github.com/INN/largo/blob/c41d8519370b48a6e53ce36b3b516d3e54e39d66/inc/custom-less-variables.php#L773

This regex is invalid. The dash needs to be escaped because it looks like a range selector.

**Comment by joshdarby** [comment]
@carlmjohnson Thanks for pointing this out. We have a PR opened here #1772 to fix the regex issues in that file.

I've marked this as a duplicate of #1771.

**Comment by earthboundkid** [comment]
Thanks
