### ISSUE TITLE
Largo Top Term title attribute always returned as "Read more posts in x category"

### ISSUE THREAD

**Issue by joshdarby** [INN/Largo#1776]
In the `largo_top_term` function, the `<a>` element title attribute is always returned as `Read x in the y **category**` even though you can set the top term to be a tag or a series. 

We should probably rework that line to pull in the correct taxonomy type instead of using a hardcoded `category` string.

https://github.com/INN/largo/blob/f50df16e9e06fb9402802e2f1ce76ce058d26d76/inc/related-content.php#L327-L443

**Comment by benlk** [comment]
If we're drawing the taxonomy name from the taxonomy object, we should make sure that all taxonomies have the full set of labels: https://github.com/INN/largo/issues/1346

**Comment by benlk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [fix largo_top_term title attribute output so that correct taxonomy label is used](https://trello.com/c/2MRBef8l/31-fix-largotopterm-title-attribute-output-so-that-correct-taxonomy-label-is-used)
