### ISSUE TITLE
id #header-social is duplicated on page when sticky nav and global nav are present

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1781]
We can't have duplicate elements on a page.

- [ ] move the ID in the HTML to a class
- [ ] change CSS to match

This issue was identified during research on https://github.com/INN/largo/issues/1653 using the AXE browser plugin.

**Comment by MirandaEcho** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [id #header-social is duplicated on page when sticky nav and global nav are present](https://trello.com/c/nqBb1Hn3/16-id-header-social-is-duplicated-on-page-when-sticky-nav-and-global-nav-are-present)

**Comment by benlk** [comment]
After reviewing a mess of Largo and non-Largo sites, we determined that:
- let's keep these buttons in the combined main/sticky nav
- let's keep these buttons in the global nav

**Comment by benlk** [comment]
Resolved in #1826 by converting the ID to a class.
