### ISSUE TITLE
partials/widget-content.php does not check if post has thumbnail before outputting link wrapping the thumbnail.

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1784]
https://github.com/INN/largo/blob/c41d8519370b48a6e53ce36b3b516d3e54e39d66/partials/widget-content.php#L8-L30

If a post has no thumbnail, an empty link tag is output:

```html
<li>
	<a href="https://largo.test/2019/07/11/adding-images-testing-post/"></a>
	<h5>
		<a href="https://largo.test/2019/07/11/adding-images-testing-post/">Adding images testing post</a>
	</h5>
	<p>The following image was inserted in Largo 0.6.3: Ben Keith / TwitterThe shadow shows the boundaries of Louisiana if intertidal lands and wetlands are not counted towards the state's territory. State correctional facilities are marked. </p>
</li>

```
- [ ] check that thumbnail exists before attempting to output a thumbnail.

----

This issue was identified during research on https://github.com/INN/largo/issues/1653 using the AXE browser plugin.

**Comment by omnisite** [comment]
@benlk See PR
