### ISSUE TITLE
Add discernible text label to author twitter links

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1791]
https://github.com/INN/largo/blob/512da701664b329f2f92244bbe54880a6e146431/inc/byline_class.php#L157

This link needs something like a `title="follow $person on Twitter"` or `aria-label="follow $person on Twitter"` element.

And this bit too:

https://github.com/INN/largo/blob/512da701664b329f2f92244bbe54880a6e146431/partials/author-bio-social-links.php#L30-L34

This issue was identified during research on https://github.com/INN/largo/issues/1653 using the AXE browser plugin.

**Comment by MirandaEcho** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add discernible text label to author twitter links](https://trello.com/c/dJsQ6UVo/12-add-discernible-text-label-to-author-twitter-links)
