### ISSUE TITLE
Check Largo for date/time problems solved in WP 5.3

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1804]
https://make.wordpress.org/core/2019/09/23/date-time-improvements-wp-5-3/

- [ ] search in Largo for functions updated/changed in 5.3

**Comment by MirandaEcho** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Date/Time updates from 5.3](https://trello.com/c/z5tAvOEg/73-date-time-updates-from-53)

**Comment by omnisite** [comment]
@benlk Can you review the PR?
