### ISSUE TITLE
5.3 introduces `aria-current="page"` attribute for current page; where does Largo need to add this?

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1805]
https://make.wordpress.org/core/2019/09/23/core-widgets-new-aria-current-attribute-in-wordpress-5-3/

**Comment by MirandaEcho** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [WP 5.3 - aria-current="page" attribute](https://trello.com/c/q4J1auC5/74-wp-53-aria-currentpage-attribute)
