### ISSUE TITLE
Header image defaults

### ISSUE THREAD

**Issue by danielbachhuber** [INN/Largo#181]
Because using a header image isn't required, the default behavior should be to use the title and description:

![image](https://cloud.githubusercontent.com/assets/36432/2674237/c266aba0-c0fd-11e3-8e22-6ca3b216e742.png)

When the title and description are selected, the header image fields shouldn't appear. Unchecking title / description would then show the header image field.

**Comment by aschweigert** [comment]
We also need to make sure it's clear where header images are/are not used in > 0.4 because we've been getting a lot of questions about why we don't show them on internal pages/mobile. We might also consider re-adding that as an option for backwards compatibility.

**Comment by benlk** [comment]
- [ ] default is text header unless images are uploaded
- [ ] link to the docs from #430 at largo.readthedocs.org
- [ ] ?
