### ISSUE TITLE
LESS/CSS Customizer regex problem

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1813]
Something to look out for as we remove the CSS thing in Largo for #1137:

> PHP Warning:  preg_match_all(): Compilation failed: invalid range in character class at offset 17 in /wp-content/themes/Largo/inc/custom-less-variables.php on line 292
> PHP Warning:  Invalid argument supplied for foreach() in /wp-content/themes/Largo/inc/custom-less-variables.php on line 294

Seen in Citylimits on WP 5.2.3 with Largo 0.6.4.

https://github.com/INN/largo/blob/c41d8519370b48a6e53ce36b3b516d3e54e39d66/inc/custom-less-variables.php#L292-L294

I *think* this is because `[\w-_]` should be written as `[\w_-]` to avoid trying to create a range from `\w` to `_`.

**Comment by joshdarby** [comment]
@benlk Didn't we already do this in #1772 ?

**Comment by benlk** [comment]
So we did!
