### ISSUE TITLE
set `box-sizing: border-box` on the max-width styles for narrow-viewport block alignment

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1836]
https://github.com/INN/largo/blob/512da701664b329f2f92244bbe54880a6e146431/less/inc/responsive-767px-max.less#L138-L162

Add `box-sizing: border-box` here.

Without this style:

<img width="678" alt="Screen Shot 2019-11-27 at 18 52 16" src="https://user-images.githubusercontent.com/1754187/69766680-13c13200-1147-11ea-9788-32b3424e0a15.png">

With this style:

<img width="649" alt="Screen Shot 2019-11-27 at 18 52 47" src="https://user-images.githubusercontent.com/1754187/69766693-276c9880-1147-11ea-963b-d89f762da5e2.png">

**Comment by rlambertsen** [comment]
We added a video and some content to test this issue. We found no problems with the parent theme styles of the theme, we think the issue is with the current child theme styles in use here in the images. Specifically the red border around the area.
