### ISSUE TITLE
Don't output a hero image on term archives if the found term meta post ID is null

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1838]
https://github.com/INN/largo/blob/f50df16e9e06fb9402802e2f1ce76ce058d26d76/archive.php#L78-L79

Should be something like 

```php
$post_id = largo_get_term_meta_post( $queried_object->taxonomy, $queried_object->term_id ); 
if ( ! empty( $post_id ) ) {
    largo_hero( $post );
}
```

Reported in https://github.com/INN/umbrella-citylimits/pull/135#issuecomment-566265176

**Comment by joshdarby** [comment]
This was fixed in https://github.com/WPBuddy/largo/commit/798d0c5c5283c12f787d9c37f7dd21bbf27599b1.
