### ISSUE TITLE
Largo_Related::popularity_sort sorts in wrong order

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1868]
## The problem

Copying from https://github.com/INN/umbrella-sfpublicpress/issues/111

> A quick review of the terms assigned to this post:
> 
> - tag "police brutality" has one post, which is the initial post
> - tag "police reform" has one post, which is the initial post
> - tag "protests" has three posts, which the initial post and two of the three related posts
> - tag "protest" has 8 posts, of which 4254 is the post in that tag previous to this post
> - category "Social Justice" has 124 posts
> 
> When `Largo_Related` is generating posts from the categories and tags that are assigned to the initial post, it grabs all category and tag terms that apply to the current post, and then sorts them by popularity before looping through them to find posts to add to the "related" list.
> 
> https://github.com/INN/largo/blob/590181982d22a5444eb3c5ccca58ea8b56db12f7/inc/related-content.php#L694-L696
> 
> The function `popularity_sort` is a method of `Largo_Related`, and if its behavior here is to be believed, it's sorting the less-used terms before the more-used terms.
> 
> https://github.com/INN/largo/blob/590181982d22a5444eb3c5ccca58ea8b56db12f7/inc/related-content.php#L550-L560
> 
> As a result, no posts are grabbed from "police brutality" or "police reform", the two posts from "protests" are added, then with one more post to grab Largo_Related grabs the next-earlier post from "protest", and then because it has three posts to equal the requested count of three, it's done. It never reads the category.
> 
> But as far as I can tell, based on [usort](https://www.php.net/manual/en/function.usort.php) and [ternary operator](https://www.php.net/manual/en/language.operators.comparison.php#language.operators.comparison.ternary) docs, this code is written to perform the opposite way of how it's behaving.
> 
> ```php
> 		return ( $a->count < $b->count ) ? -1 : 1;
> ```

> So this is what's actually happening:
> 
> Given tags and counts
> 
> - c -> 4
> - a -> 3
> - f -> 2
> - e -> 1
> 
> This usort sorting function will return `e,f,a,c` instead of `c,a,f,e`, because it orders _from least to greatest_.
> 
> So _of course_ it's picking from the lower-count terms.

----

## Solution

- [ ] swap `-1` and `1` here:

https://github.com/INN/largo/blob/590181982d22a5444eb3c5ccca58ea8b56db12f7/inc/related-content.php#L559

**Comment by benlk** [comment]
This bug dates back to November 7, 2013! https://github.com/INN/largo/blame/252d35c9261dda3d659e38182e99fe2d407879b2/inc/related-content.php#L501-L511

**Comment by aschweigert** [comment]
sorry!

**Comment by benlk** [comment]
That one isn't your fault! (I think)
