### ISSUE TITLE
Theme Options > Theme Images: 'upload' buttons not responding

### ISSUE THREAD

**Issue by patrickbrendel** [INN/Largo#1874]
Using Wordpress 5.5.
Largo 0.6.4
Same issue on Windows Chrome, Windows Edge, Ubuntu Firefox

The upload buttons on Theme Options > Theme Images are not responding. I click them and the dialogue does not open to upload a file.

This was working as of ~2 weeks ago.

![largo-upload-not-responding](https://user-images.githubusercontent.com/51090453/90337718-f0c30080-dfa9-11ea-8fce-132c0516a829.png)

**Comment by benlk** [comment]
Do you see a Javascript error the console of any of those browsers?

Do the buttons work if you install the https://wordpress.org/plugins/enable-jquery-migrate-helper/ plugin?

**Comment by patrickbrendel** [comment]
Yes downloading the plugin seems to have solved the issue.

FYI here's the javascript error from before activating the plugin:

of-medialibrary-uploader.js?ver=0.6.4:21 Uncaught TypeError: $(...).live is
not a function
    at Object.removeFile (of-medialibrary-uploader.js?ver=0.6.4:21)
    at HTMLDocument.<anonymous> (of-medialibrary-uploader.js?ver=0.6.4:157)
    at i
(load-scripts.php?c=0&load[chunk_0]=jquery,jquery-ui-core,utils&ver=5.5:2)
    at Object.fireWith [as resolveWith]
(load-scripts.php?c=0&load[chunk_0]=jquery,jquery-ui-core,utils&ver=5.5:2)
    at Function.ready
(load-scripts.php?c=0&load[chunk_0]=jquery,jquery-ui-core,utils&ver=5.5:2)
    at HTMLDocument.J
(load-scripts.php?c=0&load[chunk_0]=jquery,jquery-ui-core,utils&ver=5.5:2)

----

Thanks for your help!

**Comment by benlk** [comment]
@kaylima FYI that this may solve the problems of many sites updating to WP 5.5.

**Comment by rlambertsen** [comment]
this file is using a deprecated jQuery function .live():
lib/options-framework/js/of-medialibrary-uploader.js
at lines 21 & 72.
jQuery removed this in version 1.9 as noted in their docs: 
https://api.jquery.com/live/

**Comment by rlambertsen** [comment]
This issue is fixed per this PR https://github.com/WPBuddy/largo/commit/8fc15d93d840fe276bdeb4f87aa9aed2ee4fcc32
