### ISSUE TITLE
CSS Variables, no interface showing up

### ISSUE THREAD

**Issue by patrickbrendel** [INN/Largo#1875]
Using Wordpress 5.5.
Largo 0.6.4
Same issue on Windows Chrome, Windows Edge, Ubuntu Firefox

I have enabled "Custom LESS to CSS For Theme Customization". But in the 'CSS Variables' option, nothing shows up to allow me to choose theme colors, etc.

![largo-no-less](https://user-images.githubusercontent.com/51090453/90337800-7ba3fb00-dfaa-11ea-9bd4-4cd402d8969c.png)

**Comment by benlk** [comment]
Hi Patrick,

This is a known bug in Largo version 0.6.4 and prior under PHP 7.3. If you're willing to run a prerelease version of Largo, we merged a fix in https://github.com/INN/largo/pull/1772. You can use tagged release `v0.7-prerelease1` to get that fix.

https://github.com/INN/largo/releases/tag/v0.7-prerelease1

https://github.com/INN/largo/compare/v0.6.4...v0.7-prerelease1

**Comment by patrickbrendel** [comment]
Thanks Ben. I’ll try the prerelease version.

Patrick

**Comment by patrickbrendel** [comment]
Hi, thanks very much. This seems to have addressed the issue.

Kind regards

-patrick
