### ISSUE TITLE
update prominence term descriptions 

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#210]
when terms are inserted in /inc/taxonomies.php the term descriptions should reflect the new homepage layout options

**Comment by benlk** [comment]
HomepageSingle's top story prominence term is added by the HomepageSingle class. Same for HomepageSingleWithFeatured and HomepageSingleWithSeriesStories. I've changed their text from 

> If you are using the Newspaper or Carousel optional homepage layout, add this label to a post to make it the top story on the homepage

to  

> If you are using a "Big story" homepage layout, add this label to a post to make it the top story on the homepage"

The terms in `inc/taxonomies.php`:

- sidebar-featured changed to reflect that the Sidebar Featured Posts widget is deprecated
- footer-featured changed to reflect that the Footer Featured Posts widget is deprecated
- category-featured doesn't affect homepages
- homepage-featured is still applicable
- series-featured still seems applicable. "Select this option to allow this post to float to the top of any/all series landing pages sorting by Featured first."

**Comment by rnagle** [comment]
I see the updated descriptions in the code, but when I look at the prominence taxonomy page in the dashboard, they're still the old ones.

Any idea what's going on here?

![screen shot 2015-01-13 at 7 07 29 am](https://cloud.githubusercontent.com/assets/72608/5721114/1f694a0e-9af3-11e4-95e4-05039f14cf9b.png)

**Comment by benlk** [comment]
Thinking out loud:

Yes, it's caching, after a fashion. However, clean_term_cache doesn't fix this.

`inc/taxonomies.php` lines [81-103](https://github.com/INN/Largo/blob/develop/inc/taxonomies.php#L81-L103):

	$changed = false;
	$terms = get_terms('prominence', array(
		'hide_empty' => false,
		'fields' => 'all'
	));
	$names = array_map(function($arg) { return $arg->name; }, $terms);
	$term_ids = array();
	foreach ($largoProminenceTerms as $term ) {
		if (!in_array($term['name'], $names)) {
			wp_insert_term(
				$term['name'], 'prominence',
				array(
					'description' => $term['description'],
					'slug' => $term['slug']
				)
			);
			$changed = true;
		}
	}
	if ($changed)
		delete_option('prominence_children');

Our code only updates if the term *names* have changed. If the descriptions don't, then no updates.

I've found a way to update this using wp_update_term, but the downside is that user-customized taxonomy descriptions will _always_ be overwritten, which isn't desirable in day-to-day work. It may be desirable when WP_DEBUG. It would be useful as part of the update process. 

	$term_ids = array();
	foreach ($largoProminenceTerms as $term ) {
		if (!in_array($term['name'], $names)) {
			wp_insert_term(
				$term['name'], 'prominence',
				array(
					'description' => $term['description'],
					'slug' => $term['slug']
				)
			);
			$changed = true;
		} else if ( WP_DEBUG ) {
			// This section forces the term descriptions to update.
			// However, it overwrites custom user-set term descriptions.
			// therefore, WP_DEBUG
			$id = get_term_by('slug', $term['slug'], 'prominence', 'ARRAY_A' );
			wp_update_term(
				$id['term_id'], 'prominence',
				array(
					'name' => $term['name'],
					'description' => $term['description'],
					'slug' => $term['slug']
				)
			);
		}
	}

	if ($changed)
		delete_option('prominence_children');

Is there a way to tell a user-defined value from the not-user-defined value, other than by comparing it to the previous value? 

Ideally:

	if prominence term doesn't exist in list of existing terms
		add the term to the terms
	else if term has old description (but not a user-set one)
		update the tax term with the new description

Comparing the current description to the old description to determine if they are the same (and therefore the new description should be set) requires knowledge of the old description, which we could manually enter in inc/update.php

**Comment by benlk** [comment]
Done in the update-tests branch, at e9114a2857dc3afa5d00ec6ad829b2ae8180c53f. This will run with the updates.
