### ISSUE TITLE
New version of picturefill.js.wp exists

### ISSUE THREAD

**Issue by benlk** [INN/Largo#249]
The version [included in Largo is 1.1.3](https://github.com/INN/Largo/tree/develop/inc/picturefill); the [current stable is 1.3.2](https://github.com/kylereicks/picturefill.js.wp/blob/master/readme.txt).

**Comment by benlk** [comment]
There are two ways to update the Picturefill.js.w in Largo:

- replacing the old files with the new files
- replacing the old files with a git submodule for the [1.x branch of picturefill.js.wp](https://github.com/kylereicks/picturefill.js.wp/tree/1.3.x)

Using a submodule would make it easier for us to keep up to date with changes upstream, but installation of largo from `git clone` would require a post-clone `git submodule init` and `git submodule update`, or  using `git clone --recursive` instead, which could be annoying for anyone using our code.

@rnagle @aschweigert What do you think is the better option?

**Comment by aschweigert** [comment]
I would lean more towards the submodule approach I think but right now picturefill isn't even being used I don't think because it was causing too many problems. So, before we update, we should make sure that that's the approach we want to use for responsive images, and if so, then we can update it and make sure our implementation is working as it needs to.

**Comment by benlk** [comment]
What sort of problems was it causing?

**Comment by aschweigert** [comment]
Mostly issues dealing with different possible handlings of image/caption shortcodes. If you were starting off with a new site from scratch it seems like it was mostly fine but with migrations we were running into some weird problems so we deactivated it until we could thoroughly test it and make sure it was really 100%

**Comment by benlk** [comment]
Submodules will make our lives significantly more annoying in the short term. Check out the `picturefill1.3-submodule` branch of Largo. It may give you warnings that you'll have to override with `git checkout -f picturefill1.3-submodule`. Now try to `git checkout develop`: you'll have to `-f` again. When you next checkout the `picturefill1.3-submodule` branch, the files in the `inc/picturefill` directory are messed up and need to be reset by going into the submodule directory to run `git checkout -f origin/1.3.x`.

Of course, this ceases to be a problem once all the branches that people are using are updated with commits from the submodule branch, but until then it will be quite annoying. 

It's possibly better to just update the files, as in the `picturefill1.3-files` branch

**Comment by benlk** [comment]
One way to get around the file conflicts with submodules is to throw the submodule in a differently-named directory. Instead of `inc/picturefill`, perhaps `inc/picturefillwp`.

**Comment by drywall** [comment]
I haven’t been following this thread closely so I’m not sure what the submodule issues are, but have you considered something like subtree as an alternative approach? http://blogs.atlassian.com/2013/05/alternatives-to-git-submodule-git-subtree/

**Comment by benlk** [comment]
Subtree actually looks pretty easy. Check out the picturefill1.3-subtree branch.

**Comment by benlk** [comment]
There's also the [`picturefill-update`](https://github.com/INN/Largo/commits/picturefill-update) branch, from Cornershop.

**Comment by aschweigert** [comment]
another update https://github.com/scottjehl/picturefill/releases/tag/2.3.0

**Comment by benlk** [comment]
Yet another update: https://css-tricks.com/please-update-picturefill/

**Comment by benlk** [comment]
We removed Picturefill in https://github.com/INN/largo/pull/1049 on Jan 7, 2016, but there's still some code from it floating around.
