### ISSUE TITLE
optional taxonomies should be...optional

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#282]
Thinking particularly about the "series" and "post type" taxonomies, some sites will never use these so we should probably make them opt-in rather than opt-out to clean up the number of metaboxes that appear on the post edit screen

**Comment by aschweigert** [comment]
just updated the new INN sites with this and looks good except the optional taxonomies still show up in the quick/bulk edit view for posts, not sure what's up with that or how to remove it...seems like it shouldn't be there because the taxonomies aren't registered, right?

**Comment by benlk** [comment]
The UI elements used to be removed by hiding them; in #338 they're now removed by just setting the taxonomy to a blank.

**Comment by benlk** [comment]
#338 has been merged.
