### ISSUE TITLE
Test all widgets in the article bottom widget area

### ISSUE THREAD

**Issue by rnagle** [INN/Largo#289]
Want to make sure all widgets behave as expected and look good.

**Comment by willhaynes** [comment]
Systematically worked through different widget and layout combinations, as well as options that seemed likely to break. All good on all fronts, so I'll close this ticket.

I do believe some design considerations could be taken for v0.5, to @kaeti's discretion.

**Comment by kaeti** [comment]
Largo v0.5: Kaeti's revenge
