### ISSUE TITLE
less to css customizer in 0.4

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#291]
particularly for sites using this now, we need to fire the customizer to burn a new stylesheet with the variables they've set, otherwise we wind up loading the new templates with the old stylesheet and some things are broken.

There's also likely some testing we need to do to make sure variables are used correctly in any new LESS written for 0.4 AND to make sure it works with the new homepages rig.

**Comment by rnagle** [comment]
Added this as a part of the update process. See 07adba7ca51aa2e7e82a8cdfae9ffe511c0738ff and b844605a34e5ce8b31e4e06265a8571dcb6bb1c8.

Custom variables appear to work fine with the new homepages rig, too.
