### ISSUE TITLE
big story with series homepage layout breaks sometimes

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#293]
In 0.4, if the "big story with other stories in the series" homepage layout is selected, and:

1) the featured stories is not in a series
or
2) the featured story is the only story in a series

The featured story seems to display correctly (similar to the single top story layout) but you can't click on the image or the headline to go to the story page. No idea why, the markup looks correct but I'm guessing there is a z-index issue or something that makes it impossible to click on anything.

**Comment by willhaynes** [comment]
I was under the assumption that wcij was running 0.4. I still don't seem to be able to replicate this, even with their child theme.

It there any way we could replicate this on staging? Perhaps there's another settings that's getting in the way.

**Comment by aschweigert** [comment]
Yeah, we can probably clone their site over to staging and tinker some there later today

**Comment by aschweigert** [comment]
I should add, also, that we need to update them to the latest develop branch of largo because they're pretty far behind us at this point. We should, at that time, also be able to strip some things out of their child theme that have since made it back into the parent.

**Comment by rnagle** [comment]
I was unable to recreate this issue either on my copy of the site or the staging site with a bunch of different browsers. Going to close this issue.

Regarding @aschweigert's comment, I opened a new issue in JIRA for @willhaynes to update Largo for Wisconsin.
