### ISSUE TITLE
Layout screen option is confusing

### ISSUE THREAD

**Issue by willhaynes** [INN/largo#297]
The way the layout post option widget design is potentially confusing. It's not clear that selecting from the dropdown is overriding a default layout. A simple fix to clarify would be to use radio buttons to differentiate the default value from the override selection.

![image](https://cloud.githubusercontent.com/assets/3745345/5249841/48d9350c-794c-11e4-9895-56687fe08646.png)

**Comment by rclations** [comment]
I think this is fine as is - consistent wit core and likely will change as a result of future homepage layout overhaul
