### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#300]
make sure everything is up to date, version number is bumped, etc.

**Comment by rnagle** [comment]
I'd like to suggest that we change the README to rst or md. Would also be nice to include the Travis build status image (src: https://api.travis-ci.org/INN/Largo.svg?branch=develop).

**Comment by aschweigert** [comment]
Yeah, we should definitely do that

**Comment by aschweigert** [comment]
Is there an advantage to using rst over md for the doc build?

**Comment by willhaynes** [comment]
I don't think .rst is the right choice. Github doesn't do a great job rendering the syntax natively. I'd stick to markdown with links to [largo.readthedocs.org](http://largo.readthedocs.org).

I'll point out that readthedocs supports building from [mkdocs](http://www.mkdocs.org/), which is md based as opposed to rst.

**Comment by aschweigert** [comment]
Sounds good, md it is

**Comment by rnagle** [comment]
Merged @willhaynes' work in bbc615b1d9c573e04a53088aab9da0b660eab808.
