### ISSUE TITLE
Documentation for various third-party integrations/services

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#308]
Mostly how our mailchimp custom feed template works

**Comment by meredithinn** [comment]
Added the start of a page from notes from December office hours.
http://largo.readthedocs.org/users/mailchimp.html

not added to index yet

**Comment by aschweigert** [comment]
moved to /users/thirdpartyintegrations.rst, removing this from the index for now until we flesh it out

**Comment by meredithinn** [comment]
What other integrations might belong here?  A link to the doubleclick repo?

**Comment by aschweigert** [comment]
Off the top of my head...there are probably more...

Email/list management:
- [ ] mailchimp
- [ ] constant contact

Donations/payments:
- [ ] paypal
- [ ] network for good

Social networks
- [ ] fb
- [ ] twitter
- [ ] youtube
- [ ] github
- [ ] linkedin
- [ ] tumblr
- [ ] flickr
- [ ] google+

Analytics
- [ ] google analytics
- [ ] chartbeat

Advertising
- [ ]  Google DFP

Webmaster tools, etc.
- [ ] google webmaster tools
- [ ] bitly

Comment systems
- [ ] disqus
- [ ] facebookk

**Comment by meredithinn** [comment]
Drafted up https://github.com/INN/Largo/blob/moredetail/docs/users/thirdpartyintegrations.md
