### ISSUE TITLE
Test header ad zone

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#316]
Here's how it should work:

1) there is an option under theme options > advanced to enable the header ad zone

2) once enabled this registers the required widget area but there will be no widgets assigned to it and nothing will happen

3) typically sites have been using the "Ad Code Manager" plugin to create and populate the ad zones. /inc/ad-codes.php is where the default zones are created but there are some additional steps required for sites to add their DFP property and zone IDs, assign those to the zones available in Largo, etc. that I believe we still need to document 

Oklahoma Watch (http://oklahomawatch.org/) is a site that has this setup done so we can probably use that as an example (although it's using the previous version of Largo (the current master branch).

So, we need to:

1) test and make sure this is all working as intended in 0.4
2) make sure the styling is ok
3) write docs explaining how to create the zones and enable this option so it's less confusing for people

**Comment by benlk** [comment]
The ad right now is left-aligned in the header: 

![download](https://cloud.githubusercontent.com/assets/1754187/5706731/2a031da2-9a51-11e4-9901-aff4d836ade7.png)

Do we want to keep it that way?

**Comment by benlk** [comment]
Based on discussion with Ryan, we agreed to center the ad zones in the header. a64f8c5 does that.

Docs are in the docs folder as `ads.rst`.
