### ISSUE TITLE
Discussion: rethinking sticky navigation elements

### ISSUE THREAD

**Issue by rnagle** [INN/Largo#318]
How can we  make the sticky nav elements (header and footer) better?

Some questions and thoughts to get started:

- Does the sticky nav header have to mirror the main navigation for the site at all times? It might be useful to have it change based on context.
- Do we need the sticky footer at all?
- Can we change the behavior of the sticky nav header to show/hide based on user behavior (e.g. show when scrolling up, hide when scrolling down)?
- Is there a more appropriate place for things like the donate and social media links that currently reside i the sticky nav?

**Comment by aschweigert** [comment]
I would like to get this resolved for RNS and then all sites moving forward

**Comment by kaeti** [comment]
Here are notes and a handful of use cases. Most of what is discussed above is reflected. Feedback + questions encouraged.

https://docs.google.com/a/investigativenewsnetwork.org/document/d/1WpjfUqJ2kkvsABnP-wfmiyzWHjbD-bws3BhTVzuXehk/edit?usp=sharing
