### ISSUE TITLE
Menu caching weirdness

### ISSUE THREAD

**Issue by drywall** [INN/Largo#319]
Sorry to not do a pull request on this one but I'm not sure what's going on. We just ran into a really weird situation with a client site we're about to kick over to you, in which partials/sticky-nav.php was retrieving a string for global-nav that appears to have been cached somehow. But what it was retrieving didn't match what was set in the admin.

Here's the scenario we encountered in more detail:
1. Squish browser window to see top sticky nav, and noticed "About" item is appearing with some sub-items.
2. Go into WP admin for Menus and observe that NO MENU AT ALL is assigning to the Global Nav location.
3. Look at code for largo_cached_nav_menu() and scratch head.
4. Manually delete transients from wp_options table to see if perhaps something didn't get flushed.
5. Reload site, have mystery menu still present. Check wp_options and see that transient has re-appeared with mystery menu html string.
6. Review currently-extant menus to see if any of them match what's seen in the mystery menu markup. They don't. 
7. Create a new menu called "Empty." Put no items in it. Assign to Global Nav location. Problem solved!

The nearest I can figure out is that at one time early in development we had a menu assigned to the Global Navigation location that was later deleted/removed. So I understand how it might've gotten cached in the first place. But I DON'T understand how it could have gotten re-cached after I deleted the transients since it clearly didn't exist any more.

Maybe someone more familiar with the menu system (and Largo's caching of it – what's that all about?) can weigh in on what might have caused this ghost menu to get cached and not go away?

**Comment by rnagle** [comment]
Investigated this a bit further and found some other strange things were happening. I really don't think we need this layer of caching anyway, so I removed it: 3e7e2ba8d7df9a5d22d8d52e4db3199664eabce3.

The `largo_cached_nav_menu` function is deprecated. Please use `largo_nav_menu` instead and report back if you have any more issues. Thanks @drywall!
