### ISSUE TITLE
problem with guest author slugs using co-authors plus

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#320]
example: http://womensenews.largoproject.org/2014/12/when-glass-ceilings-chip-get-ready-for-break-in/

the author link is correct in the byline but in the author box at the bottom of the post it just links to http://womensenews.largoproject.org/author/ without the slug appended. Maybe an issue we introduced in re-working the author box so we should check and make sure this works as intended with guest authors

**Comment by willhaynes** [comment]
Likely the logic implemented in #279 is slightly off. Worth doing in a way that tests are possible. Right now it's procedural.

**Comment by rnagle** [comment]
Fixed with #327.
