### ISSUE TITLE
fix spacing of social media icons in the sticky header

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#323]
looks like some css got removed in the last set of changes so they're now too far apart (spaced the same as the other list items in the nav), e.g. - 

![header](https://cloud.githubusercontent.com/assets/490703/5631963/d287e362-9598-11e4-8176-85a1948d45db.png)

maybe try 3-ish px of padding instead of 10

**Comment by rnagle** [comment]
Fixed this in 973598607b32ad65a8c523773694f574ccb5ffa9.
