### ISSUE TITLE
site name should probably persist in sticky/mobile nav on smaller viewports

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#324]
see, for example voiceofoc.org on small viewports, it's weird that their is neither a site name nor a logo displayed anywhere

**Comment by benlk** [comment]
On Voice of OC (And in normal Largo), here's what the sticky header structure looks like:

	<nav id="sticky-nav" class="sticky-navbar navbar clearfix open">
		<div class="container">
			<div class="nav-right">
				
			</div>

			
			<a class="btn btn-navbar toggle-nav-bar" title="More">
				<div class="bars">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</div>
			</a>

			<div class="nav-shelf">
				
				
			</div>
		</div>
	</nav>

If we add this inside `div.container`, then the site title can be visible when `div.nav-shelf` and its contents have been hidden:

			<div class="nav-right">
				
			</div>

This means that the image/title shows up more than once in the HTML given to the reader, but we already do that for the main and global navs. 

Therefore, hide it using media queries:

	@media (max-width: 768px) {
		.nav-left {
			display: none;
		}
	}

At 769px and greater, `div.nav-shelf` is visible and not collapsed, so if they have "Show the site name in the sticky nav" enabled in Theme Options > Basic Settings, the site name will appear there.

Does this sound like a plan? Or is there a better way to do it?

For Voice of OC, [they're using a custom nav](https://bitbucket.org/projectlargo/theme-voice-of-oc/src/68eb12c2a74f192f3befc47f8e034074f32c5bdb/partials/nav-sticky-ack.php?at=master) which will need to be edited to match the changes made in Largo.

**Comment by benlk** [comment]
If these changes look good, I'll add the `.nav-left` to `largo-umbrella/theme-voice-of-oc`.

**Comment by benlk** [comment]
Branch sticky-header-logo of `largo-umbrella/theme-voice-of-oc` has this change, which depends on #335 for hiding the site name in `.nav-shelf`'s dropdown menu.

All they should have to do is check the "Show the site name in the sticky nav".
