### ISSUE TITLE
Disappearing social icons on single posts

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#326]
Reported by City Limits, the social icons under the byline on story pages don't seem to be respecting the theme option (under the "single post options" on the first tab), when set to "top" the bar with the social icons should display at the top of the post as in previous Largo versions (right now nothing is displaying).

**Comment by benlk** [comment]
If their option is set to "both" or "btm" then it will no longer appear on the page: https://github.com/INN/Largo/commit/c071c611c93b011b05b951250620f1d8f0058b2f

Quick fix is to ask them to go in and re-save the option as "Top" in Theme Options > Basic Options > Single Post Options.

Do we want the top icons to continue to show if "both" is set? (really, if it's not "none") Legacy support.

**Comment by aschweigert** [comment]
Yeah, they have it set to "top" though, and, oddly, the dropdown only has "top" and "both" as options, "bottom" doesn't even appear.

Which...technically is how it should be. Except then we don't really need "both" either. So really this should probably just be a checkbox to show them under the byline or not...i think?

**Comment by benlk** [comment]
Bottom ... isn't an option in `largo-umbrella/largo-dev`, and there isn't an overriding `options.php` in `largo-umbrella/theme-citylimits`, so how does it have "both"? Is "None" an option? I'm confused.

**Comment by aschweigert** [comment]
Gah, sorry, it has "top" and "none" but that's silly, should just be a toggle instead of a dropdown

**Comment by aschweigert** [comment]
And "top" does not work as intended, hence the bug report

**Comment by benlk** [comment]
If they re-select "top" and re-save, does that fix it?

**Comment by aschweigert** [comment]
oh, it did...what the

**Comment by rnagle** [comment]
When you remove an option, the Theme Options page will display the (new) default as the option that is selected even if some non-existent option is actually stored in the database. Kinda silly...

Anyway, I think @aschweigert is right, this should be an on/off toggle now. In theory, this should be fine for sites that are already using the develop branch if we change the name of the id/slug for the option.

**Comment by benlk** [comment]
#334 makes it an on/off toggle now, with a different slug. OK to close?

**Comment by rnagle** [comment]
Yep, looks good to me!
