### ISSUE TITLE
hooks and filters

### ISSUE THREAD

**Issue by aschweigert** [INN/largo#330]
Let's take a comprehensive look at where we've put hooks into Largo so far and come up with a more fully-baked plan for how these are implemented, add more where it makes sense, document everything, make Largo generally easier to extend and modify without having to override as many templates, etc.

**Comment by benlk** [comment]
- [x] category pages: #1217

**Comment by rclations** [comment]
Once we overhaul the base theme to run off _s and remove a lot of the over-engineering in the templates, i think we'll have little need for additional hooks/filters. Definitely something I'll keep in mind though moving foreword in case it seems appropriate anywhere.
