### ISSUE TITLE
update default child theme

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#337]
we have a default child theme linked here: http://largoproject.org/setup/download-and-installation/ that we probably need to review and update for 0.4 (maybe add an example homepage template, functions.php, etc. to document how to extend certain things). Ideally we should try to have this ready for when we ship 0.4 but we might be able to ship it separately soon after.

A further question is whether we ought to just keep this in the theme repo and/or create a new github repo for it and link to that instead of just uploading a zip file.

**Comment by aschweigert** [comment]
made a repo for this here: https://github.com/INN/Largo-Sample-Child-Theme

see also #336

**Comment by ithacaindy** [comment]
The sample child theme link throws a 404.

**Comment by aschweigert** [comment]
it's still private until we get it setup

**Comment by aschweigert** [comment]
since the basics are there now, closing this and we'll track issues over there as we continue to add to it.

**Comment by aschweigert** [comment]
If you're a developer working on child themes and have requests for documentation or questions about the new default child theme, please open a new issue here: https://github.com/INN/Largo-Sample-Child-Theme/issues

Thanks!
