### ISSUE TITLE
Overlapping visibility between .hidden-desktop and .hidden-phone.hidden-tablet

### ISSUE THREAD

**Issue by benlk** [INN/Largo#341]
On viewpoints between 769px and 979px, the following divs are both visible:

    <div class="hidden-desktop hidden-tablet"></div>
    <div class="hidden-phone"></div>

This can be demonstrated by creating two widgets in the same sidebar, then setting one to hide on phones and tablets, while the other is hidden on desktops.

The `.hidden-desktop` remains visible up to 979px, while `.hidden-phone.hidden-tablet` is visible from 769px up.

The reason for this appears to be that `.hidden-desktop` is set to `display: inherit !important` in [style.css](https://github.com/INN/Largo/blob/develop/css/style.css#L4922-L4924), but is not inheriting the `.hidden-desktop { display: none !important }` set earlier in the document.

**Comment by aschweigert** [comment]
While we're at it we should probably consider whether to use the new regime bootstrap responsive classes instead of/in addition to these. Largo was originally built using bootstrap v.2 but they changed how these work in v.3 See: http://getbootstrap.com/css/#responsive-utilities

**Comment by benlk** [comment]
If we use the Bootstrap 3 responsive code, will Largo end up switching to Bootstrap 3?

**Comment by aschweigert** [comment]
I really just used it as a starting point and didn't keep the entire framework because it's (imo) too heavy for production sites, we could definitely probably steal some ideas from the new version though and incorporate them

**Comment by benlk** [comment]
#449 merged, so I'm closing this issue, but there's #451 for 0.6.
