### ISSUE TITLE
Review Download and Install page

### ISSUE THREAD

**Issue by meredithinn** [INN/Largo#344]
Review download and install page for .4
http://largo.readthedocs.org/en/develop/users/download.html

Note:  Perhaps the child theme repo should be integrated here.

**Comment by meredithinn** [comment]
Thinking about a label that helps identify items for review -- rather than tied to a pre-launch to do

**Comment by benlk** [comment]
"Needs eyes" ?

**Comment by aschweigert** [comment]
Needs edit

*Adam Schweigert*

mobile: 812-219-2624

gtalk: aschweigert


http://adamschweigert.com

twitter: @aschweig <http://twitter.com/aschweig>

**Comment by aschweigert** [comment]
we already have a "help wanted" label but I was thinking of that more in terms of issues that would be friendly for open source contributors. I think a "needs edit" or "needs review" label would probably be more in line with what you're thinking here.

**Comment by meredithinn** [comment]
Yes, I like the needs edit or needs review makes sense.  Does need review have more versatility?
