### ISSUE TITLE
allow site admins to purge pending user registrations

### ISSUE THREAD

**Issue by aschweigert** [INN/largo#346]
A common request we get is something like "people don't know they need to click on a link in an email to confirm their registration so they wind up stuck in purgatory and can't sign in and we can't set a password manually for them, etc."

IMO this is as intended and I'm not sure we should change the default WP workflow for user creation any more than we already have, but...maybe we could make it so that site admins could see pending registrations and purge/resend the invitations?

**Comment by eyeseast** [comment]
+1e6

**Comment by benlk** [comment]
This is plugin territory, not Largo theme territory.
