### ISSUE TITLE
Review Theme Options doc page

### ISSUE THREAD

**Issue by meredithinn** [INN/Largo#348]
Review Theme Options doc page for accuracy and fit to v.4

http://largo.readthedocs.org/en/develop/users/themeoptions.html

**Comment by aschweigert** [comment]
This one is way out of date, we'll need to make sure we add all of the new options in 0.4 and move any deprecated options to a section below (see, for example, how I organized: http://largo.readthedocs.org/users/menus.html)

Typically we'll want to keep deprecated options in the docs for at least one release past when they were removed or become no longer applicable so people making the update know what has changed.
