### ISSUE TITLE
landing pages menu item still appears when series taxonomy is disabled

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#349]
When the series taxonomy is disabled and custom landing pages are enabled (from the "advanced" tab of the theme options, the landing pages menu item still appears even if that box appears to be unchecked (including after theme options are saved as far as I can tell)

**Comment by benlk** [comment]
Weird. I can't reproduce this behavior unless I deliberately break the javascripts running in the theme options admin page. 

With scripts running, when you uncheck the `series_enabled` box, `custom_landing_enabled` is also unchecked. Save options, the "Landing Pages" menu item disappears. 

Without scripts running (probably rare among our users), I can check the `custom_landing_enabled` box but not the `series_enabled` box, meaning the plugin is enabled while series are not.

https://github.com/INN/Largo/commit/23738a8b7ae6eea314a23e1bd28ad5fec81ffc80 Makes sure that cftl is only enabled when series are.
