### ISSUE TITLE
add meta description tag to site header

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#351]
We're getting some reports of sites having problems, particular with Google News, where the excerpt it chooses to show is just a weird random bit of text from the page instead of the excerpt they've set. I looked into this a little bit and we set the og:description in inc/open-graph.php but it appears we don't explicitly set the meta description tag and we probably should (to the same value we use for the og:description, probably).

**Comment by benlk** [comment]
Fixed in 2569738, uses the same description content as og:description, in the same place.
