### ISSUE TITLE
account for duplicated hero/featured images in upgrade process

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#354]
for example: http://investigatemidwest-org.largoproject.staging.wpengine.com/2014/12/16/federal-spending-bill-primed-to-boost-food-safety/

is there some way we could programmatically remove images at the tops of posts when using the new article page template? 

It seems like we could just look for posts that start with a caption shortcode and strip that out but we would need to proceed with caution to make sure we don't strip things that need to remain there. Thoughts?

**Comment by willhaynes** [comment]
I'd suggest writing a content filter to remove that first image without deleting it from the database. After the database process (when we're happy that we haven't broken anything) we could with the same logic do a physical delete from the database.

**Comment by willhaynes** [comment]
@aschweigert Thoughts when a post has a feature image at the top that might be medium/floated (not inserted like a hero?)

**Comment by aschweigert** [comment]
Yeah, that the situation I was worried about because, in some cases, that might NOT be the same as the featured image so we'd probably want to keep it (maybe). There's also the problem where the featured image for a post is tiny and/or doesn't make sense as a hero image that we should probably try to account for. The content filter seems like a decent first thing to try though for this immediate problem.

**Comment by willhaynes** [comment]
I think we're looking at this sudo code for the filter.

```
if(post has a top image):
	if(post is full width & big enough):
		hide it, display hero
		return
	else:
		don't hide it, don't display hero
		return
else:
	return
```

**Comment by aschweigert** [comment]
yeah, that seems right to me

**Comment by aschweigert** [comment]
just waiting on tests for this, right? anything else still to do?
