### ISSUE TITLE
Settings for the Clean Contact plugin should be under the Settings menu, not Plugins

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#355]
Because otherwise site admins in multisite won't be able to get to those settings.

This should be a minor change that needs to be made in lib/clean-contact

and the docs will also need to be updated in docs/users/contactpages.rst

**Comment by aschweigert** [comment]
should just need to use add_submenu_page instead of add_theme_page on line 272 of lib/clean-contact/clean-contact.php but you'll want to double check and make sure the parameters/order are still correct

**Comment by benlk** [comment]
In current develop, Clean Contact settings are under Appearance?

**Comment by aschweigert** [comment]
Definitely under plugins on staging and production...are you looking at it in multisite or in a standalone WP instance?

**Comment by benlk** [comment]
In a standalone, which would be the problem.

**Comment by aschweigert** [comment]
weird, i wonder why it's handled differently in multisite
