### ISSUE TITLE
Plugins Documentation page needs review 

### ISSUE THREAD

**Issue by meredithinn** [INN/Largo#356]
The Plugins list on the documentation page does not match those that appear in a Largo site.
http://largo.readthedocs.org/en/develop/users/plugins.html

Please review the list of currently available below, additional plugins from docs and unsupported.

Those below appear to be available on a WP Largo Install:

Askimet
Argo Audio Player
Argo Links
Business Directory Plugin
Business Directory Plugin - Paypal Gateway Module
Clean-Contact
Largo Extended
Navis DocumentCloud
Navis Jiffy Posts
Navis Sildeshows
Navis Quizzes
WP Member

**Should any of these be deleted?**
All in One SEO Pack
Disqus Comment System
Edit Flow
WP Google Ad Manager
Winer Links
Tweetable Text
Curated Plugins
Caspio Deploy2
Chartbeat
Co-Authors Plus
Liveblog
Redirection
Simple Tags
Storify
TablePress
Tiny MCE Advanced

Utilities:
Categories to Tag Converter
CodeStyling Localization
Core Control
Theme-Check
Vice Versa
Wordpress Importer

**Unsupported Plugins -- any changes?**
AdRotate
Advanced Custom Fields
Breadcrumb NavXT
Charity-Thermometer
WinerLinks
WooDojo
Pippity
Facebook comments
Iframe

**Comment by aschweigert** [comment]
Made a first pass at this. Still todo:

- [ ] add links to the page in the WP plugin directory (or author's site) for each plugin so they're available for easy reference
- [ ] add links to other relevant places in our docs for things we have more detailed information for (e.g. - the clean contact plugin)

**Comment by aschweigert** [comment]
@meredithinn do you want to take a crack at those to-dos?

**Comment by aschweigert** [comment]
closed with 38636a0
