### ISSUE TITLE
Possible to show the "featured override" checkbox outside the featured media modal?

### ISSUE THREAD

**Issue by rnagle** [INN/largo#357]
In an effort to save a click for users, perhaps we can place this next to the "Set/Edit featured media" button above the post editor?

**Comment by rnagle** [comment]
This checkbox:
![screen shot 2015-01-20 at 1 46 49 pm](https://cloud.githubusercontent.com/assets/72608/5824582/25e07246-a0ab-11e4-88c2-6fab8ec4095a.png)

**Comment by willhaynes** [comment]
The copy of this checkbox seems confusing to me (what are you overriding, for which display?)

Some options:

- [ ] Do not display as hero on article page.
- [ ] Use only as post thumbnail on article listings.
- [ ] Hide on article page.

Or others?

**Comment by rclations** [comment]
this was completed in 0.5.5 https://github.com/INN/largo/releases/tag/v0.5.5
