### ISSUE TITLE
update docs/glossary.rst

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#358]
what's in there now is all duplicated in docs/taxonomies.rst

we should either flesh it out or remove it

**Comment by meredithinn** [comment]
I agree that it feels out of place.  I would suggest that an overview glossary might be helpful to include with the style guide but feels redundant here.

**Comment by aschweigert** [comment]
It would definitely need to be much more complete to be useful...going to remove it for now and we can always re-add it later. I do think it would be helpful to read through all the docs at some point and grab any terms that could potentially be too technical/confusing for novice users, pull them into a glossary and define them, but that could be an enhancement in a future version.

**Comment by meredithinn** [comment]
The beginning of a glossary https://github.com/INN/Largo/blob/master/docs/users/glossary.md
