### ISSUE TITLE
minor css issues

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#364]
looking at http://investigatemidwest-org.largoproject.staging.wpengine.com/ as an example, we have:

- [x] search box is slightly misaligned in the global header, probably just needs a slight top margin to push it in line with everything else

![untitled](https://cloud.githubusercontent.com/assets/490703/5858441/2ffbef72-a221-11e4-9631-b810586c496f.png)

- [x] the main nav bar overlaps the right edge of the banner image by about 5px

![untitled1](https://cloud.githubusercontent.com/assets/490703/5858467/5bbb4cca-a221-11e4-9f2f-aa1f4657f2e1.png)

This is site is using the LESS/CSS customizer and I haven't noticed these issues before on sites that started from 0.4 and don't use that so it's possible that's the cause of the weirdness...maybe.

**Comment by aschweigert** [comment]
tagging @kaeti here too, let's add anything that seems like a really quick/minor fix to this ticket so we can try to kill as many of them as possible

**Comment by aschweigert** [comment]
should have mentioned this is in chrome

**Comment by benlk** [comment]
It is a thing in Firefox as well.

Did you notice that the social icons beside it are not the same height as the Donate button or the search, and that the offset between the social icons and the donate box is different than between the donate box and the search box?

**Comment by aschweigert** [comment]
Yeah, there are quite a few little things. Seems to be consistent on other sites though, e.g. - http://citylimits.org/

So, probably does need to be fixed in Largo proper instead of a child theme or problem with the LESS/CSS thing

**Comment by benlk** [comment]
![screenshot - 01222015 - 06 43 53 pm](https://cloud.githubusercontent.com/assets/1754187/5867192/b9a494f0-a266-11e4-88c2-8a52002ab28f.png)

At 200% zoom, this is the difference between Firefox and Chrome. The lower text is Firefox.

**Comment by benlk** [comment]
(The search bar margin-top fix was applied in https://github.com/INN/Largo/commit/b0171dca95300174d71c92123feb739a51a7f56d)

**Comment by benlk** [comment]
Social icon buttons are [now](https://github.com/INN/Largo/commit/a7b06becd9f8534834db20d7127969d90acb7a01) the same size (approximately, off by one pixel at 200% zoom) as the "Donate Now" button and are [consistently spaced](https://github.com/INN/Largo/commit/e9199ae7aca12106e01ba4660efc6b9ecc7ec369) in the header and the sticky navbar.

The 5px was because of `.navbar-inner` padding, which has [been removed](https://github.com/INN/Largo/commit/81afc3c6c468462f3da11f201b38a53b13098a79). Do we want to keep that style of padding before the first item in the list?

**Comment by benlk** [comment]
Okay to close this?

**Comment by aschweigert** [comment]
I think so. Everything look ok to you, @rnagle? The extra padding at the front of .navbar-inner, i suspect, was there to give the home icon a little more breathing room so it's probably no longer necessary.

**Comment by benlk** [comment]
Just noticed that spacing is off when "Donate" button is missing, because donate has padding on both sides and the search has none.

**Comment by benlk** [comment]
Fixed that in 44bd679
