### ISSUE TITLE
Source maps for CSS?

### ISSUE THREAD

**Issue by benlk** [INN/Largo#369]
Largo's CSS rules are scattered across a large number of LESS files, and sometimes tracking down which file is creating a property is difficult. It would be nice to have `grunt watch` or `grunt less` build source maps, even if they aren't included in this repository and are `.gitignore`'d.

Not something for 0.4, but something I think should be considered for future builds.

**Comment by aschweigert** [comment]
I'm definitely pro-explaining more about what's where. We had a request previously to include an unminified version of style.css in addition to the minified version so that might be a good place to start, but having more documentation here would also help

**Comment by benlk** [comment]
If we're building the source map files, should they be included in the repo, or should they be in `.gitignore`? cc @rnagle 

`grunt-contrib-less` doesn't *currently* support outputting multiple source maps, or compiling a single source map from multiple files. When https://github.com/gruntjs/grunt-contrib-less/pull/243 is merged in, we'll be able to set `combineSourceFiles: true` in the less development task.

The solution until then is to have the [Gruntfile compile an all-in-one .less file](https://github.com/gruntjs/grunt-contrib-less/issues/89#issuecomment-71093468) and then rander source maps from that.

**Comment by benlk** [comment]
It looks like [gruntjs/grunt-contrib-less#243 isn't going to be merged in](https://github.com/gruntjs/grunt-contrib-less/pull/243#issuecomment-75196554). (Unless a contributor reopens; they appear to be divided on the subject.)

We can try [this workaround](https://github.com/gruntjs/grunt-contrib-less/issues/89#issuecomment-71093468) or figure out something using [grunt-contrib-concat](https://github.com/gruntjs/grunt-contrib-concat).

**Comment by benlk** [comment]
I've created a sourcemaps branch. https://github.com/INN/Largo/commit/f6b0daf95d2d8abdeb5605a3bbd712d7ca407be5 puts sourcemaps inline, when `grunt watch` and `grunt less:development` are run. it does not run that way for `grunt less:production`.

Advantages of this over separate map files:

- currently possible

Disadvantages:

- inline source maps in development should not make it into production
- inline source maps can be up to 250,000 characters in `css/style.css` and will negatively affect performance if committed, unless the inline sourcemaps are stripped by minification and [if we use the minified version of files in production](https://github.com/INN/Largo/issues/432).
- inline source maps cannot be used independent of minification.

**Comment by benlk** [comment]
#646 merged, so closing this!
