### ISSUE TITLE
permissions issue with clean contact on options save

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#370]
From the Appearance > Clean Contact menu, when you hit "save options" the options do appear to be saved, but I get an error page that says "Cannot load clean-contact." instead of just confirmation that the options have been saved.

**Comment by benlk** [comment]
Can you confirm the following URLs?

- Appearance > Clean Contact: http://vagrant.dev/wp-admin/themes.php?page=clean-contact
- Error page URL post-"save options": http://vagrant.dev/wp-admin/options-general.php?page=clean-contact&message=updated

It looks like the [redirect on save](https://github.com/INN/Largo/blob/master/lib/clean-contact/clean_contact.php#L78) is to a page that doesn't exist, namely the clean-contact settings page under general settings. This should be solved by #355's solution.

**Comment by aschweigert** [comment]
Yeah, for example:

http://largo.inndev.wpengine.com/wp-admin/themes.php?page=clean-contact
http://largo.inndev.wpengine.com/wp-admin/options-general.php?page=clean-contact&message=updated

Let's get that other commit merged and then we can confirm.

**Comment by benlk** [comment]
It's in develop right now.

**Comment by aschweigert** [comment]
develop pre-0.4 or post-0.4?

**Comment by benlk** [comment]
post-0.4. Should I put those commits in master?

**Comment by aschweigert** [comment]
if it's a bugfix that's not going to cause complications for anyone, then i'd say yes. as a separate branch and pull request though so we can be extra certain everything is cool before merging.
