### ISSUE TITLE
Sample Child: Logo Image Doesn't Appear

### ISSUE THREAD

**Issue by ithacaindy** [INN/Largo#373]
I prepared my site for Largo 4, updating the database. I installed the new sample child, setting the top style to full-width. When viewed (from two browsers and two computers) the site logo image doesn't display. When I switch the top style to newspaper, the logo reappears. When I switch it back to full-width it's gone. The logo appears when I use the Largo parent theme or I switch to the default WordPress theme. I like the full-width top style because of its greater widget flexibility (left, center and right widgets).

**Comment by aschweigert** [comment]
Hi Ed - In this new version the full header image only appears on the homepage by default and a slimmer top menu is used for all internal pages. Is that what you're referring to or something else? Also, as with the other issue you opened, you probably don't want to use the full sample child theme, just the pieces that you need.

**Comment by ithacaindy** [comment]
Adam - The logo doesn't appear on the homepage. I'll take a look at the
sample child theme with the aim of updating my Largo 3 child theme. Thanks.

Best,
Ed

**Comment by aschweigert** [comment]
Did deactivating your plugins resolve this one too? Guessing this is also a JS conflict with a plugin and can probably be closed.

**Comment by ithacaindy** [comment]
Yes, the plugin off/on reenabled the frontpage logo graphic.

**Comment by aschweigert** [comment]
Any idea which plugin(s) were the culprits?

**Comment by aschweigert** [comment]
Oh, also (I don't think this is related to this issue, but just FYI), depending when you last updated/installed Largo, the media credit, slideshows and clean contact plugins are now included in the theme directly so if you have those installed in your plugins folder you can remove them.

**Comment by ithacaindy** [comment]
I'll remove clean contact. I'm not sure which plugin was aborting the logo and/or messing with the fixed menu, but when I have time I'll track it down.
