### ISSUE TITLE
figure out some way to keep long sticky nav menus from wrapping

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#376]
this drives me nuts, we should probably fix the length of that menu and cut off the extra items or fade them or something so they don't wrap.

or something.

**Comment by benlk** [comment]
Easy way is with `overflow:hidden;`

Another way to do it would be to sum the widths of the first-level children of the navbar `ul`, and if that's greater than the width of the navbar or nav-shelf, then hide from the end until the sum is less than the thing.

Or, the same approach, but create a drop-down at the end of the navbar, then add the first-level child li elements to it.

**Comment by benlk** [comment]
Will suggests: Use JS to collapse the nav ul to the standard drop-down menu

Ryan suggests: nav menu overflow scrolls off to the side, like at http://www.americastestkitchenfeed.com/

**Comment by benlk** [comment]
Another scrolling overflow menu, [via @rdmurphy](https://twitter.com/rdmurphy/status/585584402320728064): http://theguardian.com/us.

**Comment by benlk** [comment]
Since we decided that #703 wasn't going to be used in Largo (but it will be used in NPQ), what alternative solutions are we looking at for dealing with menus that are too long?

**Comment by benlk** [comment]
Update: Continue bulletproofing the NPQ solution for Largo.

- Find fix for on page load.
- Make the collapse function call itself if it's not fully collapsed?
- If it collapses fully on page load, (initial Flash of Unstyled Content not withstanding), then the trigger event won't need to be onscroll, but instead on a viewport resize.

**Comment by benlk** [comment]
When this merges, we'll need to cut it out of NPQ.

**Comment by aschweigert** [comment]
needed for RNS-55

**Comment by benlk** [comment]
Actually, once #1024 merges, we're going to have to fix NPQ anyways. And this issue won't be able to use NPQ code any more.

Gonna wait until #1024 merges.

**Comment by benlk** [comment]
#1024 merged.
