### ISSUE TITLE
STRONGLY encourage people updating from 0.3 to 0.4 to use the new single col article template

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#378]
We're being a little too nice and they might not even know it exists unless we make this more explicit

**Comment by aschweigert** [comment]
we might even want to make it the default and just let them know we changed it and how to change it back if they need to

**Comment by rnagle** [comment]
The single column layout is now the default for sites upgrading to 0.4+. Where should the info about the change be made available? Should we flash a notice after updating and/or should this be something that's addressed via documentation?

**Comment by aschweigert** [comment]
We might be able to handle it with documentation but I'm just concerned that people won't know about the new stuff that's available. Maybe, for future releases, we could do something like WP does now when it's updated where the dashboard is a one page overview of the new release. Not sure how involved that would be though...

**Comment by rnagle** [comment]
I'm inclined to close this issue or change the focus to "how to highlight new features after updated" or something like that. Pitching this for `0.6` or `0.7` as it seems like a big undertaking.

Some thoughts -- 

I think the "must have" item here is a meta box on the main "Dashboard" page that shows when Largo is updated. Link to the page with release notes and links to all sections of the theme that have been updated.

Nice to have: I like how WordPress (and others) use tooltips to highlight new things, allow the user to dismiss them, etc. If WP core makes it easy enough to use that stuff, we can probably get pretty far with that strategy.

**Comment by aschweigert** [comment]
Yeah, I agree. Let's try to explore that stuff a bit in 0.6
