### ISSUE TITLE
kill the negative margins on the new article template

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#379]

**Comment by aschweigert** [comment]
with a few exceptions...for example, images/pullquotes/etc. within a story floated left/right SHOULD push outside of the text block (they do on Wisconsin but this seems to have gotten ripped out of Largo proper at some point).

and we should try to get back to making the heroimage and sufficiently large images within stories full bleed (#290)

**Comment by aschweigert** [comment]
this could probably be moved to 0.5 but let's see what we can do

**Comment by willhaynes** [comment]
Pull request https://github.com/INN/Largo/pull/420

**Comment by willhaynes** [comment]
#420 merged back in, closing this.
