### ISSUE TITLE
docs coverage for all post edit screen custom functionality

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#381]
Particularly thinking about the new featured media manager stuff that snuck in under the buzzer in 0.4, but we should probably make that a part of a larger doc covering all of the stuff we add to the post/page edit screen, so:

- [x] featured media manager
- [x] modules/pull quotes (button added to tinymce toolbar)
- [x] custom byline options (what this is for but also best practices for formatting bylines, e.g. - typically admins should create "real" WP users rather than using plain text to override, use co-authors plus plugin for multiple authors, only use custom byline as a last resort)
- [x] layout options (basic explanation but then link to docs on post templates and custom sidebars)
- [x] additional options: how the related posts widget works, what this box is used for, how to find/enter related post ids; top term dropdown (how this is populated, what it's used for on the frontend of the site)

**Comment by aschweigert** [comment]
maybe also link to the custom taxonomies doc to explain those as well + any relevant WP codex resources on creating/managing posts generally

**Comment by meredithinn** [comment]
added additional topics

**Comment by jackbrighton** [comment]
Fully covered in the Largo User Guide in: 

- https://github.com/INN/Largo-User-Guide/blob/master/docs/publish-content-part-one.md,
- https://github.com/INN/Largo-User-Guide/blob/master/docs/publish-content-part-two.md
- https://github.com/INN/Largo-User-Guide/blob/master/docs/images-and-media.md 

Still need to add much of this to the Largo Project docs.

**Comment by jackbrighton** [comment]
Should be complete now in both the Largo Users Guide and the Largo Project docs on readthedocs. One thing that isn't done: adding https://github.com/INN/Largo/blob/master/docs/users/posting.rst to the main menu. I don't see where that's accomplished.
