### ISSUE TITLE
INN_MEMBER constant not respected in child theme functions.php

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#386]
eg. - ijec.org

functions.php includes:

define( 'INN_MEMBER', FALSE );

and yet the INN member badge and member stories widget are displayed

**Comment by willhaynes** [comment]
Problem here is that runtime constants are supposed to be just that — constant. [There's some workarounds](http://php.net/manual/en/function.runkit-constant-redefine.php) but nothing terrible good.

Options:

- We could change the define to a global variable.
- We could turn this functionality into a function call `is_inn_member()`

**Comment by aschweigert** [comment]
yeah, we were defining it previously in the parent theme's functions.php which worked because it would be executed after the child theme's functions.php but we moved it to wp-config and that introduced this problem. We could make it a function call or come up with some other solution but it's definitely broken in its current incarnation.

**Comment by willhaynes** [comment]
I'll figure something out.
