### ISSUE TITLE
docs for sticky footer

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#387]
(via twitter: https://twitter.com/notblue/status/561254108695240705 and https://twitter.com/notblue/status/561254327457546241)

sounds like we need to explain a little more how it's choosing the topics to follow.

I haven't reviewed it too closely but I *think* it uses the top term for the post and then falls back to just categories/tags/series but we should double check and create some docs to explain.

**Comment by meredithinn** [comment]
Drafted a KB article for this for now.  Maybe it belongs with Post Formatting?

**Comment by aschweigert** [comment]
since this only appears on single article pages it probably belongs with post formatting/single post options, i would think, should be covered in the docs though as well as the kb

**Comment by meredithinn** [comment]
Added to https://github.com/INN/Largo/blob/master/docs/users/posting.rst

**Comment by benlk** [comment]
Sticky footer no longer exists.
