### ISSUE TITLE
Guest Author archive URLs not being rendered in footer-sticky.php partial

### ISSUE THREAD

**Issue by drywall** [INN/Largo#388]
For some reason, the calls to get_author_feed_link() and get_author_posts_url() used for rendering the "Follow" link in the sticky footer aren't returning the proper URLs when the post's author is a Guest Author. See for example http://chicagoreporter.com/elderly-on-west-and-south-sides-targets-of-reverse-mortgage-scheme-say-advocates/

**Comment by willhaynes** [comment]
Included in #639
