### ISSUE TITLE
sharethis share/email buttons are broken

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#389]
let's plan to remove them anyway in 0.5

**Comment by benlk** [comment]
Should this also remove the "Tweet", "Like" and "Print" buttons, and the entire article-top sharing buttons area?

**Comment by aschweigert** [comment]
probably, or they should use a similar technique as in the sticky footer, only make the call to fb/twitter when someone clicks on them instead of loading all the extra cruft on every page

**Comment by aschweigert** [comment]
We should probably talk about whether we need a print button or not. I would say no, but we have some members who insist that it's necessary so...?

**Comment by benlk** [comment]
They can disable it they don't want it; it's an option in the theme settings.

OK to close?

**Comment by aschweigert** [comment]
What does it look like now that sharethis is gone? The print icon is the only one that remains floated to the right in that bar?

**Comment by benlk** [comment]
Yes, it's the only one floated left. 

Should these share buttons be visible on the single-column article template as well? They aren't visible on the two-column template.

![screenshot - 03232015 - 10 49 21 am](https://cloud.githubusercontent.com/assets/1754187/6782465/b5272ff6-d14a-11e4-9916-e1cc0689fe23.png)

**Comment by aschweigert** [comment]
That looks fine, it should also work on the new single column template too, though. This is related to #440, we need to make sure the > 0.4 theme options make sense and don't confuse people by not working either the way they used to and/or not doing what they claim to do.

**Comment by benlk** [comment]
#442 merged, with buttons on the single column template, so I think it's safe to close this?
