### ISSUE TITLE
Feature: CPT in Category Include/Exclude

### ISSUE THREAD

**Issue by ithacaindy** [INN/Largo#395]
Perhaps for 5.0. the Other Homepage Display Options could be expanded to include Custom Post Types, as well as Category ID. I try to reserve categories for general posts while CPTs are used for particular post collections. So it would be nice to have the option to set the "Front" CPT to display only posts marked for the frontpage.

**Comment by aschweigert** [comment]
Isn't that the same as #385? or something different?

**Comment by ithacaindy** [comment]
It is, now that I remember.

Best,
Ed
