### ISSUE TITLE
Parse error functions.php on line 230

### ISSUE THREAD

**Issue by ipyl** [INN/Largo#396]
When trying to activate Largo 0.4 the following comes up:

Parse error: syntax error, unexpected T_FUNCTION in /home/ukrwe0/public_html/wp1/wp-content/themes/largo/functions.php on line 230

Tried several times. PHP version 5.2.17.

Please help.

Thank you.

**Comment by aschweigert** [comment]
We do state that Largo is only compatible with PHP 5.3+ so you might want to update to a newer version of PHP (or ask your hosting company if you don't have control of that directly). That should resolve this error for you.
