### ISSUE TITLE
Customizer draws from largo even when child theme uses largo-dev

### ISSUE THREAD

**Issue by benlk** [INN/largo#398]
Discovered this with the MTCIR theme on Vagrant, using the current largo-umbrella.

If themes/largo is checked out at 0.3, themes/largo-dev is at 0.4, and the child theme is using Largo's CSS Variables customizer, then triggering a LESS-to-CSS rebuild will result in 0.3 styles being used in the child theme's customized CSS.

**Comment by benlk** [comment]
wasn't this fixed?

**Comment by rclations** [comment]
no largo-dev

**Comment by benlk** [comment]
Chicago-reporter still does: https://github.com/INN/umbrella-chicagoreporter/tree/master/wp-content/themes/

This issue doesn't affect them, though, because they don't use the LESS Customizer.
