### ISSUE TITLE
custom taxonomies not available to add to menus

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#399]
This is true in both 0.3 and 0.4. When you go to Appearance > Menus, the option to add a series (or post type, etc.) to a menu is only available to network admins, it seems. It should be available to regular administrators as well.

**Comment by willhaynes** [comment]
Checked this one more time to make sure I'm not crazy.

Using my admin account, I'm still able to add these to menus, although I have to make them visible screen options:

![screen shot 2015-03-02 at 2 56 56 am](https://cloud.githubusercontent.com/assets/3745345/6447751/85fe57e8-c0da-11e4-83f7-e0b55915cd37.png)

![screen shot 2015-03-02 at 2 57 21 am](https://cloud.githubusercontent.com/assets/3745345/6447757/970cca24-c0da-11e4-865b-388548d2c578.png)

**Comment by aschweigert** [comment]
Do we know if there's a way to check those boxes by default?

**Comment by willhaynes** [comment]
Yes, there is. Which would be best to show? All, or just post type & series?

**Comment by aschweigert** [comment]
I would say if they're active (from the setting in the theme options menu) we should show them by default
