### ISSUE TITLE
Refactor sticky nav site logo display

### ISSUE THREAD

**Issue by benlk** [INN/Largo#401]
The current sticky nav solution is perhaps suboptimal:

- Home icon is replaced with the square logo from Theme Options > Theme Images > Upload a Square Thumbnail Image, and this image is forced to be square, even if it is not. This image is also used for the actually-square Apple icon image.
- Basic Settings > Menu Options > "Show the site name in the sticky nav" is required to get *any* link to the homepage in the sticky nav on mobile browsers

Suggestion:

- [x] Create a separate "site logo" image field for the sticky navimage, so it can be rectangular, like is used on voiceofoc.org. This image should be at least 50px wide and tall.
- [x] Use this new "site logo" image for "home icon" image
- [x] Set `html .sticky-nav-holder .navbar .nav-shelf li.home-link a img { width: auto;}` so that the image will resize horizontally if it is not square
- [x] Image should also be full height of the sticky menu, which apparently is more than `@navbarHeight`
- [x] Replace the mobile nav's site name code with:
    - [x] if no "site logo" image: the site url or name, linking to the homepage
    - [x] if "site logo" image: the site logo image, linking to the homepage

Replacing the logo in the mobile nav has been a common request from members

**Comment by aschweigert** [comment]
Right, and most smaller orgs (and I say this with love) have crappy logos that don't work well at that size (and/or have no way to adapt them to work as a square that works as an icon like that). So definitely having more flexibility here would be nice.

**Comment by benlk** [comment]
There's a PR for this now at #460.
