### ISSUE TITLE
Largo prevents saving new default image widths

### ISSUE THREAD

**Issue by benlk** [INN/Largo#404]
Setting a custom image width in Dashboard > Settings > Media will not be respected by Largo. When using Largo, the values are set to their Largo defaults:

- Thumbnail: cropped to 140 x 140
- Medium: 336 x 9999
- Large: 771 x 9999

Changing to the Twenty Twelve theme shows the values that had been manually set.

Changing the values in [functions.php](https://github.com/INN/Largo/blob/master/functions.php#L56-L74) does not appear to affect the displayed values.

**Comment by aschweigert** [comment]
Yeah, that's intentional, of course but we should probably either hide those fields or somehow add a note that these are not the settings people are looking for.

**Comment by benlk** [comment]
Issue #404: bug not found.

We could hide that specific part of the settings with:

```php
function hide_media_options() {
  remove_menu_page( 'options-media.php' );        //Settings 
}
add_action( 'admin_menu', 'hide_media_options' );
```

**Comment by aschweigert** [comment]
right. I *think* that would be ok. anyone have any reservations re: going down that road? @rnagle?
