### ISSUE TITLE
Largo Recent Posts Widget output should be the same for different options

### ISSUE THREAD

**Issue by benlk** [INN/Largo#412]
Resolution: The widget outputs the same general structure no matter what options are chosen.

Changing the options in the widget settings can drastically affect what the widget looks like, because of CSS. Depending on the options chosen, the widget can output:

    ul
        li
            a Title
        li

or

    ul
        div
            h5 a Title
        div

or

    div
        div
            h5 a Title
        div

**Comment by willhaynes** [comment]
This should be fixed as of #444.

**Comment by willhaynes** [comment]
#444 merged in, closing this.
