### ISSUE TITLE
figure out where the INN logo goes

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#416]
All INN member sites are supposed to have the "member of INN" logo at the top of the site. It was previously in the global nav but now that many sites are global nav-less we should probably figure something out. Plus that one thing about the one thing.

**Comment by kaeti** [comment]
Could we put it in the footer?

**Comment by aschweigert** [comment]
Kevin would prefer it be in the header, and I agree (mostly) but I think it can be less obtrusive.

**Comment by kaeti** [comment]
It's hard to put another organization's logo in your header without being obtrusive, but I shall think about this.

**Comment by aschweigert** [comment]
I get it from the "make these feel like a network" perspective, even if it's somewhat loose. Also, a reminder to the members of the value they're getting from INN every time they look at their site, etc. so also that kind of thing.

**Comment by benlk** [comment]
Footer social icons can be done at the same time as this: https://github.com/INN/Largo/issues/463

**Comment by benlk** [comment]
The INN Logo has moved to the footer and been removed from the global nav in the header. Is this ok to close?
