### ISSUE TITLE
update all references to INN

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#425]
- [x] member stories widget (feed address, reference to INN)
- [x] footer (INN name and URL)
- [x] INN logo in the header for member sites
- [x] readme
- [x] header block in style.less/css
- [x] Probably just do a quick search through the repo to make sure we're not missing anything else

@kaeti will supply any image/logo files needed

Prefer "Institute for Nonprofit News" where it makes sense to write the full name out, "INN" is fine on second reference and anywhere space is limited.

http://inn.org (no www) is the preferred format for the URL

**Comment by kaeti** [comment]
![largobanner](https://cloud.githubusercontent.com/assets/884444/6605460/27d1f67c-c7fe-11e4-818a-10eb3f95e27b.png)

**Comment by kaeti** [comment]
Small note, it's "Institute for Nonprofit News" (no "the" unless needed in the course of a sentence).

**Comment by aschweigert** [comment]
fixed!

**Comment by benlk** [comment]
#428 has everthing except these: 

- [ ] Rebuild translation files
    - What's the accepted Spanish translation? `lang/es_ES.po`
- [ ] Does the mailing list address change from investigativenewsnetwork to inn in http://investigativenewsnetwork.us1.list-manage1.com/subscribe?u=81670c9d1b5fbeba1c29f2865&id=913028b23c to http://inn.us1.list-manage1.com/subscribe?u=81670c9d1b5fbeba1c29f2865&id=913028b23c in `inc/dashboard.php`?

**Comment by JoeyColeman** [comment]
A question: I have INN referenced in my site credits using the old name.
How long do we have to update to the new name?

Thanks,

Joey Coleman

**Comment by aschweigert** [comment]
@JoeyColeman not urgent, if you're using the latest version of largo (0.4) then you can just pull the latest down and it should take care of it. If you're using a previous version you might just want to wait until you update because you'd have to change it in a number of places.

**Comment by benlk** [comment]
- [mailing list address changed](https://github.com/INN/Largo/commit/f34a199c83581e2f00f4b54be8da6ef3e7018e17)
- [translation files updated](https://github.com/INN/Largo/commit/f97a586d653fd94d9d1c7134dd009b4fae9ec0f1)
- [instructions for rebuilding translation files](https://github.com/INN/Largo/commit/7bc98418283ab896c800e10acc43ab5b62e9a418)

I'm going to close this now.
