### ISSUE TITLE
update documentation re: header images

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#430]
We're getting a lot of questions re: how the header/banner images work in 0.4 since they no longer appear on all pages of the site. We should update the setup/checklist docs to reflect this.

We also need clearer guidelines on how to choose a "good" square image to use as the home link in the sticky nav on internal pages/mobile.

**Comment by meredithinn** [comment]
To be added:  a bit about where the image is used and also about the size needed for the sticky nav

**Comment by aschweigert** [comment]
Right, so what makes a "good" square image is one of the things we need to make sure to include here. In this case, the image is used in two places: 
- for the homepage, category/archive pages, and when a featured image is not set for a post then this image is used as the open graph/twitter card image when a story is shared via social
- it is used in the sticky header as the home icon

It needs to be clear to users that it needs to work at quite a small size 50x50 or 60x60 which means that it should NOT contain any text, probably not have any significant margin or padding, etc.

**Comment by meredithinn** [comment]
Pre-Launch document includes "good" square image guidance.  http://largo.readthedocs.org/users/prelaunchchecklist.html

**Comment by jackbrighton** [comment]
Docs have been update to clarify the points raised in this issue. Just to confirm, do the updates solve this issue?

**Comment by aschweigert** [comment]
#318 and #715 will likely further affect this so we'll probably need to give that stuff we just updated yet another read before this next release just to make sure the docs still match reality

**Comment by benlk** [comment]
This should include the nav options tab added in #1024.

**Comment by jackbrighton** [comment]
Docs have been updated to reflect all the images sizes needed, and to explain that they only display on home pages and not single pages and posts. I think this issue can be closed now.
