### ISSUE TITLE
Add some way to specify that minified CSS and JS be used

### ISSUE THREAD

**Issue by rnagle** [INN/Largo#432]
Maybe we should add a `LARGO_DEBUG` constant. When its value is `true`, the theme enqueues the unminified versions of all assets. Otherwsie, use the `*.min.js` and `*.min.css` files are used.

**Comment by benlk** [comment]
In Grunt, is there a way to get one task to run another task?

**Comment by benlk** [comment]
#646 merged, so closing this!
