### ISSUE TITLE
share buttons in sticky footer should respect hide/show theme options

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#434]
In the theme options for 0.3 we had an option to show/hide the various social sharing tools on article pages. These options are still present but they don't affect the display of the share icons in the sticky footer. This is confusing to users so we should either change/remove these options and/or make the sticky footer respect them.

**Comment by benlk** [comment]
Should this remove the "Email" button? It's already been removed in the social sharing tools at the top of the page.

**Comment by aschweigert** [comment]
Nope, keeping here is fine.

**Comment by benlk** [comment]
Should the email button be controlled by a toggle in the theme options? And if so, would it make better sense to split the options into two fields?

- Show post social buttons at the top of the article template
    - Facebook
    - Twitter
    - Print
    - Email? (Should this be returned to the post social buttons? It was previously removed for #389)
- Show post social buttons in the sticky footer
    - Facebook
    - Twitter
    - Email (Not currently controlled by a toggle)
    - Print? (Not currently in footer)

**Comment by aschweigert** [comment]
Probably make them separate options.

At the top of the article I would actually re-add email but using the same method as in the sticky footer (not sharethis).

I think "print" is fine at the top of the article, even though it's pretty superfluous, in my opinion. It should not be an option for the sticky footer though because there's just not enough real estate there and I'd rather keep it as clean and simple as we can.

**Comment by benlk** [comment]
Closed with #456, though we'll need to revisit the test for that.
