### ISSUE TITLE
ShareThis "share" not functioning

### ISSUE THREAD

**Issue by drywall** [INN/Largo#435]
In developing a new child theme for Largo, we've noticed that the "ShareThis" and "Email" buttons rendered by a call to `largo_post_social_links()` in a partial in our child don't seem to do anything. I can see that st_buttons.js is being loaded, but it's minified so a little challenging to troubleshoot... not seeing the console logging any errors on load, or on click of the elements in question.

Happy to provide URL example via a more private channel.

**Comment by aschweigert** [comment]
Yeah, we noticed this too. We're actually planning to remove it entirely now that the share tools have been moved to the sticky footer.

**Comment by aschweigert** [comment]
duplicates #389
