### ISSUE TITLE
Sticky nav uses custom image size not used anywhere else.

### ISSUE THREAD

**Issue by willhaynes** [INN/Largo#437]
We register a home-logo image size with dimensions of 50x50px that is only used in the sticky nav area.
We also register a 60x60 size used in various other places in the theme.

 - Do we need to keep both crops of every image, or could we use the 60px crop in the sticky nav?
 - Or, is it worth the time to create an "on the fly" crop function that would generate a 50x50px crop just for the image used in the sticky header the first time it's requested.

**Comment by aschweigert** [comment]
probably just use the 60x60

**Comment by willhaynes** [comment]
The sticky nav now uses 60x60, and the home-icon size is no longer generated.
