### ISSUE TITLE
on first activation of theme, article page is STILL not defaulting to the single column (new) one

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#438]
what is the deal with this?

**Comment by benlk** [comment]
1. Created a new largo umbrella single site
2. Ran `wp post generate` to get a bunch of default posts
3. Activated the Largo theme from umbrella, using the WordPress browser interface
4. Posts are using the single-column layout
5. Ran database update
6. Posts are using the two-column layout

So it's in inc/update.php, and why did we even have that line in the update functions.

https://github.com/INN/Largo/commit/644f3cc38dfdf0c1ca650aabd1aac83af1dc5bca removes the `of_set_option('single_template', 'classic');` that did it.

**Comment by rnagle** [comment]
So this means that anyone updating from pre-0.4 would automatically be using the new, single column layout?

**Comment by aschweigert** [comment]
There's a related ticket (#378) re: strongly encouraging people to use the single column layout so maybe it's fine to just force that change and then make it easy for them to switch back if they don't want it. In that case we might want to do slightly more to notify them re: what's been changed in the update (and how to change it back)

**Comment by benlk** [comment]
Yes, because v0.3 didn't set a `single_template` option in the theme options.

If we wanted to be especially sure about this, I can add `of_set_option('single_template', 'normal');` or something equivalent in `largo_force_settings_update`

**Comment by rnagle** [comment]
Cool. Just wanted to be clear before merging. I think this is correct behavior.

@benlk we might not have to force the setting if the default in the theme options configuration is single column template.

**Comment by benlk** [comment]
The default is single-column, but for a site that has updated to 0.4 and then reverted to 0.3,, we may want to force it.

**Comment by benlk** [comment]
Forced with https://github.com/INN/Largo/commit/dea086bfd632518a144b7466f59d6f21075912c1
