### ISSUE TITLE
audit all theme options

### ISSUE THREAD

**Issue by aschweigert** [INN/largo#440]
We need to go through all the theme options with fresh eyes and make sure everything is still relevant for > 0.4 as there has been some confusion about why certain things don't work as expected (or as they used to).

**Comment by aschweigert** [comment]
giving this one to our freshest set of eyes, @tothebeat :)

**Comment by meredithinn** [comment]
Under Appearance > Basic Settings > Single Post Options > Select the share icons to display on single posts > Share This checkbox remains and should be removed

**Comment by aschweigert** [comment]
@meredithinn If you're using 0.4+ it already has been removed...where are you still seeing it?

**Comment by meredithinn** [comment]
@aschweigert I believe it's specifically related to the instance you created for me.  I'm not clear about the process of how it might be updated from 0.4 to 0.4.1

**Comment by benlk** [comment]
Also: Make sure that all options are in the best places for them to be. Some options regarding layout may be under "Basic Options", or complementary settings to stuff in "Layout" may be hidden in "Advanced" (#968).

Related: https://github.com/INN/Largo/issues/683

**Comment by benlk** [comment]
A suggestion that came up during today's post-scrum meeting:

- [ ] Remove the [article utility buttons options](https://github.com/INN/Largo/blob/master/options.php#L51-L63) that separately disable Twitter/Facebook/email/print. #970 will add a filter on `largo_post_social_links` that can be used to the same effect, and removing the options will encourage a sane default while simplifying the user-facing options.

**Comment by rclations** [comment]
closing for now - we'll tackle this in .7 / .8
