### ISSUE TITLE
let's talk about the header

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#453]
We're getting a lot of questions about how header images work, why the sticky nav appears on some pages and not others, etc. and I think the fact that we've pushed that direction is less because it's the right thing to do for ALL sites and more just because it's what we built for the Wisconsin Watch site.

So...let's take a step back and think this through.

Some sites probably just want to use the header more as less as we had it in 0.3, a couple header images for different viewport sizes probably paired with some of the reworked navigation stuff we've built since then. This should be an option. Perhaps we still include an option to stick the nav when you scroll past a certain waypoint, article pages might only show it when you scroll up instead of keeping it visible all the time, etc. This feels to me like it should be the default, probably.

Other sites will follow the wisconsin model and have a more compact nav on internal pages and mobile but have the full header only on the homepage. This feels to me like a great option for many sites but it probably shouldn't be the default. I think. Maybe.

ok, your turn. @kaeti @rnagle @benlk @tothebeat

**Comment by benlk** [comment]
[This is the code that has to change to enable the display of the full header image on interior pages](https://github.com/INN/Largo/blob/master/inc/header-footer.php#L27-L30).

**Comment by aschweigert** [comment]
at this point i think we have the issues pretty well captured in other tickets. closing this one.
