### ISSUE TITLE
Document installation and use of Grunt for Largo development

### ISSUE THREAD

**Issue by tothebeat** [INN/Largo#454]
[Grunt](http://gruntjs.com/) is used to run a few different tasks within Largo and there is no documentation on how to install it. For example, [docs/readme.md](https://github.com/INN/Largo/blob/master/docs/readme.md#2-using-grunt-directly) explains how to use a grunt command to compile the RST docs into HTML.

@benlk explained to me that I needed to run `npm install` from the root of the Largo project folder, and after doing that I was able to use grunt for generating the documentation HTML. This instruction for `npm install` should appear somewhere and possible prerequisites for being able to use `npm`. 

The tasks that Grunt performs should also be documented. @benlk said this includes:

- recompiling the LESS to CSS
- minifying the CSS
- uglifying the JS

**Comment by benlk** [comment]
Partially closed with #1036, for installing NPM. Still needs docs on what our Grunt tasks are and what they do.

**Comment by benlk** [comment]
- [ ] list of grunt tasks
