### ISSUE TITLE
http vs. https issue in current url/open graph tags

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#462]
in header.php we get the current URL of the page using:

$current_url = (!empty($_SERVER['HTTPS'])) ? "https://".$_SERVER['SERVER_NAME'].$_SERVER['REQUEST_URI'] : "http://".$_SERVER['SERVER_NAME'].$_SERVER['REQUEST_URI'];

For the sites on WP Engine this has started ALWAYS returning the https version, even when the request is not made using https.

This problem mostly manifests itself in inc/open-graph.php which uses the $current_url for the og:url meta tag for certain page types. 

Facebook seems to choke on that if it's https in the og:tag but https is not supported for the page it requests when they crawl it. See, for example:

![unnamed](https://cloud.githubusercontent.com/assets/490703/6872856/73cad40a-d482-11e4-8f75-a00b06a06be2.png)

Thoughts on what we should do about this?

**Comment by rnagle** [comment]
I think we can use WordPress' built-in `is_ssl` to perform this check unless there's a reason we didn't do that to begin with.

**Comment by aschweigert** [comment]
oh right, I forgot about that. yeah, let's do that.
