### ISSUE TITLE
rework how social icons are displayed in the footer

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#463]
We generally like the way inn.org is doing them: in their own container, centered, instead of in the last widget area.

Let's rework the footer to make this the default.

Code for that is here for consolidation: https://bitbucket.org/projectlargo/inndev/src/2f0d8543b34968c2636f21571834df8b56ad3aa3/wp-content/themes/inn/?at=master

**Comment by benlk** [comment]
Closing this in favor of #761's social icons, as that ticket is more up-to-date. The social icons are already removed from the widget areas, and are now part of the boilerplate.
