### ISSUE TITLE
when byline override is used, posts should not display on regular author archive pages

### ISSUE THREAD

**Issue by aschweigert** [INN/largo#469]
If i'm logged in as a regular WordPress user and then create a post that uses the largo_byline_text meta field, the post will show that byline text on the front end as intended, but it will also show up on my author archive page (/author/my-username/). We should see if there's some way to filter out these posts so they are not displayed here.

**Comment by benlk** [comment]
#726 duplicates this; I'm closing this ticket because #726 has more information.
