### ISSUE TITLE
Add ability to toggle "read more" links on various templates

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#52]
In theme settings, add ability to turn "read more" links on and off independently for:

1) homepage top story
2) archive pages

We should probably also allow people to set the "read more" link anchor text.

**Comment by aschweigert** [comment]
I think "read more" links are a little silly for news sites. This is probably just a holdover from Argo that we should consider killing. Probably.

**Comment by kaeti** [comment]
Agreed, I don't think they're necessary. And bad from an SEO perspective.

**Comment by benlk** [comment]
Tying this in with #668.
