### ISSUE TITLE
Add PHP inline documentation to /inc/post-templates.php

### ISSUE THREAD

**Issue by tothebeat** [INN/largo#529]
Following up on issue #321 we need to have inline documentation in the form of PHP DocBlocks in `/inc/post-templates.php`. Please refer to the section in [our WordPress style guide on inline documentation](https://github.com/INN/docs/blob/master/style-guides/code/wordpress.md#inline-documentation) for specifics.

**Comment by benlk** [comment]
There's a lot of non-docblock function-documenting comments in this file. Those will need to be converted to docblocks.
