### ISSUE TITLE
Add PHP inline documentation to /inc/robots.php

### ISSUE THREAD

**Issue by tothebeat** [INN/Largo#531]
Following up on issue #321 we need to have inline documentation in the form of PHP DocBlocks in `/inc/robots.php`. Please refer to the section in [our WordPress style guide on inline documentation](https://github.com/INN/docs/blob/master/style-guides/code/wordpress.md#inline-documentation) for specifics.

**Comment by benlk** [comment]
We removed /inc/robots.php in https://github.com/INN/Largo/commit/ac24d65d898161ec1012882e28a724d5c048da5c for https://github.com/INN/Largo/issues/667
