### ISSUE TITLE
Add PHP inline documentation to /inc/sidebars.php

### ISSUE THREAD

**Issue by tothebeat** [INN/largo#532]
Following up on issue #321 we need to have inline documentation in the form of PHP DocBlocks in `/inc/sidebars.php`. Please refer to the section in [our WordPress style guide on inline documentation](https://github.com/INN/docs/blob/master/style-guides/code/wordpress.md#inline-documentation) for specifics.

**Comment by benlk** [comment]
When finally tackling this issue, there's some comments on `largo_is_sidebar_required` in branch RNS-168-twocolumn-page-span2, commit 9ab790e, in `inn/vms/rns/wp-content/themes/largo` on oyster.
