### ISSUE TITLE
Add PHP inline documentation to /inc/widgets/largo-sidebar-featured.php

### ISSUE THREAD

**Issue by tothebeat** [INN/Largo#572]
Following up on issue #321 we need to have inline documentation in the form of PHP DocBlocks in `/inc/widgets/largo-sidebar-featured.php`. Please refer to the section in [our WordPress style guide on inline documentation](https://github.com/INN/docs/blob/master/style-guides/code/wordpress.md#inline-documentation) for specifics.

**Comment by benlk** [comment]
We removed the "Largo Sidebar Featured" widget in #1294 for #897.
