### ISSUE TITLE
Add PHP inline documentation to /partials/author-bio-social-links.php

### ISSUE THREAD

**Issue by tothebeat** [INN/Largo#585]
Following up on issue #321 we need to have inline documentation in the form of PHP DocBlocks in `/partials/author-bio-social-links.php`. Please refer to the section in [our WordPress style guide on inline documentation](https://github.com/INN/docs/blob/master/style-guides/code/wordpress.md#inline-documentation) for specifics.

**Comment by benlk** [comment]
This looks okay now: https://github.com/INN/Largo/blob/v0.5.4/partials/author-bio-social-links.php
