### ISSUE TITLE
Add PHP inline documentation to /partials/largo-header.php

### ISSUE THREAD

**Issue by tothebeat** [INN/Largo#603]
Following up on issue #321 we need to have inline documentation in the form of PHP DocBlocks in `/partials/largo-header.php`. Please refer to the section in [our WordPress style guide on inline documentation](https://github.com/INN/docs/blob/master/style-guides/code/wordpress.md#inline-documentation) for specifics.

**Comment by dryanmedia** [comment]
In pull #908

**Comment by benlk** [comment]
Closing this issue because #908 was turned into #913, which was merged.
