### ISSUE TITLE
Author box widget has no save button

### ISSUE THREAD

**Issue by willhaynes** [INN/Largo#641]
I presume this is any box without its own set of options, but the author box has no save button for settings provided by Largo.

![image](https://cloud.githubusercontent.com/assets/3745345/7008155/920ce52c-dc55-11e4-90f1-18c4f10d8737.png)

You can still save the URL field by hitting enter and submitting the form, but not very intuitive.

**Comment by aschweigert** [comment]
Weird, is there a way to just always show it?

**Comment by benlk** [comment]
The save button only appears if there's a `form()` method on the widget class - but the `form()` can be empty and do nothing.
