### ISSUE TITLE
staff roster widget sometimes links to 404 pages

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#647]
In the staff roster widget, if a user is displayed that has no posts, their name is still a link to their author archive page but since there are no posts nothing is displayed.

We should either make their name not a link OR we should show their photo, bio, etc. on the author profile/archive page in the header and THEN say that no posts are found instead of that being all a user is shown.

An example of this behavior reported by current.org (see for example Julie Drizin's user in the homepage staff roster widget)

**Comment by aschweigert** [comment]
making this one high priority because current would really like to get a fix for this. cc: @rnagle

**Comment by willhaynes** [comment]
Staff roster widget no longer links if no posts exist.
