### ISSUE TITLE
Make YouTube video embeds responsive in post content

### ISSUE THREAD

**Issue by tothebeat** [INN/largo#663]
Currently, when a YouTube video is added to the body of a post through the Add Media button or using the `[embed]` shortcode, it inserts an `<iframe>` with a static width and height. This embed is not responsive, remaining that static width no matter the size of the viewport. I don't see any CSS styling that would be applied by Largo to the `<iframe>` element.

**Comment by aschweigert** [comment]
If it's wrapped in <div class="embed-container"> it will apply some styling to make the iframe responsive but this still isn't perfect. It would probably be a good idea to either make this automatic or add a tinymce button to insert media into the post, give users some options re: size and aspect ratio and then insert the correct markup for them in a way that WP/tinymce won't strip out of the post.

**Comment by tothebeat** [comment]
There is a way to make the YouTube `<iframe>` responsive by changing the width from the static number to "100%" (as detailed in [our KB article](http://confluence.inn.org/pages/viewpage.action?pageId=3178523)), but this tweak cannot be applied when using simply the `[embed]` shortcode or adding it through Add Media.

This can be achieved by getting the full embed code from the YouTube video page itself, via Share > Embed and copying the embed code.

![image](https://cloud.githubusercontent.com/assets/486230/7207501/84188194-e4ff-11e4-9eb0-207faf940300.png)

This can be pasted into the text view of the post and one can then change the width there to "100%".

**Comment by tothebeat** [comment]
@aschweigert That's good to know. [Here's the relevant section](https://github.com/INN/Largo/blob/6adc763fff38d04fa547d3c2cce6b87f3cb07b51/less/inc/wp-responsive-media.less#L50-L70) in our styles for the `embed-container` class.

I hesitate to make it automatic in case someone really wants to embed at a certain size always (seems unlikely, but I don't want to prescribe how Largo users are presenting their embedded content).

If we wanted to make it automatic for all embeds, we could modify the output of the `[embed]` shortcode to wrap the regular output in the `<div class="embed-container"></div>`. I'm actually not sure if shortcodes can be extended in this way.

Short of that, and perhaps less dangerous than overriding a core shortcode in WordPress, is adding a custom shortcode to do things our way and add that tinymce button as you suggested.

**Comment by benlk** [comment]
How do we want to proceed on this? I'd like to check if we can modify the default shortcode first, before trying to make our own shortcode.

**Comment by benlk** [comment]
This might be addressed in https://github.com/INN/largo/pull/1689
