### ISSUE TITLE
Modifying Google search (excluding content)

### ISSUE THREAD

**Issue by meredithinn** [INN/Largo#664]
Follow [Google's recommendations](https://support.google.com/customsearch/answer/2364585?hl=en) on labeling boilerplate content on a page so that it is ignored by the search index. Specifically, the content that should be ignored is:

- sidebar
- footer
- nav bars

This is related to an issue with searching reported by James Pound of [JJIE](http://jjie.org/) and [Youth Today](http://youthtoday.org/) in [this ticket](http://jira.inn.org/browse/YT-24):

Google is searching content it shouldn't (you can see this by searching in the google custom search bar). 
According to Google, there's a nocontent tag we should apply to parts of the page.
![customsearchresult](https://cloud.githubusercontent.com/assets/9658519/7238712/429ed324-e772-11e4-985d-c065e79a2efc.png)

https://support.google.com/customsearch/answer/2364585?hl=en

We need that tag (if possible) on everything underneath the a post's story, and on the widget bar. The widget bar should probably only be searched on the homepage.

The specific sections that have been giving incorrect search results are the Next Post and Previous Post buttons, More About,and In Case You Missed It section.

**Comment by tothebeat** [comment]
For example, when searching for "grassley" on JJIE, on the second page of search results is this article:

![image](https://cloud.githubusercontent.com/assets/486230/7240006/953e2f7a-e773-11e4-9892-136b75fb5747.png)
http://jjie.org/best-practices-address-community-gang-problems/

There are no actual instances of "grassley" in this page. It's likely that at the time the search index was built, the sidebar or footer contained a link to [this story](http://jjie.org/grassley-lists-juvenile-justice-as-a-top-priority/) with the excerpt as you can see in the search results.

**Comment by tothebeat** [comment]
Another example provided by James: when searching for "gately" on JJIE, in addition to actual articles by Gately there are also several non-article pages returned including the home page:

![image](https://cloud.githubusercontent.com/assets/486230/7258448/3beaee2c-e822-11e4-82a0-b3779f2c18ca.png)

* http://jjie.org/page/2/
* http://jjie.org/page/3/
* http://jjie.org/

Although not included in this example, other pages that are aggregations of posts would not make sense to include in the search results, including:

* category page
* tag page
* archive page

I'm not sure about the Series landing page, as there can be content in that separate from the articles belonging to the series, and that could make sense to search for.

**Comment by aschweigert** [comment]
Archive pages typically would appear in search results because you might be searching for the name of that category and series and want it to be returned. You also want Google to crawl the links on those pages so you wouldn't typically exclude them for that reason, also.

The only suggestion they made that I think we should implement is the nocontent tag on the sidebar and footer of the posts, the other SEO stuff in Largo is pretty well thought-through at this point and should remain as-is unless there's a really compelling reason to change it.

**Comment by aschweigert** [comment]
That's all to say that we should follow the best practices as outlined by Google and not go out of our way to do weird things just because Google returns odd results sometimes.

**Comment by tothebeat** [comment]
It's worth mentioning that these recommendations are all related only to Google _Custom_ Search, not regular Google search indexing. Adding "nocontent" to the home page or an archive page would only affect the Custom Search while those pages would still be available to and indexed by the regular Google crawler.

**Comment by aschweigert** [comment]
Right, which I think is good, we definitely wouldn't want to start adding noindex to certain pages/types unless we really think that through. Right now we only add noindex to date archive pages and then have a theme option available (under the advanced options) to also add noindex to other archive pages but that's typically not a thing most sites would want to do, imo.

**Comment by benlk** [comment]
https://github.com/INN/Largo/pull/743 is merged, so I'm closing this for now. We can reopen if the behavior doesn't change. I'm not sure how long it takes for Google to re-index the site.

**Comment by benlk** [comment]
Reopening because GCSE is indexing menu content and returning it in search results, per YT-24. That area was not excluded in #743.

- [ ] `<div class="sticky-nav-wrapper"`
- [ ] `<header id="site-header"`
- [ ] `<header class="print-header"`
