### ISSUE TITLE
Setting strip_tags to true in largo_excerpt removes the <a> from "Continue Reading"

### ISSUE THREAD

**Issue by benlk** [INN/Largo#668]
- [x] tests for largo_excerpt
- [x] remove the read more text and toggle functionality
- [x] leave behind the vars, for legacy reasons
- [ ] document in changelog

**Comment by rnagle** [comment]
Some of this is addressed in pull requests #759.

**Comment by rnagle** [comment]
Started a 0.5.1 changelog doc so we'll have this in the release notes. Closing.
