### ISSUE TITLE
consider modifying tinymce format dropdown to use the styles we actually recommend

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#670]
see: http://wordpress.stackexchange.com/questions/128931/tinymce-adding-css-to-format-dropdown

**Comment by aschweigert** [comment]
we should also probably try to remove "heading 1" from the dropdown because it should never be used within a story (reserved for the headline).

A smarter thing to do would be remove headings entirely and add sensical labels like "subheading" that people actually understand

**Comment by rclations** [comment]
Related: https://core.trac.wordpress.org/ticket/27159

It seems a consensus is growing around removing the Heading1 tag. Should we remove that for now, and save the rest for a larger discussion down the road about what we want to recommend?

**Comment by rclations** [comment]
took a first pass on this with removing the Heading 1

@aschweigert let me know how much you'd like to tackle in .5.5 and I can amend the PR accordingly

**Comment by aschweigert** [comment]
I'm ok with that PR as-is, eventually will want to put our heads together with @julia67 and figure out what specific styles/tags we want to support and then modify that dropdown accordingly.
