### ISSUE TITLE
class Largo_Related is a query monster and needs to use fewer resources

### ISSUE THREAD

**Issue by benlk** [INN/Largo#671]
The "Related Posts" widget query queries for posts in a list of post IDs. That list of post IDs is created by [`Largo_Related`](https://github.com/INN/Largo/blob/6adc763fff38d04fa547d3c2cce6b87f3cb07b51/inc/related-content.php#L397).

Largo_Related:

- [get the series on the post](https://github.com/INN/Largo/blob/6adc763fff38d04fa547d3c2cce6b87f3cb07b51/inc/related-content.php#L464): uses `get_the_terms`, which [does cache](https://core.trac.wordpress.org/browser/tags/4.2/src/wp-includes/category-template.php#L0) the post object.
- [For each series](https://github.com/INN/Largo/blob/6adc763fff38d04fa547d3c2cce6b87f3cb07b51/inc/related-content.php#L469) that the current post is in:
    - [query for the existence](https://github.com/INN/Largo/blob/6adc763fff38d04fa547d3c2cce6b87f3cb07b51/inc/related-content.php#L484-L488) of a `cftl-tax-landing` page. If there is:
        - get the `'post_order'` meta value from the taxonomy landing page and use that as an arg for the posts query. If there is no tax landing page, then it orders by date.
    - query for [infinite posts](https://github.com/INN/Largo/blob/6adc763fff38d04fa547d3c2cce6b87f3cb07b51/inc/related-content.php#L475) in the series, using the sort order.

If the series query returns fewer than the requested number of posts, it proceeds to query [infinite posts for each category the post is in](https://github.com/INN/Largo/blob/6adc763fff38d04fa547d3c2cce6b87f3cb07b51/inc/related-content.php#L537).

If there are still insufficient posts, it runs a query for recent posts by date, but fortunately not infinite posts. It only queries [one more post than the number of posts needed](https://github.com/INN/Largo/blob/6adc763fff38d04fa547d3c2cce6b87f3cb07b51/inc/related-content.php#L562-L564).

In order to add posts to the list of post ids that have been returned, the recent posts method [creates and advances over a Loop of the returned posts](https://github.com/INN/Largo/blob/6adc763fff38d04fa547d3c2cce6b87f3cb07b51/inc/related-content.php#L569-L572). This could probably be an array function instead of a Loop.

I mean, it's great at getting related posts, and it's actually pretty good about returning ones that are actually related. But it's also like a bulldozer: good for moving things around, but not good for moving furniture in your house to vacuum. Do we really need to query for infinite posts? 

----

Posted because I'm getting PHP out of memory errors with a related_posts widget on Vagrant with NPQ.

**Comment by aschweigert** [comment]
Yeah...i've been thinking about this recently too and talked with @rnagle a bit about it. I want to revisit how it's working and make sure the logic is correct. Then we definitely need to figure out how to cache things or do something the minimizes the impact of this thing because right now it's pretty ugly.

**Comment by benlk** [comment]
At the very least, we should be querying for the number of posts that are requested instead of infinite posts.

**Comment by benlk** [comment]
Does Largo use transients anywhere for caching? It sounds like it would be a good idea in many places (like the homepage functions), but especially here. http://www.wpbeginner.com/wp-tutorials/speed-up-your-wordpress-by-caching-custom-queries-using-transients-api/

**Comment by aschweigert** [comment]
Not that I can recall, although it's probably something we could/should do in some places
