### ISSUE TITLE
new way of loading css completely ignores the less/css styling set from the dashboard/theme options

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#675]
For example, on mtcir.org and investigatemidwest.org, both sites are using the default Largo styles after the update last week when they should be respecting the custom color schemes set in the Appearance > CSS variables ui from the dashboard. This is affecting several sites in production so we'll need to come up with a fix for this one quickly.

**Comment by benlk** [comment]
Merged a fix for this, it works on staging, so closing for now
