### ISSUE TITLE
recommended plugins nag alert box not dismissible, even by admins

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#679]
When we install largo the TGM Plugin Activation library adds a nag box to the dashboard asking people to install plugins. It has a link to dismiss the box but it seems that that link only works for super admins in a multisite install (users get a permissions error otherwise). This would be ok except why even show it to people who don't have permission to do anything with it (install plugins, dismiss the notice, etc.)

Also, re: the sites we host....why do we show this at all? they can't install plugins anyway...

**Comment by willhaynes** [comment]
See PR #740

**Comment by willhaynes** [comment]
Merged.
