### ISSUE TITLE
Fork lessphp and make it compatible with WP’s plugin requirements

### ISSUE THREAD

**Issue by rnagle** [INN/largo#684]
See my comment on #431:

> In the case of the lessphp lib, we'll generally have to modify any release to use WP_Filesystem instead of core PHP functions for accessing and modifying the filesystem, since this is a requirement if we want to submit the theme to WordPress. Since we've already modified the version we're currently using, let's stick with that for now. It's not too far out of date, anyway. Maybe we should consider creating a fork of the project, modifying it to meet all of WordPress' requirements for submitting themes and plugins to the directory.

So, let's create a fork that follows lessphp so we can have a WP compatible version and update the version we're using in Largo.

**Comment by rclations** [comment]
migrating to sass in milestone .8
