### ISSUE TITLE
404 page is lame

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#692]
C'mon, we're better than this.

**Comment by benlk** [comment]
We have the search box, which is good, but we should also put the stripped, escaped URL that was queried for on the page or in the search box, ready to go. That would assist users in finding their page faster.

**Comment by aschweigert** [comment]
also relevant, maybe: http://websistent.com/wordpress-custom-403-401-error-page/

**Comment by benlk** [comment]
And from discussion:

- Theme option for the 404 page text, allowing HTML, configurable by admins. Default text is empty, but some might want to use "We've recently updated our site, let us know if you find any broken links by emailing us!"
