### ISSUE TITLE
Document how to use the full-width template for embedding interactives

### ISSUE THREAD

**Issue by benlk** [INN/Largo#694]
Inspired by [this tweet](https://twitter.com/palewire/status/595706720061693952), [this thinkpiece](https://medium.com/@lindzcook/what-made-nyt-s-income-mobility-map-so-magical-ee91486c2d81), and  [the NYT "best area to grow up" story](http://www.nytimes.com/interactive/2015/05/03/upshot/the-best-and-worst-places-to-grow-up-how-your-area-compares.html?abt=0002&abg=1).

We should also cover what's allowed by WordPress, TinyMCE, and Largo as far as injecting styles and javascript through the post editor.

**Comment by aschweigert** [comment]
I just had a conversation with a member today about this as well, about what gets stripped by TinyMCE and when/why. I'm sure someone has written that up already but it wouldn't hurt for us to have it somewhere to reference easily. I do like the idea of having a really barebones template though that would be easy to throw a full page piece into, already include the parent code for pym.js, etc. and have some docs and standards for this, how and where to upload and host content that might be iframed in, how that process would work, what needs to be included within the iframe to make it responsive, etc.

**Comment by aschweigert** [comment]
@jackbrighton has this been addressed anywhere yet?

**Comment by jackbrighton** [comment]
Not really. I like the idea of having a barebones full-width template with pym.js enabled where people could embed large objects, but short of that we could:

- Provide guidance on using the existing full-widget along with the Pym Shortcode plugin.
- Include info (or an existing reference) on what kinds of code gets stripped out by WP/Largo/TinyMCE without using plugins.

Unless there are any objections I'll go ahead and write this.

**Comment by aschweigert** [comment]
go for it. we also want to make sure it's crystal clear that MOST of the time when someone thinks they want the full width template, they actually want the single column post template and explain why. That is, make it clear that the full-width template is really only for embedded, highly visual sort of things. The line-length is waaaaaay too long for regular text on that page and the single column template is a better choice for an article, generally.
