### ISSUE TITLE
Single Post bleeds full page in Firefox 

### ISSUE THREAD

**Issue by meredithinn** [INN/Largo#697]
Single post bleeds behind the sidebar in Firefox.  
![screen shot 2015-05-07 at 1 50 37 pm](https://cloud.githubusercontent.com/assets/9658519/7521981/1eb83f62-f4c0-11e4-9fdd-e60158908fb7.png)

**Comment by willhaynes** [comment]
@meredithinn is following up with the reporter, but it appears as if this is no longer an issue or was an issue with the child theme the reporting site was using.
