### ISSUE TITLE
Identify Largo default for quotes -- are they curly or straight, where is it set?

### ISSUE THREAD

**Issue by meredithinn** [INN/Largo#705]
Looks like wptexturize controls this function.  http://jakubmarian.com/wptexturize-smart-quotes-not-working-in-wordpress/

**Comment by aschweigert** [comment]
I'm not keen to mess with the default WP behavior unless someone can come up with a really compelling reason...

**Comment by meredithinn** [comment]
I am advocating for identifying expected behavior. A number of Largo sites display curly quotes.

**Comment by aschweigert** [comment]
We don't do anything to change it...so it's not clear to me where this behavior would come from (unless sites are doing something to change it)

**Comment by benlk** [comment]
Sites, or fonts.
