### ISSUE TITLE
Revise the contents of fordevelopers.rst

### ISSUE THREAD

**Issue by rnagle** [INN/largo#708]

**Comment by benlk** [comment]
- [ ] new TOC, see https://docs.google.com/document/d/1ukQ9b_7KKVvsyP_3oIubBuXBkjHPtpqX-yw5cUo7sk0/edit#
- [ ] pull tech notes out into separate file
- [ ] link to inc dir
- [ ] link to lib dir
- later: link to API notes
- link to image sizes doc
-  [ ] options framework docs
- [ ] link to largo homepage templates explanation
- [ ] revised contributing section
    - [ ] getting dev env set up
    - [ ] getting dev env for docs set up
    - [ ] pr docs

**Comment by rnagle** [comment]
Note: I moved `developers/fordevelopers.rst` to `developers/index.rst`.

**Comment by benlk** [comment]
We should also make a barebones, commands-only setup list for getting Largo set up, something that approaches a bash script in its emptiness.

**Comment by rclations** [comment]
this file doesn't exist, afaik

**Comment by benlk** [comment]
This issue references `developers/`, but should really be talking about `doc/developers/`: https://github.com/INN/largo/tree/master/docs/developers
