### ISSUE TITLE
Find a way to notify third party sites when a new version of the theme is available

### ISSUE THREAD

**Issue by aschweigert** [INN/largo#71]
See: http://wordpress.org/extend/plugins/theme-updater/ and http://www.disruptiveconversations.com/2012/02/how-to-auto-update-wordpress-custom-themes-using-github.html

**Comment by rclations** [comment]
Doesn't appear there is a solid lightweight option for this currently. We'll add the theme to wp.org as we get close to a 1.0 release. 

Closing for now
