### ISSUE TITLE
Should Doubleclick For Wordpress be mentioned and supported in the Largo docs? 

### ISSUE THREAD

**Issue by benlk** [INN/Largo#711]
The [Largo docs section on advertising](https://largo.readthedocs.org/en/write-the-docs/users/ads.html) is heavily centered on using Ad Codes Manager. Do we want to:

- keep the ACM docs only
- keep the ACM docs and add DFW
- replace the ACM docs entirely with DFW

?

**Comment by meredithinn** [comment]
Maybe linked to the advertising section? 
These exist:  https://github.com/INN/DoubleClick-for-WordPress/blob/master/docs/index.md

and 

http://dfw.readthedocs.org/en/latest/

**Comment by aschweigert** [comment]
replace entirely and remove ACM from the list of recommended plugins.

**Comment by benlk** [comment]
Added to the write-the-docs branch.
