### ISSUE TITLE
Make it easier to change nav visibility on mobile and desktop, on front page and internal pages

### ISSUE THREAD

**Issue by benlk** [INN/Largo#715]
See NPQ.

Currently, changing the behavior of the sticky nav requires copying over the entire largoCore.js, unstaging Largo's, and staging your own with only a few changed lines.

**Comment by aschweigert** [comment]
#318 and #453 touch on this, but yeah, we need a better solution here.

**Comment by benlk** [comment]
We could take the approach we've done with most of the other javascript bits, and put it in a separate file, like we do with pretty much [everything else in the `js/` subdirectory of Largo](https://github.com/INN/Largo/tree/master/js).

**Comment by aschweigert** [comment]
Given that a number of current sites we're working on would benefit from having this, we should definitely take this opportunity to figure out a better solution here instead of always falling back to "just don't show the sticky header" just because that's the easy way out.

**Comment by aschweigert** [comment]
for RNS-55

**Comment by aschweigert** [comment]
covered in #1024
