### ISSUE TITLE
Should docs include how to get to common WP admin locations?

### ISSUE THREAD

**Issue by benlk** [INN/Largo#718]
- Largo Theme Options
- Menu options
- Widget options
- Per-author settings

These are things that site admins will commonly do, and if they're not familiar with WordPress it would be helpful to them. However, we'd be duplicating some WordPress docs if we did this.

Does this sound like something we should write?

**Comment by meredithinn** [comment]
I would say this becomes relevant where Largo adds features/functionality that is not well documented in WordPress.  For example Menu options as they relate to series.

**Comment by aschweigert** [comment]
Possibly as some start of "quickstart guide" but I don't think we should do much more than link to relevant WP documentation for how to use those sections. The intent would be more "here are the places to look to find the most common settings you need to care about to get your site up and running"

**Comment by meredithinn** [comment]
I wonder where a quick start guide and the style guide intersect -- thinking about menus.

**Comment by aschweigert** [comment]
@meredithinn I think we're just talking about where to find them and basic setup here though, right? The style guide would be more for developers working on sites to outline the different navigation patterns that are a available from a design/dev standpoint, users (admins) would just need to know where to go in the dashboard to add/remove/change items in a given menu.

**Comment by meredithinn** [comment]
@aschweigert I am thinking that it might be helpful to link to some guidance in terms of building menus that make sense for users -- in addition to where to find the menu settings.

**Comment by aschweigert** [comment]
If we're talking about UX guidance (what to put in which menu areas, how many items to include, etc.) then that should go here: http://largo.readthedocs.org/users/menus.html

If we made a quickstart guide it should be very brief and easy to scan, probably a refinement of http://largo.readthedocs.org/users/download.html
