### ISSUE TITLE
The mailto link is malformed (%40 instead of @)

### ISSUE THREAD

**Issue by nickom** [INN/Largo#725]
The email address link for "Get in touch with us" on the [main docs page](https://largo.readthedocs.org/index.html) is "largo%40inn.org." I believe this is happening due to a markdown conversion issue:
![screen shot 2015-05-20 at 8 59 28 pm](https://cloud.githubusercontent.com/assets/3171982/7739672/33781f08-ff33-11e4-878e-1898fd94d01d.png)

How it looks in the code:
![screen shot 2015-05-20 at 9 00 49 pm](https://cloud.githubusercontent.com/assets/3171982/7739681/5105c246-ff33-11e4-9ade-a9254c9d8ba6.png)

**Comment by willhaynes** [comment]
Some (brief) internet research seems to suggest [there's not really a fix](https://groups.google.com/forum/#!topic/sphinx-users/1fLXNgtUNgI) for this in .rst.

Some more digging suggests that `%40` is [valid escaping for `@` in a mailto link](https://www.mail-archive.com/sphinx-dev@googlegroups.com/msg04535.html). But others mention [problems on iPads](http://community.sitepoint.com/t/problem-using-40-instead-of-in-mailto-link/33390) and maybe other places too.

Seems like more trouble than a "fancy" mailto: link is worth.

**Comment by benlk** [comment]
Based on Will's research, we have two options: 

1. Do nothing, and blame software vendors for not implementing mailto: links in accordance with the RFC.
2. Rewrite this to "Questions? Comments? Send us an email at nerds@inn.org" and let RST handle the link.

**Comment by aschweigert** [comment]
Option 2 is fine with me
