### ISSUE TITLE
Refine Largo mobile nav styles

### ISSUE THREAD

**Issue by benlk** [INN/Largo#732]
![image](https://cloud.githubusercontent.com/assets/1754187/7874400/0a8b2ca2-057d-11e5-8c42-bfad02a81233.png)
![image](https://cloud.githubusercontent.com/assets/1754187/7874402/1198ba8c-057d-11e5-88a5-616a93dca30e.png)

Images copied from NQ-86. Styles are in theme-npq.

**Comment by benlk** [comment]
- [ ] copy
- [ ] test all child themes
    - [ ] Is it possible to automate screenshot-generation?
        - this would require a reasonably up-to-date vagrant from production's database.

**Comment by aschweigert** [comment]
see #867 should this just be closed as a duplicate?

**Comment by benlk** [comment]
Yes, though #807 is the ticket that duplicated this.
