### ISSUE TITLE
remove fb and twitter buttons from author profiles

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#741]
FB and Twitter keep changing the padding inside of the iframes they provide for their like/follow buttons. Let's remove their buttons and just use static icons that link to the provided profile URL instead of loading these (bonus: remove their tracking scripts)
s
![screenshot](https://cloud.githubusercontent.com/assets/490703/7985228/4f9cb0de-0a9d-11e5-9578-6fb18f8bfba6.png)

**Comment by JoeyColeman** [comment]
I'm a big fan of this proposal as it removes tracking scripts.

**Comment by willhaynes** [comment]
Just to play devils advocate — I know not everyone does, but I use these buttons all the time to follow authors and subscribe to sites. I almost never find myself clicking on icons to profile pages.

Removing tracking scripts is not a bad reason, but probably not terribly realistic given other facebook/twitter widgets that a majority of our sites add anyways. Not to mention those [tracking scripts can offer benefits](https://developers.facebook.com/docs/marketing-api/custom-audience-website/faq/v2.3) back to sites.

**Comment by aschweigert** [comment]
I would say, to @JoeyColeman's point, that many sites want to limit tracking of their users without their consent so I'd argue that our default state should be to include as little of that stuff as possible (and maybe even provide some kind of statement re: the third-party tools we do include and our rationale for using them).

**Comment by dryanmedia** [comment]
List of sites with need of check:
- [ ] current (has pull)
- [ ] voice of oc (needs pull)
- [ ] invw (needs pull)

**Comment by dryanmedia** [comment]
Largo pull is in on #890.
