### ISSUE TITLE
make number of homepage stories filterable

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#742]
see: http://jira.inn.org/browse/HELPDESK-241

we should make it easier for sites to change the number of homepage featured posts from a child theme by adding filters for these values anywhere they are currently hard-coded.

**Comment by willhaynes** [comment]
This is done here: https://github.com/INN/Largo/pull/744

It might be worth considering creating a better way to subclass homepage templates and overriding default values. Seems like doing it all through filters could be a lot of filters.
