### ISSUE TITLE
Share via email from the Sticky Footer on mobile opens blank browser window

### ISSUE THREAD

**Issue by meredithinn** [INN/Largo#748]
Current.org reported that when you click on the email share icon on an article from a phone browser it opens a blank browser window.  I duplicated the issue on citylimits.org as well.

**Comment by aschweigert** [comment]
this is only in mobile safari on iOS, correct?

**Comment by meredithinn** [comment]
Yes, reported and confirmed in mobile safari on iOs.

**Comment by meredithinn** [comment]
Additional reported behavior, when using desktop Safari and launching an external email client, "it inserts plus signs instead of spaces into the headline and the excerpt. I.e., "Linda+Simensky,+PBS’s+head+of+children’s+programming,+on+carrying+forward+Mister+Rogers’+legacy."

**Comment by aschweigert** [comment]
covered in #799, closing as duplicate
