### ISSUE TITLE
Post Images: Featured?

### ISSUE THREAD

**Issue by vtnq** [INN/Largo#749]
I'm trying to understand how images work when displaying a single post. I add a featured post for the front page then a smaller image to accompany the individual post. However, once published, the individual post displays the full-size image, as well as the smaller image. How do I prevent the larger image appearing on single posts? (I want the larger image to display as the featured post on the front page, however.)

Here is a link to the post in question: http://www.vtinq.org/2015/06/15/sanders-latinos/

**Comment by meredithinn** [comment]
The Featured Media dialogue box controls how images are displayed for the post.  You can adjust which image is displayed on the single post by checking the box next to Override display of featured image for this post?  Your post will then display the smaller image you uploaded and feature the Featured Image on the front page.

**Comment by aschweigert** [comment]
This will be covered with #381, closing as duplicate
