### ISSUE TITLE
donate button is hidden on mobile

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#760]
and this is a terrible idea, let's do something about it!

**Comment by kaeti** [comment]
copying comment from MWE:

"I think I would first try to keep it visible in the header on smallest screen sizes.

If the spacing on that is weird, we could possibly try to get it into the hamburger menu.

Thinking more broadly, if we actually want people to give money, a link in the navigation isn't gonna do it."

I'll think through this and mock a couple things up.

**Comment by kaeti** [comment]
Initial thinking:

1. As a default, let's get the Donate link into the hamburger menus at smaller screen sizes so it doesn't disappear entirely from the menu

2. Let's make sure there is a donate menu item or button in the footer (will take care of that with footer ticket)

3. Rehabbing the Largo Donate widget to make it more flexible, and encourage sites that are seeking donations to use it on the homepage (and elsewhere)

**Comment by aschweigert** [comment]
re: the largo donate widget, what would "more flexible" mean in practice?

Seems like typically it's going to be some kind of CTA + a button in almost every situation (which is possible now, more or less, though the styling could be better). 

Anything else we'd want to consider adding?

**Comment by kaeti** [comment]
I was thinking mostly of style flexibility (so people could use in sidebars, banner across full/part width of the site a la Wisconsin Watch, possibly mid-story on article pages, etc.). But yes, text and button would still be the primary elements here.

**Comment by rnagle** [comment]
- Pull request #785 resolves #1 in @kaeti's comment above.
- #761 will address the issue of the donate link/button placement in the footer.
- The donate widget looks acceptable to me wherever it is placed in a vanilla Largo install. It might also be acceptable for use as the donate link/button in the footer since it can be placed in footer widget areas.
