### ISSUE TITLE
styles for hierarchical category pages don't make sense

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#766]
Observed on JJIE, for example: http://jjie.org/category/ideas-and-opinions/

the styles for the top area of these hierarchical category pages are inexplicably in the less file for the "top stories" homepage layout (https://github.com/INN/Largo/blob/master/homepages/assets/less/top-stories.less#L87)

Obviously this doesn't make sense.

Also, why is the background blue? Seems like the white background should just cover the primary/secondary featured area and any extraneous markup should be removed.

Further, why is the top stories homepage css being loaded on pages that are not the homepage?

**Comment by benlk** [comment]
Note: Adam says code for this is in https://github.com/INN/Largo/pull/729/files

**Comment by benlk** [comment]
@aschweigert For this, did you just want to remove the styles entirely, as in the stop-the-navsanity branch, or should they be moved someplace better, like `archives.less`? https://github.com/INN/Largo/pull/729/files#diff-d69039940eaa51136a1b4f1b472448caL87

I think we should keep the `margin-bottom`s on `.primary-featured-post` and `.secondary-featured-post`, but those are the only rules that are needed.

There does not appear to be any compelling reason for those classes to be in the homepage top top stories CSS.

**Comment by aschweigert** [comment]
leaving the bottom margin is fine but everything else should be removed. 

We'll want to check wisconsin watch to make sure the blue background and such still exist in their child theme before we deploy this update to that install (because that's where it originated). Should have never made it into the main Largo theme though.

**Comment by aschweigert** [comment]
see also this issue on midwest energy: http://jira.inn.org/browse/FE-147

generally the styles at intermediate sizes look pretty bad and we should either stack the stories sooner (and adjust the styles to make them more uniform) or maybe go from 4 stories across to two rows of two or something similar

**Comment by benlk** [comment]
We could move to a smaller font for those headlines, making them less crowded for long words. CSS hyphenation isn't yet usable, but we could also force overflowing words to break with `word-wrap: break-word;`.

**Comment by aschweigert** [comment]
smaller headline is probably fine as a quick fix. i think it would probably be best for them to eventually just match the format/style of the stories in the river below once it gets to a breakpoint where that makes sense

**Comment by aschweigert** [comment]
the hierarchical thing is kind of silly at the moment because afaik there's not really any way to control which stories appear in the featured area (or this feature is really poorly documented) so they're almost always just chronological anyway

**Comment by benlk** [comment]
Those top five are the five-most-recent posts in the category with the "Featured in Category" prominence term. Most users probably make everything "Featured in Category".

**Comment by aschweigert** [comment]
I think it's more likely that they don't use that prominence term at all
because it's not clear what it does (my hunch anyway)

*Adam Schweigert*

mobile: 812-219-2624

gtalk: aschweigert


http://adamschweigert.com

twitter: @aschweig <http://twitter.com/aschweig>

**Comment by benlk** [comment]
Ticket for documenting prominence terms: https://github.com/INN/Largo/issues/792
