### ISSUE TITLE
Improve explanations of theme images

### ISSUE THREAD

**Issue by benlk** [INN/Largo#774]
The Largo docs explain what images exist and what sizes they should be, but not what they're used for: https://largo.readthedocs.org/users/themeoptions.html?highlight=images#theme-images

- [x] explain where images are used
- [x] explain why images have the sizes they do
- [x] consider breaking Theme Options docs page up into several separate files; it's really long and hard to find things.

**Comment by jackbrighton** [comment]
Updated in https://github.com/INN/Largo/blob/master/docs/users/themeoptions.rst

Also much more detail added including screenshots in the Largo Guide for Users: https://github.com/INN/Largo-User-Guide

Including separate pages for each tab of the Theme Options settings in Largo. I considered breaking up the page in readthedocs, but kept it a single page for now. We'll need to better present the right docs for the right audience in the right places, and we'll get that done in the next phase of docs development.
