### ISSUE TITLE
Remove all the border-radiuses > 0

### ISSUE THREAD

**Issue by benlk** [INN/Largo#777]
Because we keep running into it in child theme customization, let's just make everything have square corners.

**Comment by aschweigert** [comment]
is this done? still seeing it on staging: http://raleighpublicrecord-org.largoproject.staging.wpengine.com/

**Comment by benlk** [comment]
- [ ] select boxes, even though these have `border-radius: 0`. right click > inspect element > computed > border-bottom-radius > magnifying glass > 0px. But it computes to 5px.
- [ ] the legacy top story layout (Isn't this deprecated?)

**Comment by aschweigert** [comment]
the top story layout is not deprecated

**Comment by benlk** [comment]
I got somehow got that impression around 0.4. Good to know!

**Comment by aschweigert** [comment]
the layout i'd like to lose eventually is the three column one, but the newspaper-like thing will live as long as newspaper people do, whether we like it or not.

**Comment by benlk** [comment]
Closing because:

- the twitter widget's border-radiuses are all within the iframe
- the select boxes are terrible to modify.
