### ISSUE TITLE
Document Largo's utility CSS classes available to authors

### ISSUE THREAD

**Issue by benlk** [INN/Largo#778]
These classes can be included in post markup for effect, and so should be included in the user/editor documentation.

- `.intro` used to increase the font size of a block of text, be it a `div` or a `p`

Are there other utility classes? We might have positional stuff for pull-quotes and images.

If these classes are added by pressing buttons, we should document the output HTML, because some people prefer to just copy and paste the HTML.

**Comment by aschweigert** [comment]
There's this http://largoproject.wpengine.com/2012/06/the-basics/?all=1 and a few other pages from the old project website. They're technically still there, I guess but should probably be moved to the docs and/or style guide

**Comment by jackbrighton** [comment]
Do we really need documentation for standard HTML elements like dl, ol, ul, abbr, etc?

I created a docs page in the Largo User Guide for the custom classes we're using, but didn't include standard tags: https://github.com/INN/Largo-User-Guide/blob/master/docs/style-guide.md

It's difficult at best to show these things using Markdown, and probably even more difficult with .rst. Best I could do is use screenshots, but it probably doesn't make sense to extend this much further.

**Comment by aschweigert** [comment]
Nope, just need the custom classes and I think the doc you have linked there pretty much covers it. I'd like to make sure we have this referenced somewhere in the largo docs though and in the knowledgebase, so let's do that and then we can call this closed.

**Comment by jackbrighton** [comment]
Added to the Knowledge Base: http://support.largoproject.org/support/solutions/articles/14000023561-i-want-to-apply-some-different-styles-to-the-text-in-my-post-how-can-i-do-that-

Also added some relevant links from the Largo Docs posting.rst page to the Largo User's Guide pages on post formatting and custom Largo style options.
