### ISSUE TITLE
Add backwards lookup to Largo_Related with 'before' date_query

### ISSUE THREAD

**Issue by benlk** [INN/Largo#782]
From HELPDESK-274:

> We should definitely not make the assumption that only a newer post in the category/tag/term would be a valid match before it falls through to just most recent. I'd say at least looking for one previous post in the category/tag/term would be the desired behavior.

Because:

> What I think was happening here was that the current post, at the time this ticket was created, was the most-recent post in its category and all its tags and all its series, so the widget fell back to pulling the most recent post from the site. This was the easiest way to solve the performance problems from the old behavior of the Largo Related Posts class, which used to fetch entire categories' worth of posts (and series) and work forward and backward from the current post to find related posts. (see https://github.com/INN/Largo/pull/680 and https://github.com/INN/Largo/pull/676 ) We stopped doing that because it was a massive memory hog, so now we only query for the N posts published after the post under consideration.

> We can query the N posts before the current post's date, with the 'before' argument for 'date_query' in WP_Query, but it's going to be a change in Largo and may cause performance issues. It won't be as bad as it was before, though, and it will prevent this problem. Do we want to make this change in Largo? The code change itself is pretty small, but we'll want to write tests for it.

- [x] Change
- [ ] Tests (see comments on #782)

**Comment by drywall** [comment]
Love to see how this related algorithm has evolved since my memory hog script — I probably would have just taken a lazy way out and stored the related results in a transient without actually fixing the memory issue. Nice work! (and happy to see it once again looking in both directions)

**Comment by aschweigert** [comment]
@drywall yeah, I thought about that a bit but the question is when to regenerate the results (when a new post is published in a series? category? only when the primary post is updated? "every once in a while"?) Totally stumped by that one. You'd definitely get a performance boost even with the slimmed down algorithm here by doing that but I'm not sure how best to tackle it.

**Comment by drywall** [comment]
I'd probably have defaulted to "every once in a while" (probably 15 minutes or so). Not saying that's the right approach — in fact probably the opposite — but if you need related posts recomputed more often than that, you're probably providing news in realtime and should therefore be using some sort of liveblog tool. My two cents, anyway. 

Really I just wanted to give you guys kudos. @aschweigert are you at Netroots? If no, any chance I'll see you tomorrow at WordCamp Columbus?

**Comment by aschweigert** [comment]
@drywall sorry, my inbox ate this message :( sorry I missed you, let me know next time you're back in town or vice versa!

**Comment by aschweigert** [comment]
this is ok to close, correct? @benlk?

**Comment by benlk** [comment]
It doesn't have tests yet, because that PR was a bit of a rush.

**Comment by benlk** [comment]
- [ ] Is Largo_Related's custom post ordering returning things in the correct order, or in the inverted order?

**Comment by benlk** [comment]
Leaving this open since #782 doesn't cover all the test cases in Largo_Related.

**Comment by aschweigert** [comment]
@benlk does #843 cover what still needs to be done here? if so I'd like to go ahead and close this ticket

**Comment by benlk** [comment]
#843 discusses two tests that were stubbed in #842:


- [ ] a series with a landing page forcing descending sort order, with featured posts
- [ ] a series with a landing page forcing ascending sort order, with featured posts

But it doesn't cover the remaining tests of this ticket:

- [ ] `Largo_Related::ids()` in the following conditions:
    - [ ] a tag
    - [ ] the current post matches posts in both categories and tags, with results drawn from both
    - [ ] no posts in the same series, categories, or tags, so only recent posts should be returned.
- [ ] `Largo_Related::cleanup_ids()`

**Comment by benlk** [comment]
So I guess the issue here is really test coverage in Largo_Related, and no longer about adding the backwards lookup. I'll create a new ticket for that, and close this.

**Comment by benlk** [comment]
#884
