### ISSUE TITLE
underline and text color selectors in TinyMCE don't do anything

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#790]
Should they?

Or is there some way for us to hide them to avoid confusing people?

**Comment by aschweigert** [comment]
see also #670

**Comment by benlk** [comment]
Do we know why they don't work?

There's a mismatch between styles in posts and in the editor because the `.entry-content` selector is not used in the TinyMCE iframe. RNS has a partial fix for this, but we should adopt it in Largo.

**Comment by rclations** [comment]
We have a function that [removes span tags](https://github.com/INN/Largo/blob/6a4eb174c54ddf3dcbf3c3aba36f7a1efc6d7b46/inc/editor.php#L71-L80), but the underline & color options rely on span tags

Do we need that function?

**Comment by benlk** [comment]
TIL that `<u>` is deprecated, and underlines are strongly discouraged: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/u

That function appears to tell TinyMCE to only remove span tags without classes; we could probably expand that to also not remove span tags with inline styles?

Useful docs: https://www.tinymce.com/docs/configure/content-filtering/#valid_elements

**Comment by rclations** [comment]
@benlk thanks for the resource on this - super helpful

**Comment by aschweigert** [comment]
yeah, i should say that i'm pretty opposed to allowing text color changes, but if the option is there it should at least work as intended. Hopefully WP does the sane thing and removes it in a future update.
