### ISSUE TITLE
Make sure all static assets have a version

### ISSUE THREAD

**Issue by rnagle** [INN/largo#797]
So that when we deploy new code users will be forced to download the new static assets (CSS, JS, etc).

**Comment by benlk** [comment]
And, if possible, this should affect child theme assets somehow.

There are probably two parts to this:

- Filtering enqueued assets to include a hash of the asset in the asset url
- Redirecting hashed urls to non-hashed files

**Comment by benlk** [comment]
As [Thomas Wilburn suggests](https://twitter.com/thomaswilburn/status/649604277338435588): Maybe a URL parameter is all that's needed.

WordPress tacks the version number onto all the assets anyways.

**Comment by benlk** [comment]
Resolved in https://github.com/INN/largo/pull/1575
