### ISSUE TITLE
email popup functionality/formatting

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#799]
Reported by Midwest Energy but I've heard similar complaints from other sites as well...

![unnamed](https://cloud.githubusercontent.com/assets/490703/8748651/f6bf4474-2c69-11e5-8104-4f482c637c2a.png)

So, when clicking on the "email" link in either the sticky footer, article social tools box or author profiles you get a popup window that is usually empty because (on macs anyway) Apple hijacks mailto links and tries to force you to use Apple mail (I'm sure you can change this, but this is the default). 

When the link gets hijacked the popup remains open and the formatting of the subject line and body of the email are weird (all words are + separated for some reason). We also pass a junk "TO:" address and could probably just leave this blank.

Let's take a closer look at this functionality in a number of contexts and see what we can do to improve it.

**Comment by aschweigert** [comment]
this may no longer be an issue?

**Comment by benlk** [comment]
We still pass the `friend@example.com` address, but everything else is properly escaped.

If your browser is set up use an external program to handle `mailto:` links, then those may be passed to the external program. My computer is configured to use Chrome to open them, and so all major browsers will pass the URL to Chrome, which opens Gmail.

The opened page has no actual content; it's essentially `about:blank` or `chrome://newtab`. I'm not sure if the parent page can close it or not; @rnagle might know better.

**Comment by benlk** [comment]
We may actually get around the new popup by doing away with the Javascript altogether, and using a plain `mailto:` link in the social button.

Such a change would need to be propagated across all the places we have a custom `largo_post_social_buttons` or equivalent, like MWEN's custom ones.

**Comment by aschweigert** [comment]
That seems like an ok solution to me, not sure why we'd need js here anyway...was that just a holdover from previous versions of the sharing tools (sticky footer, etc.)?

**Comment by benlk** [comment]
I'm not sure when we introduced it. It's definitely been around since 0.4, though.

**Comment by rclations** [comment]
- [X] Remove `friend@example.com` from the to: address
- [ ] Replace the `+` between words with spaces
- [ ] Move the `mailto:` link to plain old html instead of JS

**Comment by benlk** [comment]
The `mailto:` link work can probably be copied from https://github.com/nprds/editorial-wp-site/pull/8/files#diff-72b7bed1a6509fa97cf13808c32678aaR93
