### ISSUE TITLE
duplicate widget titles?

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#803]
Observed this on a site using 0.3 but I know I've run into it more recently on sites using 0.4+, let's make sure widgets are not outputting a title twice. This seems particularly to occur in the footer, for some reason (might just be these widgets).

<img width="391" alt="widgets" src="https://cloud.githubusercontent.com/assets/490703/8880170/aba3a980-3204-11e5-8764-9c1ef418c57a.png">

**Comment by aschweigert** [comment]
this seems to be an issue mostly with default WP widgets, it looks like they added some help text for accessibility that should probably just be visually hidden.

**Comment by benlk** [comment]
I'm going to hold off on committing this until #882 is merged (because of merge conflicts), but the LESS is:

```less
.widget_archive label,
.widget_categories label {
    .visuallyhidden
}
```
