### ISSUE TITLE
default widget styles are still terrible

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#805]
in looking at http://raleighpublicrecord-org.largoproject.staging.wpengine.com/ a couple of things

- [ ] we need some padding in widgets to open up the layout a bit. It was previous 20px or so and got removed in 0.4 but we need to add it back.
- [ ] the gray bottom border on widgets is probably not necessary and it causes issues in the homepage bottom widget area (when that layout is selected), probably just remove it and make sure the default bottom margin on widgets is consistent and generous enough to make them feel distinct
- [ ] widget title styles. something. just anything.

throwing this to @kaeti first for input but we need to look at this ASAP.

**Comment by aschweigert** [comment]
Also, why are widget in the homepage bottom area sans and the widgets in the sidebar not sans?

**Comment by aschweigert** [comment]
- [ ] setup a test instance of largo and put every widget in every possible context so we can review what the defaults look like
- [ ] look through all of the markup being generated, make sure it's consistent
- [ ] create rational default styles that are easy to modify/override in child themes

**Comment by aschweigert** [comment]
contexts to review:

- main sidebar
- footer
- homepage bottom
- article bottom
- homepage alert (less impt)

**Comment by aschweigert** [comment]
less/css for:

widgets
https://github.com/INN/Largo/blob/master/less/inc/widgets.less

author bio box
https://github.com/INN/Largo/blob/master/less/inc/author.less

**Comment by aschweigert** [comment]
we should probably also look at the link roundups widgets (and any other widgets commonly added by plugins?)

**Comment by kaeti** [comment]
so many widgets

**Comment by benlk** [comment]
Summary of August 31's hipchatting:

- [ ] header alert: lighter red background
- [ ] `.rev` needs gray background, not blue
- [ ] make type size and proportions consistent among various widgets: headlines and body text and bylines and teasers and
- [ ] remove styles on widget title in individual widgets so that all widgets have same headline styles

![about](https://s3.amazonaws.com/uploads.hipchat.com/93536/1159612/Liluhjn04Q0WxRK/Screen%20Shot%202015-08-31%20at%202.30.58%20PM.png)

![read next](https://s3.amazonaws.com/uploads.hipchat.com/93536/1159612/hcB4CUM1zCD6z0b/Screen%20Shot%202015-08-31%20at%202.30.29%20PM.png)

![Recent Posts](https://s3.amazonaws.com/uploads.hipchat.com/93536/1159612/dM9ulhKWuAVp2lV/Screen%20Shot%202015-08-31%20at%202.30.25%20PM.png)

- [ ] Helvetica Neue for text, Helvetica Neue Condensed for the titles
- [ ] try to remove font settings in `less/inc/widgets/` and in `widgets.less` so that they inherit form Largo based on the existing elements and classes

**Comment by dryanmedia** [comment]
Tasks
=============
* Setup vanilla Largo install and setup sidebar locations with widgets.
* Decruft, simplify and modularize the widget styles for vanilla.
    * No rules
    * No superfluous margin/padding beyond structure
    * Default typography
    * We are !important, don't need to say it.
    * Be discrete but leave wiggle room for overrides.
    * Identify which environments widgets are likely used in 
      (i.e. Author Box probably won't be in Homepage Alert)
* Test changes against all existing installs
    * Identify sites like Current with custom styles that will need love.
    * Test against our umbrella in the sidebar environments below.

Once these styles are complete there are a handful of related tasks we should handle:
* largo widget constructors are old and spit depreciation notices
* bring all widget slugs inline in the database (GH #894)
* document all the widgets (GH #847)

Widgets (21 widgets)
==============
* largo-about
* largo-author-bio
* largo-disclaimer-widget
* largo-donate
* largo-explore-related
* largo-facebook
* largo-featured
* largo-follow
* largo-footer-featured
* largo-image-widget
* largo-inn-rss
* largo-post-series-links
* largo-prev-next-post-links
* largo-recent-comments
* largo-recent-posts
* largo-related-posts
* largo-sidebar-featured
* largo-staff
* largo-tag-list
* largo-taxonomy-list
* largo-twitter

Sidebar Environments
* main sidebar
* footer
* homepage bottom
* article bottom
* homepage alert (less impt - @aschweigert)

**Comment by aschweigert** [comment]
One thing to keep in mind: some padding on widgets is a GOOD thing, but it's going to cause issues in certain contexts. We'll need to account for this either in the widget styles or in the broader layout styles somehow.

**Comment by aschweigert** [comment]
also check other common widgets added by plugins:

- DFP ad units
- mailchimp signup
- Popular posts (from the analytic bridge plugin)

**Comment by dryanmedia** [comment]
- [ ] Are there sites using these widget settings?
https://github.com/INN/Largo/blob/master/less/inc/widgets.less#L71-L94

- [ ] Identify styles from other less files that impact widgets
Responsive Widget Styles:
* https://github.com/INN/Largo/blob/master/less/inc/responsive-767px-max.less#L18-L19
* https://github.com/INN/Largo/blob/master/less/inc/responsive-768px-979px.less#L28-L29

Sidebar Widget Styles in Single.Less
* https://github.com/INN/Largo/blob/master/less/inc/single.less#L98-L114

Largo Disclaimer Widget?
* https://github.com/INN/Largo/blob/master/less/inc/single.less#L143-L147

Widget-Related Author Box in author.less
* https://github.com/INN/Largo/blob/master/less/inc/author.less#L85-L88

Footer.less widget styles
* https://github.com/INN/Largo/blob/master/less/inc/footer.less#L5-L7
* https://github.com/INN/Largo/blob/master/less/inc/footer.less#L61
* https://github.com/INN/Largo/blob/master/less/inc/footer.less#L61

Homepage.less
* https://github.com/INN/Largo/blob/master/less/inc/homepage.less#L30-L45
* https://github.com/INN/Largo/blob/master/less/inc/homepage.less#L30-L68

**Comment by benlk** [comment]
There are 0.5 sites using the no-background option. It's probably safe to assume that there are sites also using the reversed styles.

**Comment by dryanmedia** [comment]
@benlk I'm going to identify some of those this afternoon.

This document chronicles which child themes have custom widget styles (the vast majority). There is only one site I can recall with custom styles defined for the reversed widgets (JJIE), but its possible some are using the default reverse setting.
https://docs.google.com/document/d/1iu1WyV5V_vj8oUrHnGqCNm-1LLMMF1moFw9EpSAW7Uw/edit

**Comment by rnagle** [comment]
Closing this as #942 is merged to `develop`.
