### ISSUE TITLE
dropdown triggers in mobile nav are still not formatted correctly

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#807]
They should be the more minimal style from nonprofit quarterly. Any reason this still hasn't been incorporated?

**Comment by aschweigert** [comment]
see, for example: ![mobile-nav](https://cloud.githubusercontent.com/assets/490703/8963953/e74983de-35f0-11e5-93b4-2f8a6e3eb912.png) vs. what's live on NPQ

**Comment by benlk** [comment]
Styles for this are in NPQ's theme.

**Comment by aschweigert** [comment]
yeah, let's go ahead and get this merged into master unless there are any major concerns about what it might break on other sites.
