### ISSUE TITLE
Improve Series Landing Page documentation

### ISSUE THREAD

**Issue by benlk** [INN/Largo#816]
- [ ] revise https://largo.readthedocs.org/users/taxonomies.html#series to explain how to create a series, more than just what the options are. Needs flavor text.
    - Why do you want to create a series?
    - How can you present the series to readers? How can it be made discoverable?
    - What can't you do with a series?
    - Pitch series landing pages
- [ ] https://largo.readthedocs.org/users/landingpages.html needs to be:
    1. [create a series](https://largo.readthedocs.org/users/landingpages.html) of posts.
    2. Create the landing page:
        1. Title
        2. Slug
        3. Series
        4. Template
    3. Options!
        - and here, do more explaining of what the options are and how to achieve certain goals.
        - maybe have some children of this docs page showing examples, and what needs to be set to achieve those examples.

### Questions to answer:

This should grow into a "troubleshooting your SLP" document, and maybe some Largo tickets

- [ ] What if the slug isn't set?
- [ ] What if the series isn't set?
- [ ] Why does the disclaimer appear twice if it's in the plain text box and in the HTML box, but the HTML option is chosen?

**Comment by benlk** [comment]
If you have suggestions on how to improve series landing pages documentation, please leave a comment here.

**Comment by aschweigert** [comment]
see also: #637 and #780
