### ISSUE TITLE
Concatenation functions for front-end scripts and style

### ISSUE THREAD

**Issue by 0aveRyan** [INN/largo#817]
We concatenate Largo scripts and styles, but thinking more grand level whole "speed as a feature" thing.

Even a moderately light site like Current.org has a half dozen CSS files being HTTP'd and another few scripts. If a server is dealing with latency issues and has to return a dozen requests no amount of minification will speed things up.

Some existing plugins hack the wp_enqueue_script()/style functions to combine into a single file but these can break things.

Largo could contain largo_scripts() and largo_styles() functions that concatenate files, minify and then enqueue a single file (would want priority attribute at minimum). We'd have to write a small set of dequeue's for 3rd party plugins in each theme. However, we could bake in checks for Largo into our own plugins to use the special function.

**Comment by rclations** [comment]
Let's wait on this until we really have things cleaned up
