### ISSUE TITLE
update notice should not be displayed to people who can't do anything about it

### ISSUE THREAD

**Issue by aschweigert** [INN/largo#833]
on a multisite instance, the largo update notice is displayed to site administrators but when they go to perform the update they get a message that says "an error occurred" with no further explanation. probably because they need to be super admins.

**Comment by aschweigert** [comment]
this is fixed now right?

**Comment by rclations** [comment]
reopening

**Comment by rclations** [comment]
not sure if this is an issue or not, but lets review in case

**Comment by rclations** [comment]
looks like this is checking against `update_themes`, which seems appropriate to me
