### ISSUE TITLE
Largo Setup UX and Theme Options Plan (0.5.7)

### ISSUE THREAD

**Issue by 0aveRyan** [INN/largo#846]
### Status Quo

Largo is pretty powerful, developer or not. However, developer or not, there's a lot to configure in the Dashboard and unless you have intimate knowledge of Largo these can be a learning curve.
## 1. For Setup: Largo Sample Child Theme Generator

After reviewing the code powering the [Underscores.me Generator](https://github.com/Automattic/underscores.me/blob/master/plugins/underscoresme-generator/underscoresme-generator.php), it doesn't look unrealistic to modify it for Largo Sample Child Theme. However, we'd take it a step further to include Largo's Theme Options to set. 

Major Downside: Doesn't help users with existing themes.
## 2. For Activation: Welcome Page

Present a number of Panels in the Welcome Page. Currently data is written inline in Link Roundups beta of this, but might be prudent to store custom fields and content in JSON and Markdown files pulled from GitHub on a `documentation` branch.  We'd store data in set_transient()s when the pages are loaded and could have a toggle to go between a "cloud" mode that reset daily (and would delete from database if offline 24+ hours) and an "offline" mode to localize the files to a users' server with traditional set_option()s.

Benefits of storing data on GitHub: 
- Daily Updates (unties docs from releases, can improve between releases)
- No overhead on initial download and easy ability to take offline
- Encourages contributions
- Would allow us to "push" notifications
#### Mission Control Panel (custom HTML, built via JSON file stored on GitHub)

Clear direction i.e. "Start Here..." "Setup This Feature...", "More Resources", etc linking off to functionality in Dashboard or guides. These are the vital features and commonly needed guides. I could also see perhaps having a YouTube embed for a tour or tutorial. This would be JSON returned and parsed in WP.
#### Features Panel (Markdown render)

A simple GitHub markdown file with headers, images, emoji, etc, describing functionality. More secondary links than above panel. GitHub API will return rendered HTML of `.md` up to 1MB (yep, transient) and we can store images on repo all in branch to keep out of master.
#### Release Notes (Markdown render)

Pull Release Notes from Repository Tag. Rendered HTML of Markdown from GitHub API as above.
#### Contributors (already done)

[Code here!](https://github.com/INN/link-roundups/blob/welcome/inc/welcome/greetings.php#L165-L182) Automattic's use of GitHub API to return a repository's contributors, their photos, contribution count, etc. The cool thing is that the way the API is written, duplicating the functionality to do the panels above isn't _insane_.
## 3. For Learning: Largo University Panel

I think it'd be great to apply the same technique for GitHub API to the documentation to bring Markdown files into WordPress. We could even have placeholders like ADMIN_URL in the markdown to search and replace when they get ingested to WordPress so that instructions like "Click Options under the blah tab" could be hyperlinked for the users own install. Think storing on GitHub gives us the best of both worlds and places the choice in the users' hands.

Ideally this eventually houses screencasts, tutorials, perhaps interactive tours of Dashboard, etc.

**Comment by rclations** [comment]
good notes, but too far into the future for now
