### ISSUE TITLE
Improve docs for each widget

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#847]
http://largo.readthedocs.org/users/sidebarswidgets.html is pretty barebones, we should have a better reference for each widget re: what it does, the options available, recommendations for use, etc.

**Comment by benlk** [comment]
Should this have a separate file in the docs for each widget? That way there would be plenty of space for screenshots showing the different options for each widget.

**Comment by aschweigert** [comment]
still needed (copied from #1160):

- if we add the link roundups widget we should also add the saved links widget (added by the same plugin
- this should actually probably be a separate section including widgets added by commonly used plugins (link roundups, dfp, analytic bridge, etc.)
- we need to add a section re: the default WP widgets that we de-register (and maybe explain why), the list can be found in inc/widgets.php
- the taxonomy list widget will need updated docs when #1171 is merged

**Comment by aschweigert** [comment]
I'm also a +1 on eventually breaking these up into separate pages per widget

**Comment by aschweigert** [comment]
I agree on separate pages, and on adding screenshots. I thought maybe we update the one page first, then iterate on this. I haven't added images to .rst files, but it looks like getting everything right might be a bit of a process.

[--- Commented from Asana.com
#commenter Jack Brighton
---[aa]

**Comment by jackbrighton** [comment]
The section http://largo.readthedocs.io/users/sidebarswidgets.html#largo-recent-posts needs revision again since the update to the widget changed a few things in the settings.
