### ISSUE TITLE
Option to disable primary/secondary featured section on hierarchical taxonomy archives

### ISSUE THREAD

**Issue by benlk** [INN/Largo#860]
- [ ] create site-wide option to disable primary/secondary featured section on hierarchical (category, etc) archive pages 
- [ ] tests

----

On Category pages:

- if there are fewer than six posts, the bottom part of the page returns the 404 "None found" template.

<img width="1079" alt="screen shot 2015-08-19 at 2 28 44 pm" src="https://cloud.githubusercontent.com/assets/1754187/9365268/a17e910c-467e-11e5-8097-6405b49e5b9f.png">

- if there are fewer than 2 posts, the secondary content row is drawn but is empty

<img width="1079" alt="screen shot 2015-08-19 at 2 31 51 pm" src="https://cloud.githubusercontent.com/assets/1754187/9365360/1d1c7f9a-467f-11e5-9ba3-eb265e8f18bc.png">

- if there are no posts in a category, the category displays part of a byline instead of a 404 or similar.

<img width="1079" alt="screen shot 2015-08-19 at 2 39 07 pm" src="https://cloud.githubusercontent.com/assets/1754187/9365547/26c07a8c-4680-11e5-8ee6-f95cae4d218c.png">

Related: YT-58

## Questions:

- should posts be put in the river area if there are not enough posts to completely fill the top story area?

**Comment by aschweigert** [comment]
The hierarchical category pages are nice for some sites, but (and I believe there is another ticket for this somewhere) some sites may want to just show the river and not use the primary/secondary featured section at the top. We should at least make this an option.

**Comment by benlk** [comment]
There's #746 to make a "None" option for sidebars, making the content well centered, but I'm not seeing a ticket for not using the primary/secondary featured section. 

Is this an option that should be site-wide or per-hierarchical-taxonomy?

**Comment by aschweigert** [comment]
It's more likely to be a sitewide setting, i think

**Comment by benlk** [comment]
> if there are fewer than 2 posts, the secondary content row is drawn but is empty 

See #869 for solution

**Comment by benlk** [comment]
> create site-wide option to disable primary/secondary featured section on hierarchical (category, etc) archive pages

This conditional will have to affect largo_category_archive_posts, which runs during `pre_get_posts`: https://github.com/INN/Largo/blob/4f2890bcc08f6516f5df2dd24bc5220e9c5aa613/inc/taxonomies.php#L301-L315

Make sure that it doesn't set the featured post ids in `post__not_in`.

**Comment by benlk** [comment]
Closing because #872 is merged and deployed in master.

**Comment by benlk** [comment]
Creating a new issue for the issue where "Not Found" is still displayed if a fewer than 6 posts are found and the featured header is not disabled.
