### ISSUE TITLE
LMP on category archive page uses different partial than category.php

### ISSUE THREAD

**Issue by benlk** [INN/Largo#868]
[In category.php](https://github.com/INN/Largo/blob/master/category.php#L63):

			while ( have_posts() ) {
				the_post();
				//$shown_ids[] = get_the_ID();
				get_template_part( 'partials/content', 'archive' );
			}

[In inc/ajax-functions.php, in `largo_load_more_posts`](https://github.com/INN/Largo/blob/master/inc/ajax-functions.php#L109-L115):

			while ( $query->have_posts() ) : $query->the_post();
				$partial = 'home';
				if($_POST['is_series_landing'] === true || $_POST['is_series_landing'] === 1) {
					$partial = 'series';
					$opt = $_POST['opt'];
				}
				$partial = ( get_post_type() == 'argolinks' ) ? 'argolinks' : $partial;
				get_template_part( 'partials/content', $partial );
			endwhile;

The category archive page uses partials/content-archive.php and LMP uses partials/content-home.php on category pages. This is okay *in Largo* because neither partial exists *in Largo*, and so it falls back to partials/content.php in both cases.

But if a child theme defines either of those, then there will be markup mismatch between the posts included in the initial page load and in the posts loaded with the LMP button.

- [ ] change LMP to check for category, use 'category' as $partial.

**Comment by benlk** [comment]
Rough code, to be inserted before the `is_series_landing` check:

     $query = (array) json_decode(stripslashes($_POST['query']));
     if ( isset($query['guest_column']) && $query['guest_column'] != '' ) {
          $partial = 'category';
     }

(Because of Catalyst Chicago and HELPDESK-337)

**Comment by benlk** [comment]
Any fix here should also check tag, search, date, author, and non-landing-page series archives.

**Comment by benlk** [comment]
Here's a list of partials slugs used in Largo and in child themes, based on the files present in the themes. 

One column is reserved for if the partial needs to be considered in this issue.

| partial | largo | child | this ticket | comment |
| :-- | --: | --: | --: | :-- |
| '' | x | x | |
| not-found | x | x | |
| page | x | x | |
| single | x | x | |
| single-classic | x | x | |
| tiny | x | x | | largo only uses for Largo Series Posts widget
| archive | | x | x |
| argolinks | | x | x |
| category | | x | x |
| category-no-title | | x | |
| fathom-list | | x | |
| fathom-load-more | | x | |
| fathom-main | | x | |
| fathom-rail | | x | |
| home-left | | x | |
| home-right | x | | |
| member | | x | |
| no-title | | x | |
| product | | x | |
| quote | | x | |
| school | | x | |
| search | | x | x |
| search-other | | x | |
| series | | x | x |
| squandered-heritage | | x | |
| video | | x | |
| whoyakidding | | x | |
| widget | | x | |

**Comment by aschweigert** [comment]
minor note: the argolinks partial should no longer be needed

**Comment by benlk** [comment]
Continued in #1021 for #1020.
