### ISSUE TITLE
INN logo in site footer on light backgrounds?

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#871]
the new INN logo we added to the footer has the name in white so it doesn't work if the footer bg is also white (see, for example: http://aspenjournalism-org.largoproject.staging.wpengine.com/). The quick fix here is probably to just use a color (light gray?) that works on both dark and light backgrounds. @kaeti does that work for you?

**Comment by kaeti** [comment]
I would prefer that we use the black-text version of the logo for light backgrounds, and reverse text for darker backgrounds. Can we build in that option?

**Comment by aschweigert** [comment]
Yeah, the problem is that we let people change the footer bg color and we don't necessarily have any way to tell whether it's "dark" or "light" (that I can think of anyway)

**Comment by kaeti** [comment]
Can we let them choose which logo version appears? Then sites can adjust via admin depending what their footer color is.

**Comment by aschweigert** [comment]
thinking.

**Comment by dryanmedia** [comment]
We could use [this library](https://github.com/jamiebrittain/colourBrightness.js) to auto-detect light/dark and have it set try to set an option for light vs. dark that user could override if it was dumb?

Or we can expect most are one color, use that as a default and have an override for a developer? Could use a constant (expensive) or something else more nimble.

**Comment by aschweigert** [comment]
including another library feels heavy-handed here.

I did write this LESS mixin a long time ago: https://github.com/INN/Largo/blob/master/less/inc/mixins.less#L609

but that general idea might work to make it possible to switch between two images, except they would probably need to be bg images instead of included inline. 

This might be more trouble than it's worth if we can get away with any sort of compromise that would work on both light and dark backgrounds so I'd like to at least consider that as an option and maybe revisit this later.

**Comment by kaeti** [comment]
Wouldn't we run into the same problem if we try to do a grayscale logo (clients using a background color or gray that has low contrast with the image)? 

Can we just make everyone use a dark gray footer? (kidding, sort of) Or at least make the very bottom portion (credit area) a dark gray.

**Comment by aschweigert** [comment]
I'd be fine with forcing a standard color for the footer since that used to be the default, but at this point we have so many clients with different colors there that I honestly don't know if people would have a problem with it. We'd also need to be able to defend the design decision if we get pushback. But assuming we can do that I'm fine with it. It would be all or nothing though (at least the way the footer is currently constructed) because the bg color is applied to the entire thing and then the other two divs (with the widgets and then the boilerplate stuff) are contained within that so that they can be centered.

Re: choosing grayscale over black/white...it's definitely more flexible. It's still not perfect and there will be situations where someone could select a footer color that would not provide enough contrast. But that's also true if we had black/white as options (somehow, still not really clear on how we'd do that in an elegant way). I don't know, that just occurred to me as the easiest compromise that would work in the largest number of situations.

**Comment by kaeti** [comment]
![inn_logo_gray](https://cloud.githubusercontent.com/assets/884444/9507074/5a9de010-4c11-11e5-8f77-11c64f687bc6.png)

**Comment by aschweigert** [comment]
![untitled 3](https://cloud.githubusercontent.com/assets/490703/9507299/45e821e4-4c1b-11e5-8a28-e97ce53df941.png)
![untitled 2](https://cloud.githubusercontent.com/assets/490703/9507301/45ecc942-4c1b-11e5-8cad-05abdc79c0c3.png)
![untitled](https://cloud.githubusercontent.com/assets/490703/9507300/45e93c96-4c1b-11e5-96e8-194e044ca0ac.png)
![untitled 4](https://cloud.githubusercontent.com/assets/490703/9507305/4e64e762-4c1b-11e5-96a8-8d36132b7362.png)

**Comment by aschweigert** [comment]
a few screenshots, it's not ideal...but probably ok for now. I do think we should probably make a ticket to figure out a more ideal solution at some point. this seems to address the immediate issue though, right?

**Comment by benlk** [comment]
Largo includes the black-text logo, and the `inn_logo` function is pluggable for this purpose:

``` php
// Using the dark-text INN logo
function inn_logo() {
	?>
		<a href="//inn.org/" id="inn-logo-container">
			<img id="inn-logo" src="<?php echo(get_template_directory_uri() . "/img/inn_logo_blue_final.png"); ?>" alt="<?php printf(__("%s is a member of the Institute for Nonprofit News", "largo"), get_bloginfo('name')); ?>" />
		</a>
	<?php
}
```

**Comment by aschweigert** [comment]
Let's stick with the gray one for now and revisit at a later date, good to know that's another possibility though. I do think we should probably make the credit text below the logo the same shade of gray, consistently, including links. So, @dryanmedia, can you make that change (add the grayscale logo, update the default text/link color for that credit line) and then submit a PR? thanks.

**Comment by dryanmedia** [comment]
just saw this, i'll submit a pull by 5 PM PT today

**Comment by dryanmedia** [comment]
perhaps earlier.. i have a 15 minute break in this three hour class :smile_cat:

**Comment by dryanmedia** [comment]
In pull #879
