### ISSUE TITLE
Add button for "Recommend Plugins," no automatic tgm-activation

### ISSUE THREAD

**Issue by 0aveRyan** [INN/largo#874]
Rather than completely _gut_ tgm-plugin-activation, lets just not have it activated by default because it's annoying to most users (namely us).

We can have it triggered by a "Recommend Plugins" button in options panel and on welcome page under "good for beginners." Used right it's a decent, lightweight drop-in that's helpful for guiding a subset of users.

**Comment by aschweigert** [comment]
I want to be very careful about the language we use though..."recommended" is probably too strong. We want to help people find things they need that might be helpful but we also don't want to create a situation where people think they need to install ALL of the plugins nor do we want to necessarily be seen as endorsing any plugins we haven't written/reviewed very carefully.

**Comment by benlk** [comment]
"suggested", perhaps? "Plugins that other members have found helpful" is a bit of a mouthful.

If it's on the welcome page, there could be a little blurb for why we recommend/suggest/are talking about/* the plugin, instead of just a link in a list.

**Comment by aschweigert** [comment]
I'd only really be comfortable with "suggested" if we've thoroughly reviewed the plugin and can honestly say that we would recommend it, it's 100% compatible with Largo, is well-maintained, etc.

**Comment by rclations** [comment]
resolved by #1440
