### ISSUE TITLE
Remove Largo Sidebar/Footer Featured Posts widgets

### ISSUE THREAD

**Issue by benlk** [INN/Largo#881]
The Largo Sidebar Featured Posts and Largo Footer Featured Posts widgets have been deprecated at least since 05, and possibly since 0.4. They're slated to be replaced by Largo Featured Posts widget, which pays attention to where it's placed.

- [x] migration plan (Probably `inc/updates.php`
- [x] tests
- [ ] backup production before running migrations with the version containing this update

**Comment by aschweigert** [comment]
yep, if we can figure out a migration plan we should definitely toast these

**Comment by benlk** [comment]
Progress in this branch is in https://github.com/INN/Largo/tree/881-migrate-featured-widgets

**Comment by benlk** [comment]
Now that we have the migration functions set, we should wait a version to make sure that everyone gets migrated, and then remove the files. Once the files are gone, Wordpress will unregister those widgets on the first page load.
