### ISSUE TITLE
If the RSS feed is bad, the INN Member Stories widget breaks the site

### ISSUE THREAD

**Issue by benlk** [INN/largo#893]
If http://feeds.feedburner.com/INNMemberInvestigations is not a parseable URL, (fetched in [line 20 of the widget](https://github.com/INN/Largo/blob/master/inc/widgets/largo-inn-rss.php#L20), then the following error occurs and causes the page to stop rendering. This breaks the page.

```
[Tue Sep 08 12:30:04 2015] [error] [client 192.168.33.1] PHP Fatal error:  Call to undefined method WP_Error::get_items() in /vagrant/wp-content/themes/largo-dev/inc/widgets/largo-inn-rss.php on line 72
```

A fix for this would:
- [ ] check to see that the RSS feed loads successfully before trying to parse it
- [ ] if it fails to load successfully, display an error message of some sort.

**Comment by rclations** [comment]
moving to inn members plugin repo, as I've already removed the underlying code for this from largo 🎉

**Comment by benlk** [comment]
Reopening this because the code hasn't been removed from the released Largo versions.

**Comment by benlk** [comment]
Closing in favor of #1511, which will remove the widget. The widget and the RSS feed it depends on are deprecated.
