### ISSUE TITLE
largo follow widget should not load interactive fb/twitter buttons

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#901]
but it still does

**Comment by rnagle** [comment]
@aschweigert The Largo Follow Widget does not load any external JS/CSS anymore. See:

![image](https://cloud.githubusercontent.com/assets/72608/10742100/5da235be-7bf9-11e5-9ce6-19738805d717.png)

The share toolbar area of single posts, does:

![image](https://cloud.githubusercontent.com/assets/72608/10742124/81624444-7bf9-11e5-9dec-19959ae31624.png)

I am guessing this ticket is about removing the dynamic buttons from the single post template(s) but want to verify before I go ahead and scrap them. Let me know.

**Comment by aschweigert** [comment]
Correct, no interactive buttons anywhere and the scripts should be completely removed.

**Comment by aschweigert** [comment]
That is, we should use the icons and only fire off those scripts if a user actually interacts with them.
