### ISSUE TITLE
Remove partials/content-argolinks.php

### ISSUE THREAD

**Issue by benlk** [INN/Largo#926]
As said in #868, argolinks isn't needed anymore, on account of the plugin having become Link Roundups.

- [ ] Close #586 with this ticket
- [ ] remove the argolinks condition from inc/ajax-functions.php
- [ ] remove  partials/content-argolinks.php
- [ ] search for other references to argolinks and consider removing them.

**Comment by aschweigert** [comment]
On the 4th point, any references you've seen that we need to review? otherwise let's go ahead with this.

**Comment by benlk** [comment]
Some stuff in the search so it uses the argolinks partial: https://github.com/INN/Largo/blob/master/search.php#L75-L79

And some editor styles that can be removed

**Comment by benlk** [comment]
When working on this issue, search the whole of the codebase for `#926`. There are quite a few comments on code that should be removed in this ticket.

**Comment by benlk** [comment]
At the same time, improve support for the link roundups plugin:

- add archive-rounduplink.php https://bitbucket.org/projectlargo/theme-aspen/src/9ebb7394e2f67e64eb9ef70e329ac44b61639ebc/archive-rounduplink.php?at=master&fileviewer=file-view-default
- add partials/content-rounduplink.php https://bitbucket.org/projectlargo/theme-aspen/src/9ebb7394e2f67e64eb9ef70e329ac44b61639ebc/partials/content-rounduplink.php?at=master&fileviewer=file-view-default
- add these two filters to the LMP functions iff the link roundups plugin is active: https://bitbucket.org/projectlargo/theme-aspen/src/9ebb7394e2f67e64eb9ef70e329ac44b61639ebc/functions.php?at=master&fileviewer=file-view-default#functions.php-39:64

**Comment by benlk** [comment]
Moving to 0.5.5 for http://jira.inn.org/browse/WE-90

**Comment by benlk** [comment]
Do we not want to do this for 0.5.5?

**Comment by aschweigert** [comment]
still todo:

inc/ajax-functions.php:195:             // argolinks post type
inc/ajax-functions.php:196:             $partial = ( get_post_type() == 'argolinks' ) ? 'argolinks' : $partial;
inc/post-templates.php:288:     if ( $post_type == 'argolinks' ) {
inc/post-templates.php:289:             $partial = 'argolinks';
tests/inc/test-ajax-functions.php:66:           // @todo find way to test get_post_type() returning argolinks.
tests/inc/test-ajax-functions.php:115:          // @todo find way to test get_post_type() returning argolinks.
