### ISSUE TITLE
Add option to show series thumbnails on Largo Taxonomy List widget

### ISSUE THREAD

**Issue by benlk** [INN/Largo#927]
- [x] show thumbnail if series has a landing page and the landing page has a featured image
- [x] show thumbnail if series has no landing page, but the most-recent post in the series has a featured image
- [x] thumbnails for categories, tags, and generic other taxonomies
- [x] limit number of series shown to `n` series, sorted by most-recently-updated? This list will be _long_ otherwise.
- [x] text box for series to include on top, in order, and then the rest gets filled to `n` with the most-recently-updated.
- [x] option to show latest headline
- [ ] ~~text box for series to exclude?~~
- [x] CSS to ensure that the li doesn't have bullets. `li {list-style: none;}`
- [x] CSS for images so they are `{max-width: 60px; max-height: 60px;}`
- [x] tests

For [WE-15](http://jira.inn.org/browse/WE-15)

**Comment by benlk** [comment]
This will remove the widget_categories_args filter in the Largo Taxonomy List widget. It's not used in any of our child themes, but it's a good thing to note. The equivalent functionality can be found by using the widget settings, I think.

**Comment by aschweigert** [comment]
Hm...do we know why that was added originally?

**Comment by benlk** [comment]
It's the default setup in Wordpress' categories list widget, and a lot of this code looks like it was copied from there with allowances made for non-category taxonomies.

**Comment by aschweigert** [comment]
ah, ok, should be ok then

**Comment by benlk** [comment]
In the half-likely case that a category/series/tag/prominence/taxonomy has neither a featured image for the series landing page or for the first 5 posts in the taxonomy, is it okay to display no thumbnail? The other options are:

- display a generic thumbnail (From where?)
- display an `img` with no `src`, a dead and blank image

**Comment by aschweigert** [comment]
I would go with no thumbnail over a generic one

**Comment by aschweigert** [comment]
ok to close?

**Comment by benlk** [comment]
Yes, because #977 is its own issue.
