### ISSUE TITLE
Add featured image option to taxonomy terms

### ISSUE THREAD

**Issue by benlk** [INN/Largo#928]
For example, a series, category, or tag could have a featured image, which would show up in the archive pages and in tax term list widgets.

~~Something that might be useful to add here would be a "Edit this term" link that appears to logged-in users on term archive pages, so they don't have to dig through the all-term listing to find the term to edit the image.~~ WordPress already has this.

**Comment by benlk** [comment]
This should also add support to the tax list widget, as part of https://github.com/INN/Largo/issues/977.

**Comment by aschweigert** [comment]
for RNS-60

**Comment by benlk** [comment]
Wordpress 4.4 will (tomorrow) bring a whole lot of new functionality regarding term meta, which would be really nice ot use here: https://make.wordpress.org/core/2015/10/23/4-4-taxonomy-roundup/

But then we lose support for WordPress 4.2 and 4.3, which we still support.

**Comment by benlk** [comment]
- [x] Add the button
- [ ] display image from button once image is uploaded, in the new-term form and the edit-term form
- [ ] stretch goal: add this in the Quick Edit view.

**Comment by benlk** [comment]
Based on today's scrumming, I'm going to split the above comment into a PR and a handful of issues, some of which need to be fixed before we ship this in Largo and some which can wait. for later.

**Comment by benlk** [comment]
#1010 merged, so I'm closing this.
