### ISSUE TITLE
Filter and action suggestions for the LMP return

### ISSUE THREAD

**Issue by benlk** [INN/largo#929]
In function [largo_load_more_posts](https://github.com/INN/Largo/blob/master/inc/ajax-functions.php), we should do one or both of the following:

Add a before and after action to the output part of the LMP:

``` php

        do_action('lmp_before');

        if ( $query->have_posts() ) {
            while ( $query->have_posts() ) : $query->the_post();
                $partial = 'home';
                if($_POST['is_series_landing'] === true || $_POST['is_series_landing'] === 1) {
                    $partial = 'series';
                    $opt = $_POST['opt'];
                }
                $partial = ( get_post_type() == 'argolinks' ) ? 'argolinks' : $partial;
                get_template_part( 'partials/content', $partial );
            endwhile;
        }

        do_action('lmp_after');

```

Wrap the whole of the LMP in an output buffer, filter the contents of the buffer, and then print the contents of the buffer before `wp_die();`

``` php
        do_action('lmp_after');

        $ret = ob_get_clean();
        apply_filters('lmp_filter', $ret);
        echo $ret;
        wp_die();
```
## Why?

Because it would remove a lot of reasons for child themes to build their own LMPs to have different formatting. This makes it easier to wrap a div around the LMP results, for example if you wanted to put the returned post partials into a `div.row-fluid`

**Comment by benlk** [comment]
I like the idea of filters more, just because it's way more versatile. but actions was what came to mind first.

**Comment by benlk** [comment]
A complementary set of changes would be in [partials/home-post-list.php](https://github.com/INN/Largo/blob/master/partials/home-post-list.php), with actions before and after the posts. This would allow containing divs to be wrapped, if the child theme needed a div around the pre-loaded posts to match something in the LMP filter/hooks.

```php
if ($query->have_posts()) {

	do_action('largo_pre_home_post_list');

	while ($query->have_posts()) : $query->the_post();
		//if the post is in the array of post IDs already on this page, skip it. Just a double-check
		if (in_array(get_the_ID(), $shown_ids))
			continue;
		else {
			$shown_ids[] = get_the_ID();
			do_action('largo_before_home_list_post', $post, $query);
			get_template_part('partials/content', 'home');
			do_action('largo_after_home_list_post', $post, $query);
		}
	endwhile;

	do_action('largo_post_home_post_list');

	largo_content_nav('nav-below');
} else {
```

**Comment by aschweigert** [comment]
Seems fine to me, throwing to @rnagle for his input first

**Comment by benlk** [comment]
I'd like to use this in http://jira.inn.org/browse/WE-15 instead of doing a custom LMP and home.php, if possible.

**Comment by benlk** [comment]
https://github.com/INN/largo/blob/v0.5.5.4/partials/home-post-list.php#L31-L34

We got the home post list actions in, and it would be nice to have those in the LMP:

https://github.com/INN/Largo/blob/v0.5.5.4/inc/ajax-functions.php#L124-L129
