### ISSUE TITLE
Make sure all functions are properly namespaced and prefixed.

### ISSUE THREAD

**Issue by benlk** [INN/largo#935]
From #933:
- [ ] Make sure that all the `argo_` and `navis_` and other-prefixed code uses `largo_` as a prefix.
- [ ] What other prefixes are used?
- [ ] Apply PHP namespaces to all Largo files: https://secure.php.net/manual/en/language.namespaces.php
- [ ] Check that all functions have stubbed tests at least.
- [ ] Check all child themes that we know about
- [ ] Write warnings in the release notes about breaking changes
- [ ] Contact theme maintainers that we have contact info for?

**Comment by aschweigert** [comment]
this is important to do (eventually) but super time-consuming so we'll probably need to break this issue up before we even attempt to tackle it

**Comment by rclations** [comment]
this will be fixed in #1449 and #1447
