### ISSUE TITLE
Header search box style consistency

### ISSUE THREAD

**Issue by benlk** [INN/Largo#937]
Styles for `#header-search` only apply to the search in the homepage header or in the global nav (if enabled).

They do not apply to the search in the sticky nav.

For consistency, these styles should use a different, common selector.

**Comment by aschweigert** [comment]
Let's try to get this with RNS-55

**Comment by benlk** [comment]
Hmm. The search box in the global nav is being hidden by CSS, a bug introduced in https://github.com/INN/Largo/commit/1c2ff94a72b2e9b73591c5f1fc5a318c483ed10c

**Comment by benlk** [comment]
Because `.form-search` lost the preceding selector `.nav-right .form-search`, and so the global nav search gains the hidden visibility of the sticky nav search.

**Comment by benlk** [comment]
Nope, that's not it. It's that the `.form-search` rules weren't in the `.sticky-nav-holder`.
