### ISSUE TITLE
Customizing Widgets

### ISSUE THREAD

**Issue by 1000camels** [INN/Largo#946]
As far as I can tell from the code and from attempts to override widgets within my Child Theme, there is no way to do this.

I'm not sure what it would take to implement this, but I see in /inc/widgets.php, a lot of hardwired references to the widget files. Those paths should be prefaced by get_stylesheet_directory().

Is this something that can be fixed?

**Comment by aschweigert** [comment]
Not sure I understand your question...are you trying to register a widget from the child theme to replace a widget in the parent theme? What are you trying to customize?

**Comment by 1000camels** [comment]
Yes. Exactly that. And it should work, but it is not. In looking at the code, it looks right, but the copied widget in my child theme at inc/widgets/largo-sidebar-featured.php does not load.

I am trying to adjust it so that excerpts are shown if they exist.

**Comment by 1000camels** [comment]
do I have to override the whole directory, inc/widgets?

**Comment by aschweigert** [comment]
It's not enough to just copy the widget over to the correct directory, unfortunately. The WordPress parent/child descendent thing is not quite *that* smart (I wish). 

What you'll need to is unregister the widget you're trying to modify and then register your new version of that widget. Here's a code example from one of our child themes that should help: https://bitbucket.org/projectlargo/theme-georgianewslab/src/bdfc765c3cbc238c6bfc9b2b6c4f5dc086efefff/functions.php?at=master&fileviewer=file-view-default#functions.php-125

If the change you're trying to make is fairly simple, let us know. We might be able to just add a filter of something in the next release to make that easier for you without having to copy over the entire widget.

**Comment by 1000camels** [comment]
Great. Thank you.

I would recommend that line 43 in inc/widgets/largo-sidebar-featured.php be replaced with the following. Excerpts should be used if they exist.

<?php
                        if( !has_excerpt() ) {
                                echo '<p>' . largo_trim_sentences( get_the_content(), $instance['num_sentences'] ) . '</p>';
                        } else {
                                echo '<p>' . get_the_excerpt() . '</p>';
                        }
                        ?>

**Comment by aschweigert** [comment]
That widget is actually deprecated at this point in favor of just using the largo recent posts widget so that might actually be a simpler solution as that widget does give you a bit more control over how the excerpt appears.

**Comment by 1000camels** [comment]
Thanks. Will switch to that new widget.
