### ISSUE TITLE
Update Widgets PHP4 Style Constructors

### ISSUE THREAD

**Issue by dryanmedia** [INN/Largo#949]
So.... we're actually running WP 4.3.1 in production without problems. The sky hasn't fallen. But we should probably update these soon.

``` php
Notice: The called constructor method for WP_Widget is deprecated since version 4.3.0! Use
__construct()
instead. in /vagrant/wp-includes/functions.php on line 3457 Notice: The called constructor method for WP_Widget is deprecated since version 4.3.0! Use
__construct()
```
https://make.wordpress.org/core/2015/07/02/deprecating-php4-style-constructors-in-wordpress-4-3/

**Comment by aschweigert** [comment]
PR in, just needs to be reviewed and merged
