### ISSUE TITLE
New social buttons on single-column articles

### ISSUE THREAD

**Issue by benlk** [INN/Largo#961]
- [x] Theme option to enable it
- [x] Social button markup goes in a template `<script type="text/html"` tag on page load
- [x] The viewport width where this social icon should be displayed is output to a JSON object in a script tag by a pluggable function, with associated notices in 
    - [x] the LESS files for this social icons bar and in 
    - [x] the PHP that draws the HTML of sidebar (See how LMP does this)
- [x] new javascript:
    - [x] On screen resize or initial page load, if viewport width is wider than the allowable width in the template tag, then do the following:
    - [x] template tag gets copied into article area (This ticket isn't going to move the post-header social icons or require the presence of a widget in the article-bottom)
    - [x] Scrollable social icons are fixed in position, and only visible between the top and bottom of the article, with the following exceptions:
        - if the top social icons are visible, the scrollable icons' initial offset from the top of the story is the height of the viewport, so that both are not visible at the same time.
        - if the Largo Follow widget is in the article-bottom widget area, the scrollable icons' initial offset from the bottom of the story is the height of the viewport, so that both are not visible at the same time.
        - if the combination of the two above constraints creates overlapping zones of "don't display the icons here", just don't display the icons at all.
    - [x] if the screen resizes to less than the allowable width, ~~remove~~ `display:none;` the icons element.
- [x] Styles 
    - vertical column of buttons, instead of horizontal row

## Why:

For RNS, Women's eNews, and Cornell Sun http://jira.inn.org/browse/WE-18 http://jira.inn.org/browse/RNS-41

**Comment by benlk** [comment]
Is there an estimate for how wide the buttons should be when styled? If they're less than 46px wide, then with default largo styles they'll fit in this 46.change-px-wide gutter on 769px-and-wider tablets. 

<img width="1002" alt="screen shot 2015-11-10 at 12 48 51 pm" src="https://cloud.githubusercontent.com/assets/1754187/11070419/8a3ad1f6-87a9-11e5-8a06-a54c5930690f.png">

768px is a lot of largo breakpoints for tablet/desktop styles. The next breakpoint up is 979px, where 980px brings us a much-wider gutter:

<img width="741" alt="screen shot 2015-11-10 at 12 49 06 pm" src="https://cloud.githubusercontent.com/assets/1754187/11070418/8a3a24cc-87a9-11e5-8ebe-30ee819b026e.png">

**Comment by kaeti** [comment]
46px might be too tight, especially thinking about space on either side. Does that size only happen on tablet/smaller desktop windows?

**Comment by benlk** [comment]
The padding there is a percent of the column width, at 6.38297872% of the column. It's 50px wide at 820px viewport, 60px at 976px, and then jumps up to 158px at 980px, shown in the second screenshot above.

It keeps the 6.3% padding down to 520px, but I wouldn't want to show the social icons below 768px.

**Comment by kaeti** [comment]
I don't think we need to show the floating toolbar on tablet sizes.

**Comment by benlk** [comment]
Notes from hipchat: It gets positioned outside the area bounded by `#main`, in the padding/margin area of `#page`:

<img width="1355" alt="screen shot 2015-11-10 at 1 21 54 pm" src="https://cloud.githubusercontent.com/assets/1754187/11071317/3969a766-87ae-11e5-9777-3da2cec98ca3.png">

**Comment by benlk** [comment]
Note to self: Floating social buttons need to be positioned relative to the viewport, `fixed`, not relative to elements on the page. The positioning is (probably?) going to have to be calculated in Js, ~~unless CSS math can~~

Older Androids with screens wider than 1200px exist: http://caniuse.com/#search=calc

**Comment by benlk** [comment]
Current state of 961-single-column-social-buttons:

- new social sidebar appears off left side of story when the header element (containing the social buttons) or the hero are offscreen.
- new social sidebar remains fixed halfway up the screen as the reader scrolls, and fades out as they approach the bottom offset (the article-bottom widget area, the comments area, or the site footer, in fallback order)
- minimum viewport width for theme is set by pluggable function `largo_floating_social_button_width_json` so child themes can override that, and the whole set of javascript is enqueued with the pluggable function `largo_floating_social_button_js` in case a child theme needs to change how that works for reasons.

To do: 

- [ ] get icons to be stuck to the page a viewport-height below the header social buttons on page load, and then stick to the page again when within a viewport-height of the bottom offset.
- [ ] review styles

**Comment by aschweigert** [comment]
log time on social icons refresh ticket (was WE-18, now RNS-58)

**Comment by rnagle** [comment]
@benlk I merged the work for this into `develop` but there are a few more things to do. @aschweigert reports the email option does not work (probably not a problem confined to just the floating social icons). Please address this issue and open another PR for review.

**Comment by benlk** [comment]
Also, the `<a>` in the button is very small within the containing `<span>`:

<img width="462" alt="screen shot 2015-12-02 at 11 07 59 am" src="https://cloud.githubusercontent.com/assets/1754187/11541223/12793b78-98ff-11e5-8363-4b822bac54bf.png">


The click targets are smaller than they should be.

**Comment by benlk** [comment]
The reason the email button doesn't work on the floating social buttons is because the social sharing button's `sharer.init()` (that binds the onclick handler for the email popup) is only run on page load, when the floating social buttons don't exist yet. Does it make sense to make the `sharer` object a window variable so that the floating social button creation function can rerun `sharer.init`?

When the popup appears for email, it's because the onClick handler is *only* called when the `span.custom-share-button` is clicked, not any of the child elements of that element. When it doesn't pop up, it's because an element within the `span` was clicked. :disappointed:
