### ISSUE TITLE
load-more-posts.js isn't loaded minified if LARGO_DEBUG is false

### ISSUE THREAD

**Issue by benlk** [INN/Largo#967]
https://github.com/INN/Largo/blob/master/inc/ajax-functions.php#L18 loads the file always fron the un-minified path `/js/load-more-posts.js`, instead of using `/js/load-more-posts.min.js` if `LARGO_DEBUG` is false.

**Comment by aschweigert** [comment]
this is a five minute (or less) change, yes?

**Comment by benlk** [comment]
Should be.
