### ISSUE TITLE
Banner ad zone options are on different pages in the theme options.

### ISSUE THREAD

**Issue by benlk** [INN/largo#968]
To put a banner ad above the footer, check "Include an additional widget region ("sidebar") just above the site footer region" option in Theme Options > Layout Options.

To put a banner ad above the navigation, check "Enable Optional Leaderboard Ad Zone" option in Theme Options > Advanced Options

Why aren't these on the same page of the settings?

**Comment by rclations** [comment]
this should be resolved when theme options move to the customizer in .7
