### ISSUE TITLE
Analytics bridge filter, CSS for widget in article-bottom widget area

### ISSUE THREAD

**Issue by benlk** [INN/Largo#971]
This will require [INN/analytic-bridge #13](https://github.com/INN/analytic-bridge/issues/13) to be finished first.

- [x] pluggable function that:
    - [x] accepts as input arguments including $args and $instance
    - [x] when the sidebar is article-bottom, set the count of posts to 3
- [x] CSS for three-column display of posts with and without thumbnails in the article-bottom area

For [WE-20](http://jira.inn.org/browse/WE-20)

**Comment by aschweigert** [comment]
for cornell sun (CS-22)

**Comment by benlk** [comment]
This is to be the Largo default, right?

**Comment by aschweigert** [comment]
yes

**Comment by benlk** [comment]
CS-22, WE-20, RNS: three-column article-bottom

RNS, etc: ol styles for sidebar

It was decided in #1003 to not force this, just change the default.

**Comment by benlk** [comment]
I think this is okay to close?

**Comment by aschweigert** [comment]
This might need a little love at intermediate breakpoints (gets a little cramped) but this particular ticket can probably be closed
