### ISSUE TITLE
Remove sticky footer entirely

### ISSUE THREAD

**Issue by benlk** [INN/Largo#974]
After #973:

- [x] figure out how to put the "Follow" a tag/category/author functionality into the floating social buttons or elsewhere (partially covered in #973)
- [x] remove sticky footer code
- [x] remove sticky footer option from theme options
- [x] remove sticky footer js
- [x] remove sticky footer LESS

**Comment by aschweigert** [comment]
to @kaeti first because we need to decide how to handle the "follow" behavior at the bottom of stories. Let's collect a few examples of similar behavior and design something that will be relatively low-effort to implement for now but also plan to improve this over time.

**Comment by kaeti** [comment]
Right now the "follow" links on the sticky footer are:

- link to category page
- link to author RSS
- link to author page

The link to the author page and category page are handled in the byline and the top term showing up on article pages. 

We can add an author or category RSS link to the floating sidebar.

If/when we build more sophisticated following options, we can add those to the sidebar as well.

**Comment by aschweigert** [comment]
I believe it will also include a link to the author's twitter account if they provide one

**Comment by kaeti** [comment]
That's included in the author bio widget, so if people want it on the page, it's available. I don't think that should be in the floating sidebar (we could possibly put it in the byline, though I don't love that).

**Comment by aschweigert** [comment]
To add a little more context to the "follow" question, the bigger issue is how do we encourage people to follow a given topic/author and communicate that in the design. I think we all agree that the current behavior/placement is not optimal. Some of that I think makes sense to add to the floating sidebar but I think more as a general "follow" action that then gives a user of what's available to follow and the various ways that might be available to follow that thing)

**Comment by kaeti** [comment]
Are you talking about adding additional follow functionality? Or just having a follow option in the sidebar that then has a pop-out/tooltip box with all the follow options?

**Comment by aschweigert** [comment]
@kaeti i think adding a trigger (with whatever icon make sense) in the floating sidebar with a popout sort of thing that covers the current options would be fine, we could always add additional options later as we have time to think through it a bit more (getting email notifications is something we get a lot of requests for, for example)

**Comment by benlk** [comment]
The floating sidebar isn't visible on mobile or narrower tablets, but the sticky footer has been visible on all sizes. How will we keep that functionality on narrower screens? Or should we just leave it to the article-bottom widgets?

**Comment by kaeti** [comment]
All of the follow functionality is represented elsewhere on the article page, so I'm not concerned about not having the floating sidebar on smaller screen sizes.

We could potentially work this into the top/bottom social toolbars, as well.

**Comment by aschweigert** [comment]
Yeah, I'm a +1 on incorporating is into the top/bottom toolbars when those options are enabled, seems like the cleanest way to go

**Comment by aschweigert** [comment]
log time for this on the social icons refresh ticket

**Comment by kaeti** [comment]
I'm going to mock up some patterns for how we can handle the follow stuff and grab a few external examples.

**Comment by kaeti** [comment]
Here are some mock ups of one way we could handle the items from the sticky footer. The specific items in the "more" tool tip could change, which gives us the flexibility to add more in the future. 

<img width="909" alt="screen shot 2015-12-02 at 3 29 20 pm" src="https://cloud.githubusercontent.com/assets/884444/11544814/a1a44f22-9909-11e5-84be-ce27a1b53e94.png">
<img width="645" alt="screen shot 2015-12-02 at 3 29 53 pm" src="https://cloud.githubusercontent.com/assets/884444/11544826/a968c26a-9909-11e5-8e90-443259094b12.png">
<img width="585" alt="screen shot 2015-12-02 at 3 29 46 pm" src="https://cloud.githubusercontent.com/assets/884444/11544832/b0fa6c22-9909-11e5-8ca9-a7847293e45a.png">

**Comment by aschweigert** [comment]
looks good to me. covers what we have now and give us room to grow. let's go with it.

**Comment by benlk** [comment]
Should the new + button be added before or after [the filter on the output](https://github.com/INN/Largo/blob/develop/inc/post-tags.php#L201) of `largo_post_social_links()`?

Does it make more sense for the contents of the menu to be filterable, or for the menu to be an action hook with our options hooked on it by default and child themes adding or unhooking actions as desired?

**Comment by aschweigert** [comment]
I don't understand the second question, but the answer to the first one is that the + button should always go after all other share buttons, including any future ones that might be added via the filter from a child theme

**Comment by benlk** [comment]
That answers the first question. The + button would go after the filter on largo_post_social_links.

The second question has to do with how the menu in the + button is created in Largo's code. If we want child themes to be able to add to the + menu, there are a few ways to do that:

1. The contents of the + menu are a pluggable function. Replace the function to customize the menu.
2. The contents of the + menu are added to a variable which is then passed through a WordPress filter that child themes can use to remove elements from the menu with string commands or add elements to the menu by concatenating.
3. The + menu's display code contains an action hook, and then everything seen above would be an `li` output by a separate function hooked on that action hook.

In the third option, a child theme wanting to remove, say, the RSS buttons, would remove the function that outputs the RSS buttons from the hook. A theme wanting to add a button would just hook a function that outputs another `li`.

**Comment by aschweigert** [comment]
yeah, i would go with either option 2 or 3, probably 3. However, we should not assume that the output of those functions hooked onto that would always output a <li>, that could be the default, but probably best to add a parameter to said functions to also allow that to be modified. That way those functions would be more usable in other contexts should we need them.

**Comment by rnagle** [comment]
This has been merged with #1017, but there is still at least one thing to consider. A note that came out of review/demo for this is that the link text in the `+ more` popover should include the title of the topic (tag, category or other taxonomy). This might be problematic if the term is especially long and might require the link's line to wrap.

**Comment by rnagle** [comment]
Addressed the issue from my last comment. This is done!
