### ISSUE TITLE
Remove all references to the twitter share count

### ISSUE THREAD

**Issue by benlk** [INN/Largo#975]
- [x] largo_post_social_links
- [x] theme options
- [ ] LESS files?
- [x] Note in the release notes

**Comment by aschweigert** [comment]
fwiw, twitter is killing this anyway so for us it's really just to scrub references to it

**Comment by aschweigert** [comment]
log time for this on the social icons refresh ticket

**Comment by benlk** [comment]
So far the only places David and I saw this referenced were in the docs and in the translation files. It doesn't appear to be in the theme options any more, or in any widget settings.
