### ISSUE TITLE
Largo Tax List Widget doesn't display thumbnails for categories or tags

### ISSUE THREAD

**Issue by benlk** [INN/Largo#977]

**Comment by aschweigert** [comment]
not sure what this means...are we pulling a thumbnail from the series landing page? if so, categories and tags presently don't have a way to set a featured image/thumbnail for the term so this is not unexpected.

**Comment by benlk** [comment]
For series, the post thumbnail is first pulled from the series landing page. If no thumbnail is found it falls back to the thumbnail of the first post in the series. In categories or tags, the thumbnail is drawn instead immediately from the first post in the term.

The bug behavior is that it isn't finding thumbnails for posts in categories or tags, but is finding thumbnails for posts in series when the series landing pae does not exist.

**Comment by aschweigert** [comment]
needed for women's enews

**Comment by benlk** [comment]
And for #928.
