### ISSUE TITLE
Largo Tax List Widgets sometimes don't display headlines in categories

### ISSUE THREAD

**Issue by benlk** [INN/Largo#978]

**Comment by benlk** [comment]
@ryan: Can you list the details of the categories that were causing the problem here?

**Comment by rnagle** [comment]
Sure. I was testing this on the Women's eNews site with the "cartoon" (1446) and "Culture" (312) categories.

**Comment by aschweigert** [comment]
needed for women's enews

**Comment by benlk** [comment]
This only affects those two categories, out of a list of `1446,312,330,308,313,301`.

The array of posts being passed to `largo_first_headline_in_post_array($array)` is 0, because

```
$posts = get_posts(array(
    'category_name' => $item->name,
));
```

returns zero posts for those two categories, despite the category `$item` having a name.

**Comment by benlk** [comment]
And there aren't any non-printing characters in those term's names.

Changing the categories' names doesn't cause headlines to show up.

It's not that there's a space or a slash in 312's name property "Cultural Trends/Popular Culture", because 1446's name property "cartoon" has neither.

**Comment by benlk** [comment]
I'm thinking that this is either some oddity with those categories in the database, causing them to return 0 posts despite having many posts, or there's a bug with WordPress.

**Comment by benlk** [comment]
Sure. Changing the slug of the category 'cartoon', where the slug is not used in this code at all, fixes the problem. `cartoon7794` became `cartoon`, and everything began working.

But not for 312/"Cultural Trends/Popular Culture".

**Comment by benlk** [comment]
I think that this is going to be resolved by all the database changes that will come with the Women's eNews taxonomy terms cleanup, so I'm going to close this for now.

If it's not fixed after then, this should be reopened, but it's very likely a problem with the database and the import.
