### ISSUE TITLE
Add right-hand padding to horizontal social toolbar

### ISSUE THREAD

**Issue by kaeti** [INN/Largo#996]
There's not enough padding on the righthand side of the individual social links in the horizontal toolbar. Let's add some more! (either equal amount to left side, or double what is currently there)

<img width="428" alt="screen shot 2015-12-01 at 3 06 22 pm" src="https://cloud.githubusercontent.com/assets/884444/11514301/586b77f8-983d-11e5-8062-d0083fb26f32.png">

**Comment by benlk** [comment]
Closed in #998 and #1017.
